import { useTranslation } from 'react-i18next';
import type { ManagedNpmPackageStatusSnapshot } from '../../../types/dependency-management.js';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { cn } from '@/lib/utils';
import { getManagedPackageDisplayStatus, getManagedPackageRequiredVersion, isManagedPackageOutdated, managedPackageRowClassName, packageBadgeVariant } from './dependencyManagementPageModel';

export function NpmPackageTable({ titleKey = 'dependencyManagement.packageTable.title', descriptionKey = 'dependencyManagement.packageTable.description', packages, highlightedPackageIds = [], selectedIds, onSelectionChange }: {
  titleKey?: string; descriptionKey?: string; packages: ManagedNpmPackageStatusSnapshot[]; highlightedPackageIds?: string[]; selectedIds: string[]; onSelectionChange: (ids: string[]) => void;
}) {
  const { t } = useTranslation(['common', 'components']);
  const highlighted = new Set(highlightedPackageIds);
  return <Card><CardHeader><CardTitle className="text-lg">{t(titleKey)}</CardTitle><CardDescription>{t(descriptionKey)}</CardDescription></CardHeader><CardContent><Table className="min-w-[720px]"><TableHeader><TableRow><TableHead className="w-12" /><TableHead className="min-w-[240px]">{t('dependencyManagement.packageTable.tool')}</TableHead><TableHead>{t('dependencyManagement.package.category')}</TableHead><TableHead>{t('dependencyManagement.package.version')}</TableHead><TableHead className="min-w-[220px]">{t('dependencyManagement.package.packageName')}</TableHead></TableRow></TableHeader><TableBody>{packages.map((item) => { const status = getManagedPackageDisplayStatus(item); const required = getManagedPackageRequiredVersion(item); return <TableRow key={item.id} className={cn(managedPackageRowClassName(item), highlighted.has(item.id) && 'ring-1 ring-inset ring-amber-500/50')}><TableCell className="align-top"><Checkbox checked={selectedIds.includes(item.id)} onCheckedChange={(checked) => onSelectionChange(checked ? [...selectedIds, item.id] : selectedIds.filter((id) => id !== item.id))} aria-label={item.definition.displayName} /></TableCell><TableCell className="align-top"><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{item.definition.displayName}</span>{item.definition.required === true ? <Badge variant="outline">★ {t('dependencyManagement.batch.requiredLabel', { ns: 'components' })}</Badge> : null}<Badge variant={packageBadgeVariant(item)}>{t(`dependencyManagement.packageStatus.${status}`)}</Badge></div><div className="text-xs text-muted-foreground">{t(item.definition.descriptionKey)}</div></TableCell><TableCell className="align-top"><Badge variant="secondary">{t(`dependencyManagement.categories.${item.definition.category}`)}</Badge></TableCell><TableCell className="align-top"><div>{item.version ?? t('dependencyManagement.unavailable')}</div>{isManagedPackageOutdated(item) ? <div className="text-xs text-amber-700">{t('dependencyManagement.package.versionMismatch', { current: item.version ?? t('dependencyManagement.unavailable'), required: required ?? item.definition.installSpec })}</div> : null}</TableCell><TableCell className="max-w-[220px] break-all align-top text-muted-foreground">{item.definition.packageName}</TableCell></TableRow>; })}</TableBody></Table></CardContent></Card>;
}
