import type { AgentCliDefinition } from '../types/agent-cli-catalog.js';

export const desktopAgentCliCatalog: readonly AgentCliDefinition[] = [
  {
    id: 'claude-code',
    displayName: 'Claude Code',
    descriptionKey: 'npmManagement.packages.claudeCode.description',
    commandName: 'claude',
    commandCandidates: ['claude'],
    providerId: 'claude-code',
    docsLinkId: 'claudeCodeSetup',
  },
  {
    id: 'codex',
    displayName: 'Codex',
    descriptionKey: 'npmManagement.packages.codex.description',
    commandName: 'codex',
    commandCandidates: ['codex'],
    providerId: 'codex',
    docsLinkId: 'codexSetup',
  },
  {
    id: 'copilot',
    displayName: 'GitHub Copilot',
    descriptionKey: 'npmManagement.packages.githubCopilot.description',
    commandName: 'copilot',
    commandCandidates: ['copilot', 'github-copilot-cli'],
    providerId: 'copilot',
    docsLinkId: 'copilotSetup',
  },
  {
    id: 'opencode',
    displayName: 'OpenCode',
    descriptionKey: 'npmManagement.packages.opencode.description',
    commandName: 'opencode',
    commandCandidates: ['opencode'],
    providerId: 'opencode',
    docsLinkId: 'opencodeSetup',
  },
  {
    id: 'qoder',
    displayName: 'QoderCLI',
    descriptionKey: 'npmManagement.packages.qoder.description',
    commandName: 'qodercli',
    commandCandidates: ['qodercli', 'qoder'],
    providerId: 'qoder',
    docsLinkId: 'qoderSetup',
  },
  {
    id: 'kiro-cli',
    displayName: 'Kiro',
    descriptionKey: 'promptGuidance.tools.kiro.description',
    commandName: 'kiro-cli',
    commandCandidates: ['kiro-cli', 'kiro'],
    providerId: 'kiro-cli',
    docsLinkId: 'kiroSetup',
  },
  {
    id: 'kimi',
    displayName: 'Kimi',
    descriptionKey: 'promptGuidance.tools.kimi.description',
    commandName: 'kimi',
    commandCandidates: ['kimi', 'kimi-cli', 'kimicli'],
    providerId: 'kimi',
    docsLinkId: 'kimiSetup',
  },
  {
    id: 'gemini',
    displayName: 'Gemini',
    descriptionKey: 'npmManagement.packages.gemini.description',
    commandName: 'gemini',
    commandCandidates: ['gemini'],
    providerId: 'gemini',
    docsLinkId: 'geminiSetup',
  },
  {
    id: 'deepagents',
    displayName: 'DeepAgents',
    descriptionKey: 'promptGuidance.tools.deepagents.description',
    commandName: 'deepagents',
    commandCandidates: ['deepagents'],
    providerId: 'deepagents',
    docsLinkId: 'deepagentsSetup',
  },
  {
    id: 'codebuddy',
    displayName: 'CodeBuddy',
    descriptionKey: 'npmManagement.packages.codebuddy.description',
    commandName: 'codebuddy',
    commandCandidates: ['codebuddy', 'cbc'],
    providerId: 'codebuddy',
  },
  {
    id: 'hermes',
    displayName: 'Hermes',
    descriptionKey: 'promptGuidance.tools.hermes.description',
    commandName: 'hermes',
    commandCandidates: ['hermes', 'hermes-cli'],
    providerId: 'hermes',
    docsLinkId: 'hermesSetup',
  },
] as const;
