import type { ManagedNpmPackageDefinition, ManagedNpmPackageId } from '../types/npm-management.js';

export const managedNpmPackages: readonly ManagedNpmPackageDefinition[] = [
  {
    id: 'hagiscript',
    packageName: '@hagicode/hagiscript',
    displayName: 'hagiscript',
    descriptionKey: 'npmManagement.packages.hagiscript.description',
    binName: 'hagiscript',
    installSpec: '@hagicode/hagiscript',
    category: 'bootstrap',
    installMode: 'embedded-npm',
    required: true,
  },
  {
    id: 'openspec',
    packageName: '@fission-ai/openspec',
    displayName: 'OpenSpec',
    descriptionKey: 'npmManagement.packages.openspec.description',
    binName: 'openspec',
    installSpec: '@fission-ai/openspec@1.3.1',
    category: 'workflow',
    installMode: 'hagiscript-sync',
    required: true,
  },
  {
    id: 'skills',
    packageName: 'skills',
    displayName: 'Skills',
    descriptionKey: 'npmManagement.packages.skills.description',
    binName: 'skills',
    installSpec: 'skills@1.5.1',
    category: 'workflow',
    installMode: 'hagiscript-sync',
    required: true,
  },
  {
    id: 'omniroute',
    packageName: 'omniroute',
    displayName: 'OmniRoute',
    descriptionKey: 'npmManagement.packages.omniroute.description',
    binName: 'omniroute',
    installSpec: 'omniroute@3.6.9',
    category: 'developer-tool',
    installMode: 'hagiscript-sync',
    required: true,
  },
  {
    id: 'claude-code',
    packageName: '@anthropic-ai/claude-code',
    displayName: 'Claude Code',
    descriptionKey: 'npmManagement.packages.claudeCode.description',
    binName: 'claude',
    installSpec: '@anthropic-ai/claude-code',
    category: 'agent-cli',
    installMode: 'hagiscript-sync',
    agentCliId: 'claude-code',
    docsLinkId: 'claudeCodeSetup',
  },
  {
    id: 'codex',
    packageName: '@openai/codex',
    displayName: 'Codex',
    descriptionKey: 'npmManagement.packages.codex.description',
    binName: 'codex',
    installSpec: '@openai/codex',
    category: 'agent-cli',
    installMode: 'hagiscript-sync',
    agentCliId: 'codex',
    docsLinkId: 'codexSetup',
  },
  {
    id: 'github-copilot',
    packageName: '@github/copilot',
    displayName: 'GitHub Copilot',
    descriptionKey: 'npmManagement.packages.githubCopilot.description',
    binName: 'copilot',
    installSpec: '@github/copilot',
    category: 'agent-cli',
    installMode: 'hagiscript-sync',
    agentCliId: 'copilot',
    docsLinkId: 'copilotSetup',
  },
  {
    id: 'codebuddy',
    packageName: '@tencent-ai/codebuddy-code',
    displayName: 'CodeBuddy',
    descriptionKey: 'npmManagement.packages.codebuddy.description',
    binName: 'codebuddy',
    installSpec: '@tencent-ai/codebuddy-code',
    category: 'agent-cli',
    installMode: 'hagiscript-sync',
    agentCliId: 'codebuddy',
  },
  {
    id: 'opencode',
    packageName: 'opencode-ai',
    displayName: 'OpenCode',
    descriptionKey: 'npmManagement.packages.opencode.description',
    binName: 'opencode',
    installSpec: 'opencode-ai',
    category: 'agent-cli',
    installMode: 'hagiscript-sync',
    agentCliId: 'opencode',
    docsLinkId: 'opencodeSetup',
  },
  {
    id: 'qoder',
    packageName: '@qoder-ai/qodercli',
    displayName: 'QoderCLI',
    descriptionKey: 'npmManagement.packages.qoder.description',
    binName: 'qodercli',
    installSpec: '@qoder-ai/qodercli',
    category: 'agent-cli',
    installMode: 'hagiscript-sync',
    agentCliId: 'qoder',
    docsLinkId: 'qoderSetup',
  },
  {
    id: 'gemini',
    packageName: '@google/gemini-cli',
    displayName: 'Gemini',
    descriptionKey: 'npmManagement.packages.gemini.description',
    binName: 'gemini',
    installSpec: '@google/gemini-cli',
    category: 'agent-cli',
    installMode: 'hagiscript-sync',
    agentCliId: 'gemini',
    docsLinkId: 'geminiSetup',
  },
] as const;

export const managedAgentCliPackages = managedNpmPackages.filter(
  (definition) => definition.category === 'agent-cli',
);

export function findManagedNpmPackage(id: string): ManagedNpmPackageDefinition | null {
  return managedNpmPackages.find((definition) => definition.id === id) ?? null;
}

export function isManagedNpmPackageId(id: string): id is ManagedNpmPackageId {
  return findManagedNpmPackage(id) !== null;
}
