// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { RandomAccessStreamReference } from './RandomAccessStreamReference.js';

const IID_IAppDisplayInfo = WinGuid.parse('1aeb1103-e4d4-41aa-a4f6-c4a276e79eac');

const _IAppDisplayInfo = DynWinRtType.registerInterface(
    "IAppDisplayInfo", IID_IAppDisplayInfo)
    .addMethod("get_DisplayName", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Description", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("GetLogo", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.Size', [DynWinRtType.f32(), DynWinRtType.f32()])).addOut(DynWinRtType.runtimeClass('Windows.Storage.Streams.RandomAccessStreamReference', WinGuid.parse('33ee3134-1dd6-4e3a-8067-d1c162e8642b'))));

export function unpackSize(v) {
    const s = v.asStruct();
    return { width: s.getF32(0), height: s.getF32(1) };
}
const _unpackSize = unpackSize;
export const Size_Type = DynWinRtType.structType('Windows.Foundation.Size', [DynWinRtType.f32(), DynWinRtType.f32()]);
const _Size_Type = Size_Type;
export function packSize(v) {
    const s = DynWinRtStruct.create(Size_Type);
    s.setF32(0, v.width);
    s.setF32(1, v.height);
    return s;
}
const _packSize = packSize;

export class AppDisplayInfo {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IAppDisplayInfo);
    }
    get displayName() {
        return _IAppDisplayInfo.method(6).invoke(this._obj, []).toString();
    }
    get description() {
        return _IAppDisplayInfo.method(7).invoke(this._obj, []).toString();
    }
    getLogo(size) {
        return new RandomAccessStreamReference(_IAppDisplayInfo.method(8).invoke(this._obj, [_packSize(size).toValue()]));
    }
}
