// Generated by dynwinrt-codegen — do not edit
import { AppDisplayInfo } from './AppDisplayInfo.js';
import { AppExecutionContext } from './AppExecutionContext.js';
import { Package } from './Package.js';
import { User } from './User.js';

export declare class AppInfo {
    private constructor();
    static get current(): AppInfo;
    static getFromAppUserModelId(appUserModelId: string): AppInfo;
    static getFromAppUserModelIdForUser(user: User, appUserModelId: string): AppInfo;
    get id(): string;
    get appUserModelId(): string;
    get displayInfo(): AppDisplayInfo;
    get packageFamilyName(): string;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
    get package_(): Package;
    get executionContext(): AppExecutionContext;
    get supportedFileExtensions(): string[];
}

export declare class IAppInfo2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IAppInfo2;

    get package_(): Package;
}

export declare class IAppInfo3 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IAppInfo3;

    get executionContext(): AppExecutionContext;
}

export declare class IAppInfo4 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IAppInfo4;

    get supportedFileExtensions(): string[];
}
