// Generated by dynwinrt-codegen — do not edit
export type AppInstallerPolicySource = (typeof AppInstallerPolicySource)[keyof typeof AppInstallerPolicySource];
export declare const AppInstallerPolicySource: {
    readonly Default: 0;
    readonly System: 1;
};
