// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtValue, DynWinRtStruct } from '@microsoft/dynwinrt';
import { IReference_DateTime } from './IReference_DateTime.js';
import { IVectorView_Uri } from './IVectorView_Uri.js';
import { AppInstallerPolicySource } from './AppInstallerPolicySource.js';
import { Uri } from './Uri.js';

export interface PackageVersion {
    major: number;
    minor: number;
    build: number;
    revision: number;
}
/** Convert a WinRT struct value into a `PackageVersion` object. */
export declare function unpackPackageVersion(v: DynWinRtValue): PackageVersion;
export declare const PackageVersion_Type: DynWinRtType;
/** Convert a `PackageVersion` object into a WinRT struct value. */
export declare function packPackageVersion(v: PackageVersion): DynWinRtStruct;

export interface DateTime {
    universalTime: bigint;
}
/** Convert a WinRT struct value into a `DateTime` object. */
export declare function unpackDateTime(v: DynWinRtValue): DateTime;
export declare const DateTime_Type: DynWinRtType;
/** Convert a `DateTime` object into a WinRT struct value. */
export declare function packDateTime(v: DateTime): DynWinRtStruct;

export declare class AppInstallerInfo {
    private constructor();
    get uri(): Uri;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
    get onLaunch(): boolean;
    get hoursBetweenUpdateChecks(): number;
    get showPrompt(): boolean;
    get updateBlocksActivation(): boolean;
    get automaticBackgroundTask(): boolean;
    get forceUpdateFromAnyVersion(): boolean;
    get isAutoRepairEnabled(): boolean;
    get version(): PackageVersion;
    get lastChecked(): DateTime;
    get pausedUntil(): IReference_DateTime;
    get updateUris(): IVectorView_Uri;
    get repairUris(): IVectorView_Uri;
    get dependencyPackageUris(): IVectorView_Uri;
    get optionalPackageUris(): IVectorView_Uri;
    get policySource(): AppInstallerPolicySource;
}

export declare class IAppInstallerInfo2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IAppInstallerInfo2;

    get onLaunch(): boolean;

    get hoursBetweenUpdateChecks(): number;

    get showPrompt(): boolean;

    get updateBlocksActivation(): boolean;

    get automaticBackgroundTask(): boolean;

    get forceUpdateFromAnyVersion(): boolean;

    get isAutoRepairEnabled(): boolean;

    get version(): PackageVersion;

    get lastChecked(): DateTime;

    get pausedUntil(): IReference_DateTime;

    get updateUris(): IVectorView_Uri;

    get repairUris(): IVectorView_Uri;

    get dependencyPackageUris(): IVectorView_Uri;

    get optionalPackageUris(): IVectorView_Uri;

    get policySource(): AppInstallerPolicySource;
}
