// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { AppDisplayInfo } from './AppDisplayInfo.js';
import { AppExecutionContext } from './AppExecutionContext.js';
import { Package } from './Package.js';
import { User } from './User.js';
const _unwrap = (x) => x?._obj ?? x;

const IID_IAppInfo = WinGuid.parse('cf7f59b3-6a09-4de8-a6c0-5792d56880d1');
const IID_IAppInfoStatics = WinGuid.parse('cf1f782a-e48b-4f0c-9b0b-79c3f8957dd7');
const IID_IAppInfo2 = WinGuid.parse('be4b1f5a-2098-431b-bd25-b30878748d47');
const IID_IAppInfo3 = WinGuid.parse('09a78e46-93a4-46de-9397-0843b57115ea');
const IID_IAppInfo4 = WinGuid.parse('2f34bdeb-1609-4554-9f33-12e1e803e0d4');

const _IAppInfo = DynWinRtType.registerInterface(
    "IAppInfo", IID_IAppInfo)
    .addMethod("get_Id", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_AppUserModelId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_DisplayInfo", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.ApplicationModel.AppDisplayInfo', WinGuid.parse('1aeb1103-e4d4-41aa-a4f6-c4a276e79eac'))))
    .addMethod("get_PackageFamilyName", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

const _IAppInfoStatics = DynWinRtType.registerInterface(
    "IAppInfoStatics", IID_IAppInfoStatics)
    .addMethod("get_Current", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.ApplicationModel.AppInfo', WinGuid.parse('cf7f59b3-6a09-4de8-a6c0-5792d56880d1'))))
    .addMethod("GetFromAppUserModelId", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.runtimeClass('Windows.ApplicationModel.AppInfo', WinGuid.parse('cf7f59b3-6a09-4de8-a6c0-5792d56880d1'))))
    .addMethod("GetFromAppUserModelIdForUser", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))).addIn(DynWinRtType.hstring()).addOut(DynWinRtType.runtimeClass('Windows.ApplicationModel.AppInfo', WinGuid.parse('cf7f59b3-6a09-4de8-a6c0-5792d56880d1'))));

const _IAppInfo2 = DynWinRtType.registerInterface(
    "IAppInfo2", IID_IAppInfo2)
    .addMethod("get_Package", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.ApplicationModel.Package', WinGuid.parse('163c792f-bd75-413c-bf23-b1fe7b95d825'))));

const _IAppInfo3 = DynWinRtType.registerInterface(
    "IAppInfo3", IID_IAppInfo3)
    .addMethod("get_ExecutionContext", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.ApplicationModel.AppExecutionContext', ['Unknown', 'Host', 'Guest'], [0, 1, 2])));

const _IAppInfo4 = DynWinRtType.registerInterface(
    "IAppInfo4", IID_IAppInfo4)
    .addMethod("get_SupportedFileExtensions", new DynWinRtMethodSig().addOut(DynWinRtType.arrayType(DynWinRtType.hstring())));

export class AppInfo {
    _obj;
    static _s_IAppInfoStatics;
    static s_IAppInfoStatics() { return AppInfo._s_IAppInfoStatics ??= DynWinRtValue.activationFactory('Windows.ApplicationModel.AppInfo').cast(IID_IAppInfoStatics); }

    constructor(obj) {
        this._obj = obj.cast(IID_IAppInfo);
    }
    static get current() {
        return new AppInfo(_IAppInfoStatics.method(6).invoke(AppInfo.s_IAppInfoStatics(), []));
    }
    static getFromAppUserModelId(appUserModelId) {
        return new AppInfo(_IAppInfoStatics.method(7).invoke(AppInfo.s_IAppInfoStatics(), [DynWinRtValue.hstring(appUserModelId)]));
    }
    static getFromAppUserModelIdForUser(user, appUserModelId) {
        return new AppInfo(_IAppInfoStatics.method(8).invoke(AppInfo.s_IAppInfoStatics(), [_unwrap(user), DynWinRtValue.hstring(appUserModelId)]));
    }
    get id() {
        return _IAppInfo.method(6).invoke(this._obj, []).toString();
    }
    get appUserModelId() {
        return _IAppInfo.method(7).invoke(this._obj, []).toString();
    }
    get displayInfo() {
        return new AppDisplayInfo(_IAppInfo.method(8).invoke(this._obj, []));
    }
    get packageFamilyName() {
        return _IAppInfo.method(9).invoke(this._obj, []).toString();
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
    get package_() {
        return new Package(_IAppInfo2.method(6).invoke(this._obj.cast(IID_IAppInfo2), []));
    }
    get executionContext() {
        return _IAppInfo3.method(6).invoke(this._obj.cast(IID_IAppInfo3), []).toNumber();
    }
    get supportedFileExtensions() {
        return _IAppInfo4.method(6).invoke(this._obj.cast(IID_IAppInfo4), []).asArray().toStringVec();
    }
}

export class IAppInfo2 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IAppInfo2(obj.cast(IID_IAppInfo2));
    }

    get package_() {
        return new Package(_IAppInfo2.method(6).invoke(this._obj, []));
    }
}

export class IAppInfo3 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IAppInfo3(obj.cast(IID_IAppInfo3));
    }

    get executionContext() {
        return _IAppInfo3.method(6).invoke(this._obj, []).toNumber();
    }
}

export class IAppInfo4 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IAppInfo4(obj.cast(IID_IAppInfo4));
    }

    get supportedFileExtensions() {
        return _IAppInfo4.method(6).invoke(this._obj, []).asArray().toStringVec();
    }
}
