// Generated by dynwinrt-codegen — do not edit
import { AppDisplayInfo } from './AppDisplayInfo.js';
import { AppInfo } from './AppInfo.js';
import { User } from './User.js';

export declare class AppListEntry {
    private constructor();
    get displayInfo(): AppDisplayInfo;
    launchAsync(signal?: AbortSignal): Promise<boolean>;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
    get appUserModelId(): string;
    launchForUserAsync(user: User, signal?: AbortSignal): Promise<boolean>;
    get appInfo(): AppInfo;
}

export declare class IAppListEntry2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IAppListEntry2;

    get appUserModelId(): string;
}

export declare class IAppListEntry3 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IAppListEntry3;

    launchForUserAsync(user: User, signal?: AbortSignal): Promise<boolean>;
}

export declare class IAppListEntry4 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IAppListEntry4;

    get appInfo(): AppInfo;
}
