// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { AppDisplayInfo } from './AppDisplayInfo.js';
import { AppInfo } from './AppInfo.js';
import { User } from './User.js';
const _unwrap = (x) => x?._obj ?? x;

const IID_IAppListEntry = WinGuid.parse('ef00f07f-2108-490a-877a-8a9f17c25fad');
const IID_IAppListEntry2 = WinGuid.parse('d0a618ad-bf35-42ac-ac06-86eeeb41d04b');
const IID_IAppListEntry3 = WinGuid.parse('6099f28d-fc32-470a-bc69-4b061a76ef2e');
const IID_IAppListEntry4 = WinGuid.parse('2a131ed2-56f5-487c-8697-5166f3b33da0');

const _IAppListEntry = DynWinRtType.registerInterface(
    "IAppListEntry", IID_IAppListEntry)
    .addMethod("get_DisplayInfo", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.ApplicationModel.AppDisplayInfo', WinGuid.parse('1aeb1103-e4d4-41aa-a4f6-c4a276e79eac'))))
    .addMethod("LaunchAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.boolType())));

const _IAppListEntry2 = DynWinRtType.registerInterface(
    "IAppListEntry2", IID_IAppListEntry2)
    .addMethod("get_AppUserModelId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

const _IAppListEntry3 = DynWinRtType.registerInterface(
    "IAppListEntry3", IID_IAppListEntry3)
    .addMethod("LaunchForUserAsync", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.boolType())));

const _IAppListEntry4 = DynWinRtType.registerInterface(
    "IAppListEntry4", IID_IAppListEntry4)
    .addMethod("get_AppInfo", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.ApplicationModel.AppInfo', WinGuid.parse('cf7f59b3-6a09-4de8-a6c0-5792d56880d1'))));

export class AppListEntry {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IAppListEntry);
    }
    get displayInfo() {
        return new AppDisplayInfo(_IAppListEntry.method(6).invoke(this._obj, []));
    }
    async launchAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IAppListEntry.method(7).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toBool();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
    get appUserModelId() {
        return _IAppListEntry2.method(6).invoke(this._obj.cast(IID_IAppListEntry2), []).toString();
    }
    async launchForUserAsync(user, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IAppListEntry3.method(6).invoke(this._obj.cast(IID_IAppListEntry3), [_unwrap(user)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toBool();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    get appInfo() {
        return new AppInfo(_IAppListEntry4.method(6).invoke(this._obj.cast(IID_IAppListEntry4), []));
    }
}

export class IAppListEntry2 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IAppListEntry2(obj.cast(IID_IAppListEntry2));
    }

    get appUserModelId() {
        return _IAppListEntry2.method(6).invoke(this._obj, []).toString();
    }
}

export class IAppListEntry3 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IAppListEntry3(obj.cast(IID_IAppListEntry3));
    }

    async launchForUserAsync(user, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IAppListEntry3.method(6).invoke(this._obj, [_unwrap(user)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toBool();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
}

export class IAppListEntry4 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IAppListEntry4(obj.cast(IID_IAppListEntry4));
    }

    get appInfo() {
        return new AppInfo(_IAppListEntry4.method(6).invoke(this._obj, []));
    }
}
