// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtValue, DynWinRtStruct } from '@microsoft/dynwinrt';

export interface DateTime {
    universalTime: bigint;
}
/** Convert a WinRT struct value into a `DateTime` object. */
export declare function unpackDateTime(v: DynWinRtValue): DateTime;
export declare const DateTime_Type: DynWinRtType;
/** Convert a `DateTime` object into a WinRT struct value. */
export declare function packDateTime(v: DateTime): DynWinRtStruct;

export declare class BasicProperties {
    private constructor();
    get size(): bigint;
    get dateModified(): DateTime;
    get itemDate(): DateTime;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
}
