// Generated by dynwinrt-codegen — do not edit

export const CommonFileQuery = Object.freeze({
    DefaultQuery: 0,
    OrderByName: 1,
    OrderByTitle: 2,
    OrderByMusicProperties: 3,
    OrderBySearchRank: 4,
    OrderByDate: 5,
});
