// Generated by dynwinrt-codegen — do not edit

export const CommonFolderQuery = Object.freeze({
    DefaultQuery: 0,
    GroupByYear: 100,
    GroupByMonth: 101,
    GroupByArtist: 102,
    GroupByAlbum: 103,
    GroupByAlbumArtist: 104,
    GroupByComposer: 105,
    GroupByGenre: 106,
    GroupByPublishedYear: 107,
    GroupByRating: 108,
    GroupByTag: 109,
    GroupByAuthor: 110,
    GroupByType: 111,
});
