// Generated by dynwinrt-codegen — do not edit

export const CreationCollisionOption = Object.freeze({
    GenerateUniqueName: 0,
    ReplaceExisting: 1,
    FailIfExists: 2,
    OpenIfExists: 3,
});
