// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IIterable_IKeyValuePair_String_Object } from './IIterable_IKeyValuePair_String_Object.js';
import { IIterable_String } from './IIterable_String.js';
import { IKeyValuePair_String_Object } from './IKeyValuePair_String_Object.js';
import { IMap_String_Object } from './IMap_String_Object.js';
import { IVector_String } from './IVector_String.js';
import { IID_IStorageItemExtraProperties, IStorageItemExtraProperties } from './IStorageItemExtraProperties.js';

const IID_IDocumentProperties = WinGuid.parse('7eab19bc-1821-4923-b4a9-0aea404d0070');

const _IDocumentProperties = DynWinRtType.registerInterface(
    "IDocumentProperties", IID_IDocumentProperties)
    .addMethod("get_Author", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_Title", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Title", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Keywords", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_Comment", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Comment", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()));

export class DocumentProperties {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IDocumentProperties);
    }
    get author() {
        return new IVector_String(_IDocumentProperties.method(6).invoke(this._obj, []));
    }
    get title() {
        return _IDocumentProperties.method(7).invoke(this._obj, []).toString();
    }
    set title(value) {
        _IDocumentProperties.method(8).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }
    get keywords() {
        return new IVector_String(_IDocumentProperties.method(9).invoke(this._obj, []));
    }
    get comment() {
        return _IDocumentProperties.method(10).invoke(this._obj, []).toString();
    }
    set comment(value) {
        _IDocumentProperties.method(11).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}
