// Generated by dynwinrt-codegen — do not edit
import { IVector_String } from './IVector_String.js';

export declare class DocumentProperties {
    private constructor();
    get author(): IVector_String;
    get title(): string;
    set title(value: string);
    get keywords(): IVector_String;
    get comment(): string;
    set comment(value: string);
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
}
