// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { AppExecutionContext } from './AppExecutionContext.js';

export declare const IID_IAppInfo3: WinGuid;

export declare class IAppInfo3 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IAppInfo3;

    get executionContext(): AppExecutionContext;
}
