// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';

export declare const IID_IAppListEntry2: WinGuid;

export declare class IAppListEntry2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IAppListEntry2;

    get appUserModelId(): string;
}
