// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { User } from './User.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';
const _unwrap = (x) => x?._obj ?? x;

export const IID_IAppListEntry3 = WinGuid.parse('6099f28d-fc32-470a-bc69-4b061a76ef2e');

const _IAppListEntry3 = DynWinRtType.registerInterface(
    "IAppListEntry3", IID_IAppListEntry3)
    .addMethod("LaunchForUserAsync", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.boolType())));

export class IAppListEntry3 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IAppListEntry3(obj.cast(IID_IAppListEntry3));
    }

    async launchForUserAsync(user, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IAppListEntry3.method(6).invoke(this._obj, [_unwrap(user)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toBool();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
}
