// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { Package } from './Package.js';

export declare const IID_IAppInfo2: WinGuid;

export declare class IAppInfo2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IAppInfo2;

    get package_(): Package;
}
