// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { AppInfo } from './AppInfo.js';

export declare const IID_IAppListEntry4: WinGuid;

export declare class IAppListEntry4 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IAppListEntry4;

    get appInfo(): AppInfo;
}
