// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { User } from './User.js';

export declare const IID_IAppListEntry3: WinGuid;

export declare class IAppListEntry3 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IAppListEntry3;

    launchForUserAsync(user: User, signal?: AbortSignal): Promise<boolean>;
}
