// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';

export declare const IID_IContentTypeProvider: WinGuid;

export declare class IContentTypeProvider {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IContentTypeProvider;

    get contentType(): string;
}
