// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { IID_IInputStream, IInputStream } from './IInputStream.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';

export const IID_IInputStreamReference = WinGuid.parse('43929d18-5ec9-4b5a-919c-4205b0c804b6');

const _IInputStreamReference = DynWinRtType.registerInterface(
    "IInputStreamReference", IID_IInputStreamReference)
    .addMethod("OpenSequentialReadAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('905a0fe2-bc53-11df-8c49-001e4fc686da')))));

export class IInputStreamReference {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IInputStreamReference(obj.cast(IID_IInputStreamReference));
    }

    async openSequentialReadAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IInputStreamReference.method(6).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IInputStream(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
}
