// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';
const _unwrap = (x) => x?._obj ?? x;

export const IID_IIterator_Object = DynWinRtType.parameterized(WinGuid.parse('6a79e863-4300-459a-9966-cbb660963ee1'), [DynWinRtType.object()]).iid();

const _IIterator_Object = DynWinRtType.registerInterface(
    "IIterator_Object", IID_IIterator_Object)
    .addMethod("get_Current", new DynWinRtMethodSig().addOut(DynWinRtType.object()))
    .addMethod("get_HasCurrent", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("MoveNext", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("GetMany", new DynWinRtMethodSig().addOutFill(DynWinRtType.arrayType(DynWinRtType.object())).addOut(DynWinRtType.u32()));

export class IIterator_Object {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IIterator_Object);
    }

    static from(obj) {
        return new IIterator_Object(obj.cast(IID_IIterator_Object));
    }

    get current() {
        return _IIterator_Object.method(6).invoke(this._obj, []);
    }

    get hasCurrent() {
        return _IIterator_Object.method(7).invoke(this._obj, []).toBool();
    }

    moveNext() {
        return _IIterator_Object.method(8).invoke(this._obj, []).toBool();
    }

    getMany(items) {
        return _IIterator_Object.method(9).invoke(this._obj, [(Array.isArray(items) ? DynWinRtArray.fromObjectValues(items.map(_i => _unwrap(_i)), DynWinRtType.object()).toValue() : _unwrap(items))]).toNumber();
    }

    /** JS iterator protocol: returns the current element and advances. */
    next() {
        if (!this.hasCurrent) return { value: undefined, done: true };
        const value = this.current;
        this.moveNext();
        return { value, done: false };
    }

    [Symbol.iterator]() { return this; }
}
