// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { StorePackageUpdate } from './StorePackageUpdate.js';

export declare const IID_IIterator_StorePackageUpdate: WinGuid;

export declare class IIterator_StorePackageUpdate {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IIterator_StorePackageUpdate;

    get current(): StorePackageUpdate;

    get hasCurrent(): boolean;

    moveNext(): boolean;

    getMany(items: StorePackageUpdate[]): number;


    next(): IteratorResult<StorePackageUpdate>;


    [Symbol.iterator](): IterableIterator<StorePackageUpdate>;
}
