// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';

export declare const IID_IIterator_Object: WinGuid;

export declare class IIterator_Object {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IIterator_Object;

    get current(): unknown;

    get hasCurrent(): boolean;

    moveNext(): boolean;

    getMany(items: unknown[]): number;


    next(): IteratorResult<unknown>;


    [Symbol.iterator](): IterableIterator<unknown>;
}
