// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { IIterator_StorePackageUpdate } from './IIterator_StorePackageUpdate.js';
import { StorePackageUpdate } from './StorePackageUpdate.js';

export declare const IID_IIterable_StorePackageUpdate: WinGuid;

export declare class IIterable_StorePackageUpdate {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IIterable_StorePackageUpdate;

    first(): IIterator_StorePackageUpdate;


    [Symbol.iterator](): IterableIterator<StorePackageUpdate>;
}
