// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IIterator_StoreQueueItem } from './IIterator_StoreQueueItem.js';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';

export const IID_IIterable_StoreQueueItem = DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.runtimeClass('Windows.Services.Store.StoreQueueItem', WinGuid.parse('56d5c32b-f830-4293-9188-cad2dcde7357'))]).iid();

const _IIterable_StoreQueueItem = DynWinRtType.registerInterface(
    "IIterable_StoreQueueItem", IID_IIterable_StoreQueueItem)
    .addMethod("First", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('6a79e863-4300-459a-9966-cbb660963ee1'), [DynWinRtType.runtimeClass('Windows.Services.Store.StoreQueueItem', WinGuid.parse('56d5c32b-f830-4293-9188-cad2dcde7357'))])));

export class IIterable_StoreQueueItem {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IIterable_StoreQueueItem);
    }

    static from(obj) {
        return new IIterable_StoreQueueItem(obj.cast(IID_IIterable_StoreQueueItem));
    }

    first() {
        return new IIterator_StoreQueueItem(_IIterable_StoreQueueItem.method(6).invoke(this._obj, []));
    }

    [Symbol.iterator]() { return this.first(); }
}
