// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { StoreQueueItem } from './StoreQueueItem.js';

export declare const IID_IIterator_StoreQueueItem: WinGuid;

export declare class IIterator_StoreQueueItem {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IIterator_StoreQueueItem;

    get current(): StoreQueueItem;

    get hasCurrent(): boolean;

    moveNext(): boolean;

    getMany(items: StoreQueueItem[]): number;


    next(): IteratorResult<StoreQueueItem>;


    [Symbol.iterator](): IterableIterator<StoreQueueItem>;
}
