// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IIterable_IKeyValuePair_String_Object } from './IIterable_IKeyValuePair_String_Object.js';
import { IIterable_String } from './IIterable_String.js';
import { IKeyValuePair_String_Object } from './IKeyValuePair_String_Object.js';
import { IMap_String_Object } from './IMap_String_Object.js';
import { IReference_Double } from './IReference_Double.js';
import { IVectorView_String } from './IVectorView_String.js';
import { IVector_String } from './IVector_String.js';
import { PhotoOrientation } from './PhotoOrientation.js';
import { IID_IStorageItemExtraProperties, IStorageItemExtraProperties } from './IStorageItemExtraProperties.js';

const IID_IImageProperties = WinGuid.parse('523c9424-fcff-4275-afee-ecdb9ab47973');

const _IImageProperties = DynWinRtType.registerInterface(
    "IImageProperties", IID_IImageProperties)
    .addMethod("get_Rating", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("put_Rating", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("get_Keywords", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_DateTaken", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()])))
    .addMethod("put_DateTaken", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()])))
    .addMethod("get_Width", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_Height", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_Title", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Title", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Latitude", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('61c17706-2d65-11e0-9ae8-d48564015472'), [DynWinRtType.f64()])))
    .addMethod("get_Longitude", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('61c17706-2d65-11e0-9ae8-d48564015472'), [DynWinRtType.f64()])))
    .addMethod("get_CameraManufacturer", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_CameraManufacturer", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_CameraModel", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_CameraModel", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Orientation", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Storage.FileProperties.PhotoOrientation', ['Unspecified', 'Normal', 'FlipHorizontal', 'Rotate180', 'FlipVertical', 'Transpose', 'Rotate270', 'Transverse', 'Rotate90'], [0, 1, 2, 3, 4, 5, 6, 7, 8])))
    .addMethod("get_PeopleNames", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.hstring()])));

export function unpackDateTime(v) {
    const s = v.asStruct();
    return { universalTime: s.getI64(0) };
}
const _unpackDateTime = unpackDateTime;
export const DateTime_Type = DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()]);
const _DateTime_Type = DateTime_Type;
export function packDateTime(v) {
    const s = DynWinRtStruct.create(DateTime_Type);
    s.setI64(0, v.universalTime);
    return s;
}
const _packDateTime = packDateTime;

export class ImageProperties {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IImageProperties);
    }
    get rating() {
        return _IImageProperties.method(6).invoke(this._obj, []).toNumber();
    }
    set rating(value) {
        _IImageProperties.method(7).invoke(this._obj, [DynWinRtValue.u32(value)]);
    }
    get keywords() {
        return new IVector_String(_IImageProperties.method(8).invoke(this._obj, []));
    }
    get dateTaken() {
        return _unpackDateTime(_IImageProperties.method(9).invoke(this._obj, []));
    }
    set dateTaken(value) {
        _IImageProperties.method(10).invoke(this._obj, [_packDateTime(value).toValue()]);
    }
    get width() {
        return _IImageProperties.method(11).invoke(this._obj, []).toNumber();
    }
    get height() {
        return _IImageProperties.method(12).invoke(this._obj, []).toNumber();
    }
    get title() {
        return _IImageProperties.method(13).invoke(this._obj, []).toString();
    }
    set title(value) {
        _IImageProperties.method(14).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }
    get latitude() {
        return new IReference_Double(_IImageProperties.method(15).invoke(this._obj, []));
    }
    get longitude() {
        return new IReference_Double(_IImageProperties.method(16).invoke(this._obj, []));
    }
    get cameraManufacturer() {
        return _IImageProperties.method(17).invoke(this._obj, []).toString();
    }
    set cameraManufacturer(value) {
        _IImageProperties.method(18).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }
    get cameraModel() {
        return _IImageProperties.method(19).invoke(this._obj, []).toString();
    }
    set cameraModel(value) {
        _IImageProperties.method(20).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }
    get orientation() {
        return _IImageProperties.method(21).invoke(this._obj, []).toNumber();
    }
    get peopleNames() {
        return new IVectorView_String(_IImageProperties.method(22).invoke(this._obj, []));
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}
