// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IMapView_String_Object } from './IMapView_String_Object.js';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';
const _unwrap = (x) => x?._obj ?? x;

export const IID_IMap_String_Object = DynWinRtType.parameterized(WinGuid.parse('3c2925fe-8519-45c1-aa79-197b6718c1c1'), [DynWinRtType.hstring(), DynWinRtType.object()]).iid();

const _IMap_String_Object = DynWinRtType.registerInterface(
    "IMap_String_Object", IID_IMap_String_Object)
    .addMethod("Lookup", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.object()))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("HasKey", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.boolType()))
    .addMethod("GetView", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('e480ce40-a338-4ada-adcf-272272e48cb9'), [DynWinRtType.hstring(), DynWinRtType.object()])))
    .addMethod("Insert", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.object()).addOut(DynWinRtType.boolType()))
    .addMethod("Remove", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("Clear", new DynWinRtMethodSig());

export class IMap_String_Object {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IMap_String_Object);
    }

    static from(obj) {
        return new IMap_String_Object(obj.cast(IID_IMap_String_Object));
    }

    lookup(key) {
        return _IMap_String_Object.method(6).invoke(this._obj, [DynWinRtValue.hstring(key)]);
    }

    get size() {
        return _IMap_String_Object.method(7).invoke(this._obj, []).toNumber();
    }

    hasKey(key) {
        return _IMap_String_Object.method(8).invoke(this._obj, [DynWinRtValue.hstring(key)]).toBool();
    }

    getView() {
        return new IMapView_String_Object(_IMap_String_Object.method(9).invoke(this._obj, []));
    }

    insert(key, value) {
        return _IMap_String_Object.method(10).invoke(this._obj, [DynWinRtValue.hstring(key), _unwrap(value)]).toBool();
    }

    remove(key) {
        _IMap_String_Object.method(11).invoke(this._obj, [DynWinRtValue.hstring(key)]);
    }

    clear() {
        _IMap_String_Object.method(12).invoke(this._obj, []);
    }

    /**
     * Get the value for `key`. Alias for `lookup()`.
     */
    get(key) {
        return (() => { try { return _IMap_String_Object.method(6).invoke(this._obj, [DynWinRtValue.hstring(key)]); } catch { return undefined; } })();
    }

    /**
     * Check if the map contains `key`. Alias for `hasKey()`.
     */
    has(key) {
        return _IMap_String_Object.method(8).invoke(this._obj, [DynWinRtValue.hstring(key)]).toBool();
    }

    /**
     * Set a key-value pair. Alias for `insert()`.
     */
    set(key, value) {
        _IMap_String_Object.method(10).invoke(this._obj, [DynWinRtValue.hstring(key), _unwrap(value)]);
    }

    /**
     * Remove entry by key. Alias for `remove()`.
     */
    delete(key) {
        _IMap_String_Object.method(11).invoke(this._obj, [DynWinRtValue.hstring(key)]);
    }

    /** Number of entries. Alias for `size`. */
    get length() { return this.size; }

    /**
     * Create a new IMap from parallel arrays of keys and values.
     */
    static create(keys, values) {
        return new IMap_String_Object(DynWinRtValue.createMap(keys.map(k => _unwrap(k)), values.map(v => _unwrap(v)), DynWinRtType.hstring(), DynWinRtType.object()));
    }
}
