// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { StoreLicense } from './StoreLicense.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';

export const IID_IMapView_String_StoreLicense = DynWinRtType.parameterized(WinGuid.parse('e480ce40-a338-4ada-adcf-272272e48cb9'), [DynWinRtType.hstring(), DynWinRtType.runtimeClass('Windows.Services.Store.StoreLicense', WinGuid.parse('26dc9579-4c4f-4f30-bc89-649f60e36055'))]).iid();

const _IMapView_String_StoreLicense = DynWinRtType.registerInterface(
    "IMapView_String_StoreLicense", IID_IMapView_String_StoreLicense)
    .addMethod("Lookup", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.runtimeClass('Windows.Services.Store.StoreLicense', WinGuid.parse('26dc9579-4c4f-4f30-bc89-649f60e36055'))))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("HasKey", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.boolType()))
    .addMethod("Split", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('e480ce40-a338-4ada-adcf-272272e48cb9'), [DynWinRtType.hstring(), DynWinRtType.runtimeClass('Windows.Services.Store.StoreLicense', WinGuid.parse('26dc9579-4c4f-4f30-bc89-649f60e36055'))])).addOut(DynWinRtType.parameterized(WinGuid.parse('e480ce40-a338-4ada-adcf-272272e48cb9'), [DynWinRtType.hstring(), DynWinRtType.runtimeClass('Windows.Services.Store.StoreLicense', WinGuid.parse('26dc9579-4c4f-4f30-bc89-649f60e36055'))])));

export class IMapView_String_StoreLicense {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IMapView_String_StoreLicense);
    }

    static from(obj) {
        return new IMapView_String_StoreLicense(obj.cast(IID_IMapView_String_StoreLicense));
    }

    lookup(key) {
        return new StoreLicense(_IMapView_String_StoreLicense.method(6).invoke(this._obj, [DynWinRtValue.hstring(key)]));
    }

    get size() {
        return _IMapView_String_StoreLicense.method(7).invoke(this._obj, []).toNumber();
    }

    hasKey(key) {
        return _IMapView_String_StoreLicense.method(8).invoke(this._obj, [DynWinRtValue.hstring(key)]).toBool();
    }

    /**
     * Get the value for `key`. Alias for `lookup()`.
     */
    get(key) {
        return (() => { try { return new StoreLicense(_IMapView_String_StoreLicense.method(6).invoke(this._obj, [DynWinRtValue.hstring(key)])); } catch { return undefined; } })();
    }

    /**
     * Check if the map contains `key`. Alias for `hasKey()`.
     */
    has(key) {
        return _IMapView_String_StoreLicense.method(8).invoke(this._obj, [DynWinRtValue.hstring(key)]).toBool();
    }

    /** Number of entries. Alias for `size`. */
    get length() { return this.size; }
}
