// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { StoreLicense } from './StoreLicense.js';

export declare const IID_IMapView_String_StoreLicense: WinGuid;

export declare class IMapView_String_StoreLicense {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IMapView_String_StoreLicense;

    lookup(key: string): StoreLicense;

    get size(): number;

    hasKey(key: string): boolean;

    /**
     * Get the value for `key`. Alias for `lookup()`.
     */
    get(key: string): StoreLicense | undefined;

    /**
     * Check if the map contains `key`. Alias for `hasKey()`.
     */
    has(key: string): boolean;


    get length(): number;
}
