// Generated by dynwinrt-codegen — do not edit

export const IndexerOption = Object.freeze({
    UseIndexerWhenAvailable: 0,
    OnlyUseIndexer: 1,
    DoNotUseIndexer: 2,
    OnlyUseIndexerAndOptimizeForIndexedProperties: 3,
});
