// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtValue, DynWinRtStruct, WinGuid } from '@microsoft/dynwinrt';
import { IVectorView_AppListEntry } from './IVectorView_AppListEntry.js';
import { StorageFolder } from './StorageFolder.js';
import { RandomAccessStreamReference } from './RandomAccessStreamReference.js';

export interface Size {
    width: number;
    height: number;
}
/** Convert a WinRT struct value into a `Size` object. */
export declare function unpackSize(v: DynWinRtValue): Size;
export declare const Size_Type: DynWinRtType;
/** Convert a `Size` object into a WinRT struct value. */
export declare function packSize(v: Size): DynWinRtStruct;

export declare const IID_IPackage8: WinGuid;

export declare class IPackage8 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IPackage8;

    get effectiveExternalLocation(): StorageFolder;

    get machineExternalLocation(): StorageFolder;

    get userExternalLocation(): StorageFolder;

    get installedPath(): string;

    get mutablePath(): string;

    get effectivePath(): string;

    get effectiveExternalPath(): string;

    get machineExternalPath(): string;

    get userExternalPath(): string;

    getLogoAsRandomAccessStreamReference(size: Size): RandomAccessStreamReference;

    getAppListEntries(): IVectorView_AppListEntry;

    get isStub(): boolean;
}
