// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { IIterable_String } from './IIterable_String.js';
import { IVector_PackageContentGroup } from './IVector_PackageContentGroup.js';
import { PackageContentGroup } from './PackageContentGroup.js';

export declare const IID_IPackage5: WinGuid;

export declare class IPackage5 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IPackage5;

    getContentGroupsAsync(signal?: AbortSignal): Promise<IVector_PackageContentGroup>;

    getContentGroupAsync(name: string, signal?: AbortSignal): Promise<PackageContentGroup>;

    stageContentGroupsAsync(names: IIterable_String | string[], signal?: AbortSignal): Promise<IVector_PackageContentGroup>;

    stageContentGroupsWithPriorityAsync(names: IIterable_String | string[], moveToHeadOfQueue: boolean, signal?: AbortSignal): Promise<IVector_PackageContentGroup>;

    setInUseAsync(inUse: boolean, signal?: AbortSignal): Promise<boolean>;
}
