// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtValue, DynWinRtStruct, WinGuid } from '@microsoft/dynwinrt';

export interface DateTime {
    universalTime: bigint;
}
/** Convert a WinRT struct value into a `DateTime` object. */
export declare function unpackDateTime(v: DynWinRtValue): DateTime;
export declare const DateTime_Type: DynWinRtType;
/** Convert a `DateTime` object into a WinRT struct value. */
export declare function packDateTime(v: DateTime): DynWinRtStruct;

export declare const IID_IPackageWithMetadata: WinGuid;

export declare class IPackageWithMetadata {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IPackageWithMetadata;

    get installDate(): DateTime;

    getThumbnailToken(): string;

    launch(parameters: string): void;
}
