// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';

export declare const IID_IPackageIdWithMetadata: WinGuid;

export declare class IPackageIdWithMetadata {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IPackageIdWithMetadata;

    get productId(): string;

    get author(): string;
}
