// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { AppInstallerInfo } from './AppInstallerInfo.js';
import { PackageUpdateAvailabilityResult } from './PackageUpdateAvailabilityResult.js';

export declare const IID_IPackage6: WinGuid;

export declare class IPackage6 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IPackage6;

    getAppInstallerInfo(): AppInstallerInfo;

    checkUpdateAvailabilityAsync(signal?: AbortSignal): Promise<PackageUpdateAvailabilityResult>;
}
