// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IVectorView_AppListEntry } from './IVectorView_AppListEntry.js';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { AppListEntry } from './AppListEntry.js';
import { StorageFolder } from './StorageFolder.js';
import { RandomAccessStreamReference } from './RandomAccessStreamReference.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';

export const IID_IPackage8 = WinGuid.parse('2c584f7b-ce2a-4be6-a093-77cfbb2a7ea1');

const _IPackage8 = DynWinRtType.registerInterface(
    "IPackage8", IID_IPackage8)
    .addMethod("get_EffectiveExternalLocation", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))))
    .addMethod("get_MachineExternalLocation", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))))
    .addMethod("get_UserExternalLocation", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))))
    .addMethod("get_InstalledPath", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_MutablePath", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_EffectivePath", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_EffectiveExternalPath", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_MachineExternalPath", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_UserExternalPath", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("GetLogoAsRandomAccessStreamReference", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.Size', [DynWinRtType.f32(), DynWinRtType.f32()])).addOut(DynWinRtType.runtimeClass('Windows.Storage.Streams.RandomAccessStreamReference', WinGuid.parse('33ee3134-1dd6-4e3a-8067-d1c162e8642b'))))
    .addMethod("GetAppListEntries", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.ApplicationModel.Core.AppListEntry', WinGuid.parse('ef00f07f-2108-490a-877a-8a9f17c25fad'))])))
    .addMethod("get_IsStub", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()));

export function unpackSize(v) {
    const s = v.asStruct();
    return { width: s.getF32(0), height: s.getF32(1) };
}
const _unpackSize = unpackSize;
export const Size_Type = DynWinRtType.structType('Windows.Foundation.Size', [DynWinRtType.f32(), DynWinRtType.f32()]);
const _Size_Type = Size_Type;
export function packSize(v) {
    const s = DynWinRtStruct.create(Size_Type);
    s.setF32(0, v.width);
    s.setF32(1, v.height);
    return s;
}
const _packSize = packSize;

export class IPackage8 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IPackage8(obj.cast(IID_IPackage8));
    }

    get effectiveExternalLocation() {
        return new StorageFolder(_IPackage8.method(6).invoke(this._obj, []));
    }

    get machineExternalLocation() {
        return new StorageFolder(_IPackage8.method(7).invoke(this._obj, []));
    }

    get userExternalLocation() {
        return new StorageFolder(_IPackage8.method(8).invoke(this._obj, []));
    }

    get installedPath() {
        return _IPackage8.method(9).invoke(this._obj, []).toString();
    }

    get mutablePath() {
        return _IPackage8.method(10).invoke(this._obj, []).toString();
    }

    get effectivePath() {
        return _IPackage8.method(11).invoke(this._obj, []).toString();
    }

    get effectiveExternalPath() {
        return _IPackage8.method(12).invoke(this._obj, []).toString();
    }

    get machineExternalPath() {
        return _IPackage8.method(13).invoke(this._obj, []).toString();
    }

    get userExternalPath() {
        return _IPackage8.method(14).invoke(this._obj, []).toString();
    }

    getLogoAsRandomAccessStreamReference(size) {
        return new RandomAccessStreamReference(_IPackage8.method(15).invoke(this._obj, [_packSize(size).toValue()]));
    }

    getAppListEntries() {
        return new IVectorView_AppListEntry(_IPackage8.method(16).invoke(this._obj, []));
    }

    get isStub() {
        return _IPackage8.method(17).invoke(this._obj, []).toBool();
    }
}
