// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { PackageSignatureKind } from './PackageSignatureKind.js';

export declare const IID_IPackage4: WinGuid;

export declare class IPackage4 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IPackage4;

    get signatureKind(): PackageSignatureKind;

    get isOptional(): boolean;

    verifyContentIntegrityAsync(signal?: AbortSignal): Promise<boolean>;
}
