// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';

export const IID_IQueryOptionsAdditionalSearchSources = WinGuid.parse('8d342d6b-8800-426e-b5cf-4b328f824e7e');

const _IQueryOptionsAdditionalSearchSources = DynWinRtType.registerInterface(
    "IQueryOptionsAdditionalSearchSources", IID_IQueryOptionsAdditionalSearchSources)
    .addMethod("get_IncludeLocalSemanticIndex", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("put_IncludeLocalSemanticIndex", new DynWinRtMethodSig().addIn(DynWinRtType.boolType()))
    .addMethod("get_IncludeCloudProviders", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("put_IncludeCloudProviders", new DynWinRtMethodSig().addIn(DynWinRtType.boolType()));

export class IQueryOptionsAdditionalSearchSources {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IQueryOptionsAdditionalSearchSources(obj.cast(IID_IQueryOptionsAdditionalSearchSources));
    }

    get includeLocalSemanticIndex() {
        return _IQueryOptionsAdditionalSearchSources.method(6).invoke(this._obj, []).toBool();
    }
    set includeLocalSemanticIndex(value) {
        _IQueryOptionsAdditionalSearchSources.method(7).invoke(this._obj, [DynWinRtValue.boolValue(value)]);
    }

    get includeCloudProviders() {
        return _IQueryOptionsAdditionalSearchSources.method(8).invoke(this._obj, []).toBool();
    }
    set includeCloudProviders(value) {
        _IQueryOptionsAdditionalSearchSources.method(9).invoke(this._obj, [DynWinRtValue.boolValue(value)]);
    }
}
