// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';

export declare const IID_IRandomAccessStreamWithContentType: WinGuid;

export declare class IRandomAccessStreamWithContentType {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IRandomAccessStreamWithContentType;
}
