// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { FileAttributes } from './FileAttributes.js';
import { NameCollisionOption } from './NameCollisionOption.js';
import { StorageDeleteOption } from './StorageDeleteOption.js';
import { StorageItemTypes } from './StorageItemTypes.js';
import { BasicProperties } from './BasicProperties.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';

export const IID_IStorageItem = WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30');

const _IStorageItem = DynWinRtType.registerInterface(
    "IStorageItem", IID_IStorageItem)
    .addMethod("RenameAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncAction()))
    .addMethod("RenameAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.enumType('Windows.Storage.NameCollisionOption', ['GenerateUniqueName', 'ReplaceExisting', 'FailIfExists'], [0, 1, 2])).addOut(DynWinRtType.iAsyncAction()))
    .addMethod("DeleteAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncAction()))
    .addMethod("DeleteAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.StorageDeleteOption', ['Default', 'PermanentDelete'], [0, 1])).addOut(DynWinRtType.iAsyncAction()))
    .addMethod("GetBasicPropertiesAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.BasicProperties', WinGuid.parse('d05d55db-785e-4a66-be02-9beec58aea81')))))
    .addMethod("get_Name", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Path", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Attributes", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Storage.FileAttributes', ['Normal', 'ReadOnly', 'Directory', 'Archive', 'Temporary', 'LocallyIncomplete'], [0, 1, 16, 32, 256, 512])))
    .addMethod("get_DateCreated", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()])))
    .addMethod("IsOfType", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.StorageItemTypes', ['None', 'File', 'Folder'], [0, 1, 2])).addOut(DynWinRtType.boolType()));

export function unpackDateTime(v) {
    const s = v.asStruct();
    return { universalTime: s.getI64(0) };
}
const _unpackDateTime = unpackDateTime;
export const DateTime_Type = DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()]);
const _DateTime_Type = DateTime_Type;
export function packDateTime(v) {
    const s = DynWinRtStruct.create(DateTime_Type);
    s.setI64(0, v.universalTime);
    return s;
}
const _packDateTime = packDateTime;

export class IStorageItem {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageItem(obj.cast(IID_IStorageItem));
    }

    /**
     * Overload of `renameAsync` with default options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async renameAsyncOverloadDefaultOptions(desiredName, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItem.method(6).invoke(this._obj, [DynWinRtValue.hstring(desiredName)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    async renameAsync(desiredName, option, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItem.method(7).invoke(this._obj, [DynWinRtValue.hstring(desiredName), DynWinRtValue.i32(option)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    /**
     * Overload of `deleteAsync` with default options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async deleteAsyncOverloadDefaultOptions(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItem.method(8).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    async deleteAsync(option, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItem.method(9).invoke(this._obj, [DynWinRtValue.i32(option)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    async getBasicPropertiesAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItem.method(10).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new BasicProperties(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    get name() {
        return _IStorageItem.method(11).invoke(this._obj, []).toString();
    }

    get path() {
        return _IStorageItem.method(12).invoke(this._obj, []).toString();
    }

    get attributes() {
        return _IStorageItem.method(13).invoke(this._obj, []).toNumber();
    }

    get dateCreated() {
        return _unpackDateTime(_IStorageItem.method(14).invoke(this._obj, []));
    }

    isOfType(type) {
        return _IStorageItem.method(15).invoke(this._obj, [DynWinRtValue.i32(type)]).toBool();
    }
}
