// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { IIterable_String } from './IIterable_String.js';
import { StoreProductQueryResult } from './StoreProductQueryResult.js';
import { StorePurchaseResult } from './StorePurchaseResult.js';

export declare const IID_IStoreContext5: WinGuid;

export declare class IStoreContext5 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStoreContext5;

    getUserPurchaseHistoryAsync(productKinds: IIterable_String | string[], signal?: AbortSignal): Promise<StoreProductQueryResult>;

    getAssociatedStoreProductsByInAppOfferTokenAsync(inAppOfferTokens: IIterable_String | string[], signal?: AbortSignal): Promise<StoreProductQueryResult>;

    requestPurchaseByInAppOfferTokenAsync(inAppOfferToken: string, signal?: AbortSignal): Promise<StorePurchaseResult>;
}
