// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { FileAccessMode } from './FileAccessMode.js';
import { IID_IStorageFolder, IStorageFolder } from './IStorageFolder.js';
import { NameCollisionOption } from './NameCollisionOption.js';
import { StorageFile } from './StorageFile.js';
import { StorageStreamTransaction } from './StorageStreamTransaction.js';
import { IID_IRandomAccessStream, IRandomAccessStream } from './IRandomAccessStream.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';
const _unwrap = (x) => x?._obj ?? x;

export const IID_IStorageFile = WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea');

const _IStorageFile = DynWinRtType.registerInterface(
    "IStorageFile", IID_IStorageFile)
    .addMethod("get_FileType", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_ContentType", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("OpenAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileAccessMode', ['Read', 'ReadWrite'], [0, 1])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('905a0fe1-bc53-11df-8c49-001e4fc686da')))))
    .addMethod("OpenTransactedWriteAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageStreamTransaction', WinGuid.parse('f67cf363-a53d-4d94-ae2c-67232d93acdd')))))
    .addMethod("CopyOverloadDefaultNameAndOptions", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
    .addMethod("CopyOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
    .addMethod("CopyOverload", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addIn(DynWinRtType.hstring()).addIn(DynWinRtType.enumType('Windows.Storage.NameCollisionOption', ['GenerateUniqueName', 'ReplaceExisting', 'FailIfExists'], [0, 1, 2])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
    .addMethod("CopyAndReplaceAsync", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))).addOut(DynWinRtType.iAsyncAction()))
    .addMethod("MoveOverloadDefaultNameAndOptions", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addOut(DynWinRtType.iAsyncAction()))
    .addMethod("MoveOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncAction()))
    .addMethod("MoveOverload", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))).addIn(DynWinRtType.hstring()).addIn(DynWinRtType.enumType('Windows.Storage.NameCollisionOption', ['GenerateUniqueName', 'ReplaceExisting', 'FailIfExists'], [0, 1, 2])).addOut(DynWinRtType.iAsyncAction()))
    .addMethod("MoveAndReplaceAsync", new DynWinRtMethodSig().addIn(DynWinRtType.interface(WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))).addOut(DynWinRtType.iAsyncAction()));

export class IStorageFile {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageFile(obj.cast(IID_IStorageFile));
    }

    get fileType() {
        return _IStorageFile.method(6).invoke(this._obj, []).toString();
    }

    get contentType() {
        return _IStorageFile.method(7).invoke(this._obj, []).toString();
    }

    async openAsync(accessMode, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(8).invoke(this._obj, [DynWinRtValue.i32(accessMode)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IRandomAccessStream(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    async openTransactedWriteAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(9).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorageStreamTransaction(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    /**
     * Overload of `copy` with default name, options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async copyOverloadDefaultNameAndOptions(destinationFolder, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(10).invoke(this._obj, [_unwrap(destinationFolder)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorageFile(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    /**
     * Overload of `copy` with default options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async copyOverloadDefaultOptions(destinationFolder, desiredNewName, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(11).invoke(this._obj, [_unwrap(destinationFolder), DynWinRtValue.hstring(desiredNewName)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorageFile(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    /**
     * Parameterless overload of `copy`.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async copyOverload(destinationFolder, desiredNewName, option, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(12).invoke(this._obj, [_unwrap(destinationFolder), DynWinRtValue.hstring(desiredNewName), DynWinRtValue.i32(option)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorageFile(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    async copyAndReplaceAsync(fileToReplace, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(13).invoke(this._obj, [_unwrap(fileToReplace)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    /**
     * Overload of `move` with default name, options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async moveOverloadDefaultNameAndOptions(destinationFolder, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(14).invoke(this._obj, [_unwrap(destinationFolder)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    /**
     * Overload of `move` with default options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async moveOverloadDefaultOptions(destinationFolder, desiredNewName, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(15).invoke(this._obj, [_unwrap(destinationFolder), DynWinRtValue.hstring(desiredNewName)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    /**
     * Parameterless overload of `move`.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async moveOverload(destinationFolder, desiredNewName, option, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(16).invoke(this._obj, [_unwrap(destinationFolder), DynWinRtValue.hstring(desiredNewName), DynWinRtValue.i32(option)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    async moveAndReplaceAsync(fileToReplace, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile.method(17).invoke(this._obj, [_unwrap(fileToReplace)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
}
