// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IIterable_StoreQueueItem } from './IIterable_StoreQueueItem.js';
import { IVectorView_StoreQueueItem } from './IVectorView_StoreQueueItem.js';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreRateAndReviewResult } from './StoreRateAndReviewResult.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';
const _unwrap = (x) => x?._obj ?? x;

export const IID_IStoreContext4 = WinGuid.parse('af9c6f69-bea1-4bf4-8e74-ae03e206c6b0');

const _IStoreContext4 = DynWinRtType.registerInterface(
    "IStoreContext4", IID_IStoreContext4)
    .addMethod("RequestRateAndReviewAppAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Services.Store.StoreRateAndReviewResult', WinGuid.parse('9d209d56-a6b5-4121-9b61-ee6d0fbdbdbb')))))
    .addMethod("SetInstallOrderForAssociatedStoreQueueItemsAsync", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.runtimeClass('Windows.Services.Store.StoreQueueItem', WinGuid.parse('56d5c32b-f830-4293-9188-cad2dcde7357'))])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Services.Store.StoreQueueItem', WinGuid.parse('56d5c32b-f830-4293-9188-cad2dcde7357'))]))));

export class IStoreContext4 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStoreContext4(obj.cast(IID_IStoreContext4));
    }

    async requestRateAndReviewAppAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStoreContext4.method(6).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StoreRateAndReviewResult(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    async setInstallOrderForAssociatedStoreQueueItemsAsync(items, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStoreContext4.method(7).invoke(this._obj, [(Array.isArray(items) ? DynWinRtValue.createVector(items.map(_i => _unwrap(_i)), DynWinRtType.runtimeClass('Windows.Services.Store.StoreQueueItem', WinGuid.parse('56d5c32b-f830-4293-9188-cad2dcde7357'))).cast(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.runtimeClass('Windows.Services.Store.StoreQueueItem', WinGuid.parse('56d5c32b-f830-4293-9188-cad2dcde7357'))]).iid()) : _unwrap(items).cast(DynWinRtType.parameterized(WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3'), [DynWinRtType.runtimeClass('Windows.Services.Store.StoreQueueItem', WinGuid.parse('56d5c32b-f830-4293-9188-cad2dcde7357'))]).iid()))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_StoreQueueItem(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
}
