// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';

export const IID_IStoreAppLicense2 = WinGuid.parse('b4666e91-4443-40b3-993f-28904435bdc6');

const _IStoreAppLicense2 = DynWinRtType.registerInterface(
    "IStoreAppLicense2", IID_IStoreAppLicense2)
    .addMethod("get_IsDiscLicense", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()));

export class IStoreAppLicense2 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStoreAppLicense2(obj.cast(IID_IStoreAppLicense2));
    }

    get isDiscLicense() {
        return _IStoreAppLicense2.method(6).invoke(this._obj, []).toBool();
    }
}
