// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { StorageLibraryChangeTracker } from './StorageLibraryChangeTracker.js';

export declare const IID_IStorageFolder3: WinGuid;

export declare class IStorageFolder3 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStorageFolder3;

    tryGetChangeTracker(): StorageLibraryChangeTracker;
}
