// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { IVectorView_StoreQueueItem } from './IVectorView_StoreQueueItem.js';

export declare const IID_IStorePackageUpdateResult2: WinGuid;

export declare class IStorePackageUpdateResult2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStorePackageUpdateResult2;

    get storeQueueItems(): IVectorView_StoreQueueItem;
}
