// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IVectorView_IStorageItem } from './IVectorView_IStorageItem.js';
import { IVectorView_StorageFile } from './IVectorView_StorageFile.js';
import { IVectorView_StorageFolder } from './IVectorView_StorageFolder.js';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { IID_IStorageItem, IStorageItem } from './IStorageItem.js';
import { StorageFile } from './StorageFile.js';
import { StorageFolder } from './StorageFolder.js';
import { CommonFileQuery } from './CommonFileQuery.js';
import { CommonFolderQuery } from './CommonFolderQuery.js';
import { IndexedState } from './IndexedState.js';
import { QueryOptions } from './QueryOptions.js';
import { StorageFileQueryResult } from './StorageFileQueryResult.js';
import { StorageFolderQueryResult } from './StorageFolderQueryResult.js';
import { StorageItemQueryResult } from './StorageItemQueryResult.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';
const _unwrap = (x) => x?._obj ?? x;

export const IID_IStorageFolderQueryOperations = WinGuid.parse('cb43ccc9-446b-4a4f-be97-757771be5203');

const _IStorageFolderQueryOperations = DynWinRtType.registerInterface(
    "IStorageFolderQueryOperations", IID_IStorageFolderQueryOperations)
    .addMethod("GetIndexedStateAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.enumType('Windows.Storage.Search.IndexedState', ['Unknown', 'NotIndexed', 'PartiallyIndexed', 'FullyIndexed'], [0, 1, 2, 3]))))
    .addMethod("CreateFileQueryOverloadDefault", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFileQueryResult', WinGuid.parse('52fda447-2baa-412c-b29f-d4b1778efa1e'))))
    .addMethod("CreateFileQuery", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFileQuery', ['DefaultQuery', 'OrderByName', 'OrderByTitle', 'OrderByMusicProperties', 'OrderBySearchRank', 'OrderByDate'], [0, 1, 2, 3, 4, 5])).addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFileQueryResult', WinGuid.parse('52fda447-2baa-412c-b29f-d4b1778efa1e'))))
    .addMethod("CreateFileQueryWithOptions", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))).addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFileQueryResult', WinGuid.parse('52fda447-2baa-412c-b29f-d4b1778efa1e'))))
    .addMethod("CreateFolderQueryOverloadDefault", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFolderQueryResult', WinGuid.parse('6654c911-7d66-46fa-aecf-e4a4baa93ab8'))))
    .addMethod("CreateFolderQuery", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFolderQuery', ['DefaultQuery', 'GroupByYear', 'GroupByMonth', 'GroupByArtist', 'GroupByAlbum', 'GroupByAlbumArtist', 'GroupByComposer', 'GroupByGenre', 'GroupByPublishedYear', 'GroupByRating', 'GroupByTag', 'GroupByAuthor', 'GroupByType'], [0, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])).addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFolderQueryResult', WinGuid.parse('6654c911-7d66-46fa-aecf-e4a4baa93ab8'))))
    .addMethod("CreateFolderQueryWithOptions", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))).addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFolderQueryResult', WinGuid.parse('6654c911-7d66-46fa-aecf-e4a4baa93ab8'))))
    .addMethod("CreateItemQuery", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageItemQueryResult', WinGuid.parse('e8948079-9d58-47b8-b2b2-41b07f4795f9'))))
    .addMethod("CreateItemQueryWithOptions", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))).addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageItemQueryResult', WinGuid.parse('e8948079-9d58-47b8-b2b2-41b07f4795f9'))))
    .addMethod("GetFilesAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFileQuery', ['DefaultQuery', 'OrderByName', 'OrderByTitle', 'OrderByMusicProperties', 'OrderBySearchRank', 'OrderByDate'], [0, 1, 2, 3, 4, 5])).addIn(DynWinRtType.u32()).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))]))))
    .addMethod("GetFilesAsyncOverloadDefaultStartAndCount", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFileQuery', ['DefaultQuery', 'OrderByName', 'OrderByTitle', 'OrderByMusicProperties', 'OrderBySearchRank', 'OrderByDate'], [0, 1, 2, 3, 4, 5])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))]))))
    .addMethod("GetFoldersAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFolderQuery', ['DefaultQuery', 'GroupByYear', 'GroupByMonth', 'GroupByArtist', 'GroupByAlbum', 'GroupByAlbumArtist', 'GroupByComposer', 'GroupByGenre', 'GroupByPublishedYear', 'GroupByRating', 'GroupByTag', 'GroupByAuthor', 'GroupByType'], [0, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])).addIn(DynWinRtType.u32()).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))]))))
    .addMethod("GetFoldersAsyncOverloadDefaultStartAndCount", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFolderQuery', ['DefaultQuery', 'GroupByYear', 'GroupByMonth', 'GroupByArtist', 'GroupByAlbum', 'GroupByAlbumArtist', 'GroupByComposer', 'GroupByGenre', 'GroupByPublishedYear', 'GroupByRating', 'GroupByTag', 'GroupByAuthor', 'GroupByType'], [0, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))]))))
    .addMethod("GetItemsAsync", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30'))]))))
    .addMethod("AreQueryOptionsSupported", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))).addOut(DynWinRtType.boolType()))
    .addMethod("IsCommonFolderQuerySupported", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFolderQuery', ['DefaultQuery', 'GroupByYear', 'GroupByMonth', 'GroupByArtist', 'GroupByAlbum', 'GroupByAlbumArtist', 'GroupByComposer', 'GroupByGenre', 'GroupByPublishedYear', 'GroupByRating', 'GroupByTag', 'GroupByAuthor', 'GroupByType'], [0, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])).addOut(DynWinRtType.boolType()))
    .addMethod("IsCommonFileQuerySupported", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFileQuery', ['DefaultQuery', 'OrderByName', 'OrderByTitle', 'OrderByMusicProperties', 'OrderBySearchRank', 'OrderByDate'], [0, 1, 2, 3, 4, 5])).addOut(DynWinRtType.boolType()));

export class IStorageFolderQueryOperations {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageFolderQueryOperations(obj.cast(IID_IStorageFolderQueryOperations));
    }

    async getIndexedStateAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(6).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toNumber();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    /**
     * Parameterless overload of `createFileQuery`.
     */
    createFileQueryOverloadDefault() {
        return new StorageFileQueryResult(_IStorageFolderQueryOperations.method(7).invoke(this._obj, []));
    }

    createFileQuery(query) {
        return new StorageFileQueryResult(_IStorageFolderQueryOperations.method(8).invoke(this._obj, [DynWinRtValue.i32(query)]));
    }

    createFileQueryWithOptions(queryOptions) {
        return new StorageFileQueryResult(_IStorageFolderQueryOperations.method(9).invoke(this._obj, [_unwrap(queryOptions)]));
    }

    /**
     * Parameterless overload of `createFolderQuery`.
     */
    createFolderQueryOverloadDefault() {
        return new StorageFolderQueryResult(_IStorageFolderQueryOperations.method(10).invoke(this._obj, []));
    }

    createFolderQuery(query) {
        return new StorageFolderQueryResult(_IStorageFolderQueryOperations.method(11).invoke(this._obj, [DynWinRtValue.i32(query)]));
    }

    createFolderQueryWithOptions(queryOptions) {
        return new StorageFolderQueryResult(_IStorageFolderQueryOperations.method(12).invoke(this._obj, [_unwrap(queryOptions)]));
    }

    createItemQuery() {
        return new StorageItemQueryResult(_IStorageFolderQueryOperations.method(13).invoke(this._obj, []));
    }

    createItemQueryWithOptions(queryOptions) {
        return new StorageItemQueryResult(_IStorageFolderQueryOperations.method(14).invoke(this._obj, [_unwrap(queryOptions)]));
    }

    async getFilesAsync(query, startIndex, maxItemsToRetrieve, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(15).invoke(this._obj, [DynWinRtValue.i32(query), DynWinRtValue.u32(startIndex), DynWinRtValue.u32(maxItemsToRetrieve)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_StorageFile(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    /**
     * Overload of `getFilesAsync` with default start, count.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async getFilesAsyncOverloadDefaultStartAndCount(query, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(16).invoke(this._obj, [DynWinRtValue.i32(query)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_StorageFile(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    async getFoldersAsync(query, startIndex, maxItemsToRetrieve, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(17).invoke(this._obj, [DynWinRtValue.i32(query), DynWinRtValue.u32(startIndex), DynWinRtValue.u32(maxItemsToRetrieve)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_StorageFolder(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    /**
     * Overload of `getFoldersAsync` with default start, count.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async getFoldersAsyncOverloadDefaultStartAndCount(query, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(18).invoke(this._obj, [DynWinRtValue.i32(query)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_StorageFolder(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    async getItemsAsync(startIndex, maxItemsToRetrieve, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(19).invoke(this._obj, [DynWinRtValue.u32(startIndex), DynWinRtValue.u32(maxItemsToRetrieve)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_IStorageItem(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    areQueryOptionsSupported(queryOptions) {
        return _IStorageFolderQueryOperations.method(20).invoke(this._obj, [_unwrap(queryOptions)]).toBool();
    }

    isCommonFolderQuerySupported(query) {
        return _IStorageFolderQueryOperations.method(21).invoke(this._obj, [DynWinRtValue.i32(query)]).toBool();
    }

    isCommonFileQuerySupported(query) {
        return _IStorageFolderQueryOperations.method(22).invoke(this._obj, [DynWinRtValue.i32(query)]).toBool();
    }
}
