// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';

export declare const IID_IStorePrice2: WinGuid;

export declare class IStorePrice2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStorePrice2;

    get unformattedBasePrice(): string;

    get unformattedPrice(): string;

    get unformattedRecurrencePrice(): string;
}
