// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { StorageItemContentProperties } from './StorageItemContentProperties.js';
import { StorageItemThumbnail } from './StorageItemThumbnail.js';
import { ThumbnailMode } from './ThumbnailMode.js';
import { ThumbnailOptions } from './ThumbnailOptions.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';

export const IID_IStorageItemProperties = WinGuid.parse('86664478-8029-46fe-a789-1c2f3e2ffb5c');

const _IStorageItemProperties = DynWinRtType.registerInterface(
    "IStorageItemProperties", IID_IStorageItemProperties)
    .addMethod("GetThumbnailAsyncOverloadDefaultSizeDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))))
    .addMethod("GetThumbnailAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))))
    .addMethod("GetThumbnailAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailMode', ['PicturesView', 'VideosView', 'MusicView', 'DocumentsView', 'ListView', 'SingleItem'], [0, 1, 2, 3, 4, 5])).addIn(DynWinRtType.u32()).addIn(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailOptions', ['None', 'ReturnOnlyIfCached', 'ResizeThumbnail', 'UseCurrentScale'], [0, 1, 2, 4])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemThumbnail', WinGuid.parse('cc254827-4b3d-438f-9232-10c76bc7e038')))))
    .addMethod("get_DisplayName", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_DisplayType", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_FolderRelativeId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Properties", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.StorageItemContentProperties', WinGuid.parse('05294bad-bc38-48bf-85d7-770e0e2ae0ba'))));

export class IStorageItemProperties {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageItemProperties(obj.cast(IID_IStorageItemProperties));
    }

    /**
     * Overload of `getThumbnailAsync` with default size, default, options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async getThumbnailAsyncOverloadDefaultSizeDefaultOptions(mode, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemProperties.method(6).invoke(this._obj, [DynWinRtValue.i32(mode)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorageItemThumbnail(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    /**
     * Overload of `getThumbnailAsync` with default options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async getThumbnailAsyncOverloadDefaultOptions(mode, requestedSize, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemProperties.method(7).invoke(this._obj, [DynWinRtValue.i32(mode), DynWinRtValue.u32(requestedSize)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorageItemThumbnail(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    async getThumbnailAsync(mode, requestedSize, options, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemProperties.method(8).invoke(this._obj, [DynWinRtValue.i32(mode), DynWinRtValue.u32(requestedSize), DynWinRtValue.i32(options)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorageItemThumbnail(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    get displayName() {
        return _IStorageItemProperties.method(9).invoke(this._obj, []).toString();
    }

    get displayType() {
        return _IStorageItemProperties.method(10).invoke(this._obj, []).toString();
    }

    get folderRelativeId() {
        return _IStorageItemProperties.method(11).invoke(this._obj, []).toString();
    }

    get properties() {
        return new StorageItemContentProperties(_IStorageItemProperties.method(12).invoke(this._obj, []));
    }
}
