// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';

export declare const IID_IStoreQueueItem2: WinGuid;

export declare class IStoreQueueItem2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStoreQueueItem2;

    cancelInstallAsync(signal?: AbortSignal): Promise<void>;

    pauseInstallAsync(signal?: AbortSignal): Promise<void>;

    resumeInstallAsync(signal?: AbortSignal): Promise<void>;
}
