// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtValue, DynWinRtStruct, WinGuid } from '@microsoft/dynwinrt';
import { IIterable_StorePackageUpdate } from './IIterable_StorePackageUpdate.js';
import { IIterable_String } from './IIterable_String.js';
import { IVectorView_StoreQueueItem } from './IVectorView_StoreQueueItem.js';
import { Package } from './Package.js';
import { StoreCanAcquireLicenseResult } from './StoreCanAcquireLicenseResult.js';
import { StorePackageInstallOptions } from './StorePackageInstallOptions.js';
import { StorePackageUpdate } from './StorePackageUpdate.js';
import { StorePackageUpdateResult } from './StorePackageUpdateResult.js';
import { StoreProductOptions } from './StoreProductOptions.js';
import { StoreProductQueryResult } from './StoreProductQueryResult.js';
import { StoreUninstallStorePackageResult } from './StoreUninstallStorePackageResult.js';

/**
 * A WinRT async operation that supports progress reporting and cancellation.
 *
 * - `await op` — wait for the final result
 * - `op.progress(cb)` — receive incremental progress updates (chainable)
 * - `op.cancel()` — cancel the underlying WinRT operation
 */
type WinRTAsyncWithProgress<T, P = unknown> = Promise<T> & {
    /** Register a callback for progress updates. Returns `this` for chaining. */
    progress(cb: (value: P) => void): WinRTAsyncWithProgress<T, P>;
    /** Get the underlying Promise (equivalent to awaiting directly). */
    toPromise(): Promise<T>;
    /** Cancel the underlying WinRT async operation. */
    cancel(): void;
};

export interface StorePackageUpdateStatus {
    packageFamilyName: string;
    packageDownloadSizeInBytes: bigint;
    packageBytesDownloaded: bigint;
    packageDownloadProgress: number;
    totalDownloadProgress: number;
    packageUpdateState: number;
}
/** Convert a WinRT struct value into a `StorePackageUpdateStatus` object. */
export declare function unpackStorePackageUpdateStatus(v: DynWinRtValue): StorePackageUpdateStatus;
export declare const StorePackageUpdateStatus_Type: DynWinRtType;
/** Convert a `StorePackageUpdateStatus` object into a WinRT struct value. */
export declare function packStorePackageUpdateStatus(v: StorePackageUpdateStatus): DynWinRtStruct;

export declare const IID_IStoreContext3: WinGuid;

export declare class IStoreContext3 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStoreContext3;

    get canSilentlyDownloadStorePackageUpdates(): boolean;

    trySilentDownloadStorePackageUpdatesAsync(storePackageUpdates: IIterable_StorePackageUpdate | StorePackageUpdate[], signal?: AbortSignal): WinRTAsyncWithProgress<StorePackageUpdateResult, StorePackageUpdateStatus>;

    trySilentDownloadAndInstallStorePackageUpdatesAsync(storePackageUpdates: IIterable_StorePackageUpdate | StorePackageUpdate[], signal?: AbortSignal): WinRTAsyncWithProgress<StorePackageUpdateResult, StorePackageUpdateStatus>;

    canAcquireStoreLicenseForOptionalPackageAsync(optionalPackage: Package, signal?: AbortSignal): Promise<StoreCanAcquireLicenseResult>;

    canAcquireStoreLicenseAsync(productStoreId: string, signal?: AbortSignal): Promise<StoreCanAcquireLicenseResult>;

    getStoreProductsWithOptionsAsync(productKinds: IIterable_String | string[], storeIds: IIterable_String | string[], storeProductOptions: StoreProductOptions, signal?: AbortSignal): Promise<StoreProductQueryResult>;

    getAssociatedStoreQueueItemsAsync(signal?: AbortSignal): Promise<IVectorView_StoreQueueItem>;

    getStoreQueueItemsAsync(storeIds: IIterable_String | string[], signal?: AbortSignal): Promise<IVectorView_StoreQueueItem>;

    requestDownloadAndInstallStorePackagesWithInstallOptionsAsync(storeIds: IIterable_String | string[], storePackageInstallOptions: StorePackageInstallOptions, signal?: AbortSignal): WinRTAsyncWithProgress<StorePackageUpdateResult, StorePackageUpdateStatus>;

    downloadAndInstallStorePackagesAsync(storeIds: IIterable_String | string[], signal?: AbortSignal): WinRTAsyncWithProgress<StorePackageUpdateResult, StorePackageUpdateStatus>;

    requestUninstallStorePackageAsync(package_: Package, signal?: AbortSignal): Promise<StoreUninstallStorePackageResult>;

    requestUninstallStorePackageByStoreIdAsync(storeId: string, signal?: AbortSignal): Promise<StoreUninstallStorePackageResult>;

    uninstallStorePackageAsync(package_: Package, signal?: AbortSignal): Promise<StoreUninstallStorePackageResult>;

    uninstallStorePackageByStoreIdAsync(storeId: string, signal?: AbortSignal): Promise<StoreUninstallStorePackageResult>;
}
