// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { FileAccessMode } from './FileAccessMode.js';
import { StorageOpenOptions } from './StorageOpenOptions.js';
import { StorageStreamTransaction } from './StorageStreamTransaction.js';
import { IID_IRandomAccessStream, IRandomAccessStream } from './IRandomAccessStream.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';

export const IID_IStorageFile2 = WinGuid.parse('954e4bcf-0a77-42fb-b777-c2ed58a52e44');

const _IStorageFile2 = DynWinRtType.registerInterface(
    "IStorageFile2", IID_IStorageFile2)
    .addMethod("OpenWithOptionsAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.FileAccessMode', ['Read', 'ReadWrite'], [0, 1])).addIn(DynWinRtType.enumType('Windows.Storage.StorageOpenOptions', ['None', 'AllowOnlyReaders', 'AllowReadersAndWriters'], [0, 1, 2])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('905a0fe1-bc53-11df-8c49-001e4fc686da')))))
    .addMethod("OpenTransactedWriteWithOptionsAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.StorageOpenOptions', ['None', 'AllowOnlyReaders', 'AllowReadersAndWriters'], [0, 1, 2])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageStreamTransaction', WinGuid.parse('f67cf363-a53d-4d94-ae2c-67232d93acdd')))));

export class IStorageFile2 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageFile2(obj.cast(IID_IStorageFile2));
    }

    async openWithOptionsAsync(accessMode, options, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile2.method(6).invoke(this._obj, [DynWinRtValue.i32(accessMode), DynWinRtValue.i32(options)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IRandomAccessStream(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    async openTransactedWriteWithOptionsAsync(options, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFile2.method(7).invoke(this._obj, [DynWinRtValue.i32(options)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorageStreamTransaction(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
}
