// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { ThumbnailType } from './ThumbnailType.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';

export const IID_IThumbnailProperties = WinGuid.parse('693dd42f-dbe7-49b5-b3b3-2893ac5d3423');

const _IThumbnailProperties = DynWinRtType.registerInterface(
    "IThumbnailProperties", IID_IThumbnailProperties)
    .addMethod("get_OriginalWidth", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_OriginalHeight", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_ReturnedSmallerCachedSize", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_Type", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Storage.FileProperties.ThumbnailType', ['Image', 'Icon'], [0, 1])));

export class IThumbnailProperties {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IThumbnailProperties(obj.cast(IID_IThumbnailProperties));
    }

    get originalWidth() {
        return _IThumbnailProperties.method(6).invoke(this._obj, []).toNumber();
    }

    get originalHeight() {
        return _IThumbnailProperties.method(7).invoke(this._obj, []).toNumber();
    }

    get returnedSmallerCachedSize() {
        return _IThumbnailProperties.method(8).invoke(this._obj, []).toBool();
    }

    get type() {
        return _IThumbnailProperties.method(9).invoke(this._obj, []).toNumber();
    }
}
