// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { StorePackageUpdate } from './StorePackageUpdate.js';

export declare const IID_IVectorView_StorePackageUpdate: WinGuid;

export declare class IVectorView_StorePackageUpdate {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IVectorView_StorePackageUpdate;

    getAt(index: number): StorePackageUpdate;

    get size(): number;


    get length(): number;


    at(index: number): StorePackageUpdate | undefined;


    toArray(): StorePackageUpdate[];


    [Symbol.iterator](): IterableIterator<StorePackageUpdate>;

    /**
     * Return the index of `value`, or -1 if not found.
     */
    indexOf(value: StorePackageUpdate): number;
}
