// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { Uri } from './Uri.js';

export declare const IID_IVectorView_Uri: WinGuid;

export declare class IVectorView_Uri {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IVectorView_Uri;

    getAt(index: number): Uri;

    get size(): number;


    get length(): number;


    at(index: number): Uri | undefined;


    toArray(): Uri[];


    [Symbol.iterator](): IterableIterator<Uri>;

    /**
     * Return the index of `value`, or -1 if not found.
     */
    indexOf(value: Uri): number;
}
