// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { IVectorView_Package } from './IVectorView_Package.js';
import { Package } from './Package.js';

export declare const IID_IVector_Package: WinGuid;

export declare class IVector_Package {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IVector_Package;

    getAt(index: number): Package;

    get size(): number;

    getView(): IVectorView_Package;

    setAt(index: number, value: Package): void;

    insertAt(index: number, value: Package): void;

    removeAt(index: number): void;

    append(value: Package): void;

    removeAtEnd(): void;

    clear(): void;


    get length(): number;


    at(index: number): Package | undefined;


    toArray(): Package[];


    [Symbol.iterator](): IterableIterator<Package>;

    /**
     * Return the index of `value`, or -1 if not found.
     */
    indexOf(value: Package): number;

    /**
     * Create a new IVector from an array of items.
     */
    static create(items: Package[]): IVector_Package;
}
