// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { PackageContentGroup } from './PackageContentGroup.js';

export declare const IID_IVectorView_PackageContentGroup: WinGuid;

export declare class IVectorView_PackageContentGroup {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IVectorView_PackageContentGroup;

    getAt(index: number): PackageContentGroup;

    get size(): number;


    get length(): number;


    at(index: number): PackageContentGroup | undefined;


    toArray(): PackageContentGroup[];


    [Symbol.iterator](): IterableIterator<PackageContentGroup>;

    /**
     * Return the index of `value`, or -1 if not found.
     */
    indexOf(value: PackageContentGroup): number;
}
