// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { Package } from './Package.js';

export declare const IID_IVectorView_Package: WinGuid;

export declare class IVectorView_Package {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IVectorView_Package;

    getAt(index: number): Package;

    get size(): number;


    get length(): number;


    at(index: number): Package | undefined;


    toArray(): Package[];


    [Symbol.iterator](): IterableIterator<Package>;

    /**
     * Return the index of `value`, or -1 if not found.
     */
    indexOf(value: Package): number;
}
