// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { StoreAvailability } from './StoreAvailability.js';

export declare const IID_IVectorView_StoreAvailability: WinGuid;

export declare class IVectorView_StoreAvailability {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IVectorView_StoreAvailability;

    getAt(index: number): StoreAvailability;

    get size(): number;


    get length(): number;


    at(index: number): StoreAvailability | undefined;


    toArray(): StoreAvailability[];


    [Symbol.iterator](): IterableIterator<StoreAvailability>;

    /**
     * Return the index of `value`, or -1 if not found.
     */
    indexOf(value: StoreAvailability): number;
}
