// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { StorePackageUpdateState } from './StorePackageUpdateState.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';

export const IID_IVectorView_StorePackageUpdateStatus = DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.structType('Windows.Services.Store.StorePackageUpdateStatus', [DynWinRtType.hstring(), DynWinRtType.u64(), DynWinRtType.u64(), DynWinRtType.f64(), DynWinRtType.f64(), DynWinRtType.enumType('Windows.Services.Store.StorePackageUpdateState', ['Pending', 'Downloading', 'Deploying', 'Completed', 'Canceled', 'OtherError', 'ErrorLowBattery', 'ErrorWiFiRecommended', 'ErrorWiFiRequired'], [0, 1, 2, 3, 4, 5, 6, 7, 8])])]).iid();

const _IVectorView_StorePackageUpdateStatus = DynWinRtType.registerInterface(
    "IVectorView_StorePackageUpdateStatus", IID_IVectorView_StorePackageUpdateStatus)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.structType('Windows.Services.Store.StorePackageUpdateStatus', [DynWinRtType.hstring(), DynWinRtType.u64(), DynWinRtType.u64(), DynWinRtType.f64(), DynWinRtType.f64(), DynWinRtType.enumType('Windows.Services.Store.StorePackageUpdateState', ['Pending', 'Downloading', 'Deploying', 'Completed', 'Canceled', 'OtherError', 'ErrorLowBattery', 'ErrorWiFiRecommended', 'ErrorWiFiRequired'], [0, 1, 2, 3, 4, 5, 6, 7, 8])])))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Services.Store.StorePackageUpdateStatus', [DynWinRtType.hstring(), DynWinRtType.u64(), DynWinRtType.u64(), DynWinRtType.f64(), DynWinRtType.f64(), DynWinRtType.enumType('Windows.Services.Store.StorePackageUpdateState', ['Pending', 'Downloading', 'Deploying', 'Completed', 'Canceled', 'OtherError', 'ErrorLowBattery', 'ErrorWiFiRecommended', 'ErrorWiFiRequired'], [0, 1, 2, 3, 4, 5, 6, 7, 8])])).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.structType('Windows.Services.Store.StorePackageUpdateStatus', [DynWinRtType.hstring(), DynWinRtType.u64(), DynWinRtType.u64(), DynWinRtType.f64(), DynWinRtType.f64(), DynWinRtType.enumType('Windows.Services.Store.StorePackageUpdateState', ['Pending', 'Downloading', 'Deploying', 'Completed', 'Canceled', 'OtherError', 'ErrorLowBattery', 'ErrorWiFiRecommended', 'ErrorWiFiRequired'], [0, 1, 2, 3, 4, 5, 6, 7, 8])]))).addOut(DynWinRtType.u32()));

export function unpackStorePackageUpdateStatus(v) {
    const s = v.asStruct();
    return { packageFamilyName: s.getHstring(0), packageDownloadSizeInBytes: s.getU64(1), packageBytesDownloaded: s.getU64(2), packageDownloadProgress: s.getF64(3), totalDownloadProgress: s.getF64(4), packageUpdateState: s.getI32(5) };
}
const _unpackStorePackageUpdateStatus = unpackStorePackageUpdateStatus;
export const StorePackageUpdateStatus_Type = DynWinRtType.structType('Windows.Services.Store.StorePackageUpdateStatus', [DynWinRtType.hstring(), DynWinRtType.u64(), DynWinRtType.u64(), DynWinRtType.f64(), DynWinRtType.f64(), DynWinRtType.enumType('Windows.Services.Store.StorePackageUpdateState', ['Pending', 'Downloading', 'Deploying', 'Completed', 'Canceled', 'OtherError', 'ErrorLowBattery', 'ErrorWiFiRecommended', 'ErrorWiFiRequired'], [0, 1, 2, 3, 4, 5, 6, 7, 8])]);
const _StorePackageUpdateStatus_Type = StorePackageUpdateStatus_Type;
export function packStorePackageUpdateStatus(v) {
    const s = DynWinRtStruct.create(StorePackageUpdateStatus_Type);
    s.setHstring(0, v.packageFamilyName);
    s.setU64(1, v.packageDownloadSizeInBytes);
    s.setU64(2, v.packageBytesDownloaded);
    s.setF64(3, v.packageDownloadProgress);
    s.setF64(4, v.totalDownloadProgress);
    s.setI32(5, v.packageUpdateState);
    return s;
}
const _packStorePackageUpdateStatus = packStorePackageUpdateStatus;

export class IVectorView_StorePackageUpdateStatus {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IVectorView_StorePackageUpdateStatus);
    }

    static from(obj) {
        return new IVectorView_StorePackageUpdateStatus(obj.cast(IID_IVectorView_StorePackageUpdateStatus));
    }

    getAt(index) {
        return _unpackStorePackageUpdateStatus(_IVectorView_StorePackageUpdateStatus.method(6).invoke(this._obj, [DynWinRtValue.u32(index)]));
    }

    get size() {
        return _IVectorView_StorePackageUpdateStatus.method(7).invoke(this._obj, []).toNumber();
    }

    /** Alias for {@link size}; matches Array.length / TypedArray.length. */
    get length() { return this.size; }

    /** Element at `index`. Negative indices count from the end (Array.prototype.at semantics). */
    at(index) {
        const n = this.size;
        const i = index < 0 ? n + index : index;
        if (i < 0 || i >= n) return undefined;
        return this.getAt(i);
    }

    /** Materialize as a plain JS array. */
    toArray() {
        const n = this.size;
        const out = new Array(n);
        for (let i = 0; i < n; i++) out[i] = this.getAt(i);
        return out;
    }

    *[Symbol.iterator]() {
        const n = this.size;
        for (let i = 0; i < n; i++) yield this.getAt(i);
    }

    /**
     * Return the index of `value`, or -1 if not found.
     */
    indexOf(value) {
        return (() => { const _r = _IVectorView_StorePackageUpdateStatus.method(8).invokeAll(this._obj, [_packStorePackageUpdateStatus(value).toValue()]); return _r[1].toBool() ? _r[0].toNumber() : -1; })();
    }
}
