// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { StoreQueueItem } from './StoreQueueItem.js';

export declare const IID_IVectorView_StoreQueueItem: WinGuid;

export declare class IVectorView_StoreQueueItem {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IVectorView_StoreQueueItem;

    getAt(index: number): StoreQueueItem;

    get size(): number;


    get length(): number;


    at(index: number): StoreQueueItem | undefined;


    toArray(): StoreQueueItem[];


    [Symbol.iterator](): IterableIterator<StoreQueueItem>;

    /**
     * Return the index of `value`, or -1 if not found.
     */
    indexOf(value: StoreQueueItem): number;
}
