// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { User } from './User.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';
const _unwrap = (x) => x?._obj ?? x;

export const IID_IVectorView_User = DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))]).iid();

const _IVectorView_User = DynWinRtType.registerInterface(
    "IVectorView_User", IID_IVectorView_User)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b')))).addOut(DynWinRtType.u32()));

export class IVectorView_User {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IVectorView_User);
    }

    static from(obj) {
        return new IVectorView_User(obj.cast(IID_IVectorView_User));
    }

    getAt(index) {
        return new User(_IVectorView_User.method(6).invoke(this._obj, [DynWinRtValue.u32(index)]));
    }

    get size() {
        return _IVectorView_User.method(7).invoke(this._obj, []).toNumber();
    }

    /** Alias for {@link size}; matches Array.length / TypedArray.length. */
    get length() { return this.size; }

    /** Element at `index`. Negative indices count from the end (Array.prototype.at semantics). */
    at(index) {
        const n = this.size;
        const i = index < 0 ? n + index : index;
        if (i < 0 || i >= n) return undefined;
        return this.getAt(i);
    }

    /** Materialize as a plain JS array. */
    toArray() {
        const n = this.size;
        const out = new Array(n);
        for (let i = 0; i < n; i++) out[i] = this.getAt(i);
        return out;
    }

    *[Symbol.iterator]() {
        const n = this.size;
        for (let i = 0; i < n; i++) yield this.getAt(i);
    }

    /**
     * Return the index of `value`, or -1 if not found.
     */
    indexOf(value) {
        return (() => { const _r = _IVectorView_User.method(8).invokeAll(this._obj, [_unwrap(value)]); return _r[1].toBool() ? _r[0].toNumber() : -1; })();
    }
}
