// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { StoreSku } from './StoreSku.js';

export declare const IID_IVectorView_StoreSku: WinGuid;

export declare class IVectorView_StoreSku {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IVectorView_StoreSku;

    getAt(index: number): StoreSku;

    get size(): number;


    get length(): number;


    at(index: number): StoreSku | undefined;


    toArray(): StoreSku[];


    [Symbol.iterator](): IterableIterator<StoreSku>;

    /**
     * Return the index of `value`, or -1 if not found.
     */
    indexOf(value: StoreSku): number;
}
