// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IVectorView_SortEntry } from './IVectorView_SortEntry.js';
import { IID_StreamedFileDataRequestedHandler, StreamedFileDataRequestedHandler_PARAM_TYPES } from './StreamedFileDataRequestedHandler.js';
import { IID_TypedEventHandler_IStorageQueryResultBase_Object, TypedEventHandler_IStorageQueryResultBase_Object_PARAM_TYPES } from './TypedEventHandler_IStorageQueryResultBase_Object.js';
import { IID_TypedEventHandler_StoreContext_Object, TypedEventHandler_StoreContext_Object_PARAM_TYPES } from './TypedEventHandler_StoreContext_Object.js';
import { IID_TypedEventHandler_StorePackageLicense_Object, TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES } from './TypedEventHandler_StorePackageLicense_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_Object, TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_Object.js';
import { IID_TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs, TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs_PARAM_TYPES } from './TypedEventHandler_StoreQueueItem_StoreQueueItemCompletedEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { StreamedFileDataRequest } from './StreamedFileDataRequest.js';
import { IStorageQueryResultBase } from './IStorageQueryResultBase.js';
import { StoreContext } from './StoreContext.js';
import { StorePackageLicense } from './StorePackageLicense.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { UserWatcher } from './UserWatcher.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';
const _unwrap = (x) => x?._obj ?? x;

export const IID_IVector_SortEntry = DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()])]).iid();

const _IVector_SortEntry = DynWinRtType.registerInterface(
    "IVector_SortEntry", IID_IVector_SortEntry)
    .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()])))
    .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("GetView", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()])])))
    .addMethod("IndexOf", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()])).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
    .addMethod("SetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()])))
    .addMethod("InsertAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()])))
    .addMethod("RemoveAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("Append", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()])))
    .addMethod("RemoveAtEnd", new DynWinRtMethodSig())
    .addMethod("Clear", new DynWinRtMethodSig())
    .addMethod("GetMany", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOutFill(DynWinRtType.arrayType(DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()]))).addOut(DynWinRtType.u32()))
    .addMethod("ReplaceAll", new DynWinRtMethodSig().addIn(DynWinRtType.arrayType(DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()]))));

export function unpackSortEntry(v) {
    const s = v.asStruct();
    return { propertyName: s.getHstring(0), ascendingOrder: s.getU8(1) !== 0 };
}
const _unpackSortEntry = unpackSortEntry;
export const SortEntry_Type = DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()]);
const _SortEntry_Type = SortEntry_Type;
export function packSortEntry(v) {
    const s = DynWinRtStruct.create(SortEntry_Type);
    s.setHstring(0, v.propertyName);
    s.setU8(1, v.ascendingOrder ? 1 : 0);
    return s;
}
const _packSortEntry = packSortEntry;

export class IVector_SortEntry {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IVector_SortEntry);
    }

    static from(obj) {
        return new IVector_SortEntry(obj.cast(IID_IVector_SortEntry));
    }

    getAt(index) {
        return _unpackSortEntry(_IVector_SortEntry.method(6).invoke(this._obj, [DynWinRtValue.u32(index)]));
    }

    get size() {
        return _IVector_SortEntry.method(7).invoke(this._obj, []).toNumber();
    }

    getView() {
        return new IVectorView_SortEntry(_IVector_SortEntry.method(8).invoke(this._obj, []));
    }

    setAt(index, value) {
        _IVector_SortEntry.method(10).invoke(this._obj, [DynWinRtValue.u32(index), _packSortEntry(value).toValue()]);
    }

    insertAt(index, value) {
        _IVector_SortEntry.method(11).invoke(this._obj, [DynWinRtValue.u32(index), _packSortEntry(value).toValue()]);
    }

    removeAt(index) {
        _IVector_SortEntry.method(12).invoke(this._obj, [DynWinRtValue.u32(index)]);
    }

    append(value) {
        _IVector_SortEntry.method(13).invoke(this._obj, [_packSortEntry(value).toValue()]);
    }

    removeAtEnd() {
        _IVector_SortEntry.method(14).invoke(this._obj, []);
    }

    clear() {
        _IVector_SortEntry.method(15).invoke(this._obj, []);
    }

    /** Alias for {@link size}; matches Array.length / TypedArray.length. */
    get length() { return this.size; }

    /** Element at `index`. Negative indices count from the end (Array.prototype.at semantics). */
    at(index) {
        const n = this.size;
        const i = index < 0 ? n + index : index;
        if (i < 0 || i >= n) return undefined;
        return this.getAt(i);
    }

    /** Materialize as a plain JS array. */
    toArray() {
        const n = this.size;
        const out = new Array(n);
        for (let i = 0; i < n; i++) out[i] = this.getAt(i);
        return out;
    }

    *[Symbol.iterator]() {
        const n = this.size;
        for (let i = 0; i < n; i++) yield this.getAt(i);
    }

    /**
     * Return the index of `value`, or -1 if not found.
     */
    indexOf(value) {
        return (() => { const _r = _IVector_SortEntry.method(9).invokeAll(this._obj, [_packSortEntry(value).toValue()]); return _r[1].toBool() ? _r[0].toNumber() : -1; })();
    }

    /**
     * Create a new IVector from an array of items.
     */
    static create(items) {
        return new IVector_SortEntry(DynWinRtValue.createVector(items.map(i => _unwrap(i)), DynWinRtType.structType('Windows.Storage.Search.SortEntry', [DynWinRtType.hstring(), DynWinRtType.boolType()])));
    }
}
