// Generated by dynwinrt-codegen — do not edit
import { WinGuid } from '@microsoft/dynwinrt';
import { IVectorView_PackageContentGroup } from './IVectorView_PackageContentGroup.js';
import { PackageContentGroup } from './PackageContentGroup.js';

export declare const IID_IVector_PackageContentGroup: WinGuid;

export declare class IVector_PackageContentGroup {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IVector_PackageContentGroup;

    getAt(index: number): PackageContentGroup;

    get size(): number;

    getView(): IVectorView_PackageContentGroup;

    setAt(index: number, value: PackageContentGroup): void;

    insertAt(index: number, value: PackageContentGroup): void;

    removeAt(index: number): void;

    append(value: PackageContentGroup): void;

    removeAtEnd(): void;

    clear(): void;


    get length(): number;


    at(index: number): PackageContentGroup | undefined;


    toArray(): PackageContentGroup[];


    [Symbol.iterator](): IterableIterator<PackageContentGroup>;

    /**
     * Return the index of `value`, or -1 if not found.
     */
    indexOf(value: PackageContentGroup): number;

    /**
     * Create a new IVector from an array of items.
     */
    static create(items: PackageContentGroup[]): IVector_PackageContentGroup;
}
