// Generated by dynwinrt-codegen — do not edit
export type PackageSignatureKind = (typeof PackageSignatureKind)[keyof typeof PackageSignatureKind];
export declare const PackageSignatureKind: {
    readonly None: 0;
    readonly Developer: 1;
    readonly Enterprise: 2;
    readonly Store: 3;
    readonly System: 4;
};
