// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { Package } from './Package.js';
import { PackageContentGroupState } from './PackageContentGroupState.js';

const IID_IPackageContentGroup = WinGuid.parse('8f62695d-120a-4798-b5e1-5800dda8f2e1');
const IID_IPackageContentGroupStatics = WinGuid.parse('70ee7619-5f12-4b92-b9ea-6ccada13bc75');

const _IPackageContentGroup = DynWinRtType.registerInterface(
    "IPackageContentGroup", IID_IPackageContentGroup)
    .addMethod("get_Package", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.ApplicationModel.Package', WinGuid.parse('163c792f-bd75-413c-bf23-b1fe7b95d825'))))
    .addMethod("get_Name", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_State", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.ApplicationModel.PackageContentGroupState', ['NotStaged', 'Queued', 'Staging', 'Staged'], [0, 1, 2, 3])))
    .addMethod("get_IsRequired", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()));

const _IPackageContentGroupStatics = DynWinRtType.registerInterface(
    "IPackageContentGroupStatics", IID_IPackageContentGroupStatics)
    .addMethod("get_RequiredGroupName", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

export class PackageContentGroup {
    _obj;
    static _s_IPackageContentGroupStatics;
    static s_IPackageContentGroupStatics() { return PackageContentGroup._s_IPackageContentGroupStatics ??= DynWinRtValue.activationFactory('Windows.ApplicationModel.PackageContentGroup').cast(IID_IPackageContentGroupStatics); }

    constructor(obj) {
        this._obj = obj.cast(IID_IPackageContentGroup);
    }
    static get requiredGroupName() {
        return _IPackageContentGroupStatics.method(6).invoke(PackageContentGroup.s_IPackageContentGroupStatics(), []).toString();
    }
    get package_() {
        return new Package(_IPackageContentGroup.method(6).invoke(this._obj, []));
    }
    get name() {
        return _IPackageContentGroup.method(7).invoke(this._obj, []).toString();
    }
    get state() {
        return _IPackageContentGroup.method(8).invoke(this._obj, []).toNumber();
    }
    get isRequired() {
        return _IPackageContentGroup.method(9).invoke(this._obj, []).toBool();
    }
}
