// Generated by dynwinrt-codegen — do not edit
export type PackageRelationship = (typeof PackageRelationship)[keyof typeof PackageRelationship];
export declare const PackageRelationship: {
    readonly Dependencies: 0;
    readonly Dependents: 1;
    readonly All: 2;
};
