// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtValue, DynWinRtStruct } from '@microsoft/dynwinrt';
import { ProcessorArchitecture } from './ProcessorArchitecture.js';

export interface PackageVersion {
    major: number;
    minor: number;
    build: number;
    revision: number;
}
/** Convert a WinRT struct value into a `PackageVersion` object. */
export declare function unpackPackageVersion(v: DynWinRtValue): PackageVersion;
export declare const PackageVersion_Type: DynWinRtType;
/** Convert a `PackageVersion` object into a WinRT struct value. */
export declare function packPackageVersion(v: PackageVersion): DynWinRtStruct;

export declare class PackageId {
    private constructor();
    get name(): string;
    get version(): PackageVersion;
    get architecture(): ProcessorArchitecture;
    get resourceId(): string;
    get publisher(): string;
    get publisherId(): string;
    get fullName(): string;
    get familyName(): string;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
    get productId(): string;
    get author(): string;
}

export declare class IPackageIdWithMetadata {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IPackageIdWithMetadata;

    get productId(): string;

    get author(): string;
}
