// Generated by dynwinrt-codegen — do not edit
import { Package } from './Package.js';
import { PackageContentGroupState } from './PackageContentGroupState.js';

export declare class PackageContentGroup {
    private constructor();
    static get requiredGroupName(): string;
    get package_(): Package;
    get name(): string;
    get state(): PackageContentGroupState;
    get isRequired(): boolean;
}
