// Generated by dynwinrt-codegen — do not edit
export type PackageUpdateAvailability = (typeof PackageUpdateAvailability)[keyof typeof PackageUpdateAvailability];
export declare const PackageUpdateAvailability: {
    readonly Unknown: 0;
    readonly NoUpdates: 1;
    readonly Available: 2;
    readonly Required: 3;
    readonly Error: 4;
};
