// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';

const IID_IPackageStatus = WinGuid.parse('5fe74f71-a365-4c09-a02d-046d525ea1da');
const IID_IPackageStatus2 = WinGuid.parse('f428fa93-7c56-4862-acfa-abaedcc0694d');

const _IPackageStatus = DynWinRtType.registerInterface(
    "IPackageStatus", IID_IPackageStatus)
    .addMethod("VerifyIsOK", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_NotAvailable", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_PackageOffline", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_DataOffline", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_Disabled", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_NeedsRemediation", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_LicenseIssue", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_Modified", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_Tampered", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_DependencyIssue", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_Servicing", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_DeploymentInProgress", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()));

const _IPackageStatus2 = DynWinRtType.registerInterface(
    "IPackageStatus2", IID_IPackageStatus2)
    .addMethod("get_IsPartiallyStaged", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()));

export class PackageStatus {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IPackageStatus);
    }
    verifyIsOK() {
        return _IPackageStatus.method(6).invoke(this._obj, []).toBool();
    }
    get notAvailable() {
        return _IPackageStatus.method(7).invoke(this._obj, []).toBool();
    }
    get packageOffline() {
        return _IPackageStatus.method(8).invoke(this._obj, []).toBool();
    }
    get dataOffline() {
        return _IPackageStatus.method(9).invoke(this._obj, []).toBool();
    }
    get disabled() {
        return _IPackageStatus.method(10).invoke(this._obj, []).toBool();
    }
    get needsRemediation() {
        return _IPackageStatus.method(11).invoke(this._obj, []).toBool();
    }
    get licenseIssue() {
        return _IPackageStatus.method(12).invoke(this._obj, []).toBool();
    }
    get modified() {
        return _IPackageStatus.method(13).invoke(this._obj, []).toBool();
    }
    get tampered() {
        return _IPackageStatus.method(14).invoke(this._obj, []).toBool();
    }
    get dependencyIssue() {
        return _IPackageStatus.method(15).invoke(this._obj, []).toBool();
    }
    get servicing() {
        return _IPackageStatus.method(16).invoke(this._obj, []).toBool();
    }
    get deploymentInProgress() {
        return _IPackageStatus.method(17).invoke(this._obj, []).toBool();
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
    get isPartiallyStaged() {
        return _IPackageStatus2.method(6).invoke(this._obj.cast(IID_IPackageStatus2), []).toBool();
    }
}

export class IPackageStatus2 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IPackageStatus2(obj.cast(IID_IPackageStatus2));
    }

    get isPartiallyStaged() {
        return _IPackageStatus2.method(6).invoke(this._obj, []).toBool();
    }
}
