// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtValue, DynWinRtStruct } from '@microsoft/dynwinrt';
import { IIterable_String } from './IIterable_String.js';
import { IVectorView_AppListEntry } from './IVectorView_AppListEntry.js';
import { IVectorView_Package } from './IVectorView_Package.js';
import { IVector_Package } from './IVector_Package.js';
import { IVector_PackageContentGroup } from './IVector_PackageContentGroup.js';
import { AppInstallerInfo } from './AppInstallerInfo.js';
import { FindRelatedPackagesOptions } from './FindRelatedPackagesOptions.js';
import { PackageContentGroup } from './PackageContentGroup.js';
import { PackageId } from './PackageId.js';
import { PackageSignatureKind } from './PackageSignatureKind.js';
import { PackageStatus } from './PackageStatus.js';
import { PackageUpdateAvailabilityResult } from './PackageUpdateAvailabilityResult.js';
import { Uri } from './Uri.js';
import { StorageFolder } from './StorageFolder.js';
import { RandomAccessStreamReference } from './RandomAccessStreamReference.js';

export interface DateTime {
    universalTime: bigint;
}
/** Convert a WinRT struct value into a `DateTime` object. */
export declare function unpackDateTime(v: DynWinRtValue): DateTime;
export declare const DateTime_Type: DynWinRtType;
/** Convert a `DateTime` object into a WinRT struct value. */
export declare function packDateTime(v: DateTime): DynWinRtStruct;

export interface Size {
    width: number;
    height: number;
}
/** Convert a WinRT struct value into a `Size` object. */
export declare function unpackSize(v: DynWinRtValue): Size;
export declare const Size_Type: DynWinRtType;
/** Convert a `Size` object into a WinRT struct value. */
export declare function packSize(v: Size): DynWinRtStruct;

export declare class Package {
    private constructor();
    static get current(): Package;
    get id(): PackageId;
    get installedLocation(): StorageFolder;
    get isFramework(): boolean;
    get dependencies(): IVectorView_Package;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
    get displayName(): string;
    get publisherDisplayName(): string;
    get description(): string;
    get logo(): Uri;
    get isResourcePackage(): boolean;
    get isBundle(): boolean;
    get isDevelopmentMode(): boolean;
    get status(): PackageStatus;
    get installedDate(): DateTime;
    getAppListEntriesAsync(signal?: AbortSignal): Promise<IVectorView_AppListEntry>;
    get installDate(): DateTime;
    getThumbnailToken(): string;
    launch(parameters: string): void;
    get signatureKind(): PackageSignatureKind;
    get isOptional(): boolean;
    verifyContentIntegrityAsync(signal?: AbortSignal): Promise<boolean>;
    getContentGroupsAsync(signal?: AbortSignal): Promise<IVector_PackageContentGroup>;
    getContentGroupAsync(name: string, signal?: AbortSignal): Promise<PackageContentGroup>;
    stageContentGroupsAsync(names: IIterable_String | string[], signal?: AbortSignal): Promise<IVector_PackageContentGroup>;
    stageContentGroupsAsync(names: IIterable_String | string[], moveToHeadOfQueue: boolean, signal?: AbortSignal): Promise<IVector_PackageContentGroup>;
    setInUseAsync(inUse: boolean, signal?: AbortSignal): Promise<boolean>;
    getAppInstallerInfo(): AppInstallerInfo;
    checkUpdateAvailabilityAsync(signal?: AbortSignal): Promise<PackageUpdateAvailabilityResult>;
    get mutableLocation(): StorageFolder;
    get effectiveLocation(): StorageFolder;
    get effectiveExternalLocation(): StorageFolder;
    get machineExternalLocation(): StorageFolder;
    get userExternalLocation(): StorageFolder;
    get installedPath(): string;
    get mutablePath(): string;
    get effectivePath(): string;
    get effectiveExternalPath(): string;
    get machineExternalPath(): string;
    get userExternalPath(): string;
    getLogoAsRandomAccessStreamReference(size: Size): RandomAccessStreamReference;
    getAppListEntries(): IVectorView_AppListEntry;
    get isStub(): boolean;
    findRelatedPackages(options: FindRelatedPackagesOptions): IVector_Package;
    get sourceUriSchemeName(): string;
}

export declare class IPackage2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IPackage2;

    get displayName(): string;

    get publisherDisplayName(): string;

    get description(): string;

    get logo(): Uri;

    get isResourcePackage(): boolean;

    get isBundle(): boolean;

    get isDevelopmentMode(): boolean;
}

export declare class IPackage3 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IPackage3;

    get status(): PackageStatus;

    get installedDate(): DateTime;

    getAppListEntriesAsync(signal?: AbortSignal): Promise<IVectorView_AppListEntry>;
}

export declare class IPackageWithMetadata {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IPackageWithMetadata;

    get installDate(): DateTime;

    getThumbnailToken(): string;

    launch(parameters: string): void;
}

export declare class IPackage4 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IPackage4;

    get signatureKind(): PackageSignatureKind;

    get isOptional(): boolean;

    verifyContentIntegrityAsync(signal?: AbortSignal): Promise<boolean>;
}

export declare class IPackage5 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IPackage5;

    getContentGroupsAsync(signal?: AbortSignal): Promise<IVector_PackageContentGroup>;

    getContentGroupAsync(name: string, signal?: AbortSignal): Promise<PackageContentGroup>;

    stageContentGroupsAsync(names: IIterable_String | string[], signal?: AbortSignal): Promise<IVector_PackageContentGroup>;

    stageContentGroupsWithPriorityAsync(names: IIterable_String | string[], moveToHeadOfQueue: boolean, signal?: AbortSignal): Promise<IVector_PackageContentGroup>;

    setInUseAsync(inUse: boolean, signal?: AbortSignal): Promise<boolean>;
}

export declare class IPackage6 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IPackage6;

    getAppInstallerInfo(): AppInstallerInfo;

    checkUpdateAvailabilityAsync(signal?: AbortSignal): Promise<PackageUpdateAvailabilityResult>;
}

export declare class IPackage7 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IPackage7;

    get mutableLocation(): StorageFolder;

    get effectiveLocation(): StorageFolder;
}

export declare class IPackage8 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IPackage8;

    get effectiveExternalLocation(): StorageFolder;

    get machineExternalLocation(): StorageFolder;

    get userExternalLocation(): StorageFolder;

    get installedPath(): string;

    get mutablePath(): string;

    get effectivePath(): string;

    get effectiveExternalPath(): string;

    get machineExternalPath(): string;

    get userExternalPath(): string;

    getLogoAsRandomAccessStreamReference(size: Size): RandomAccessStreamReference;

    getAppListEntries(): IVectorView_AppListEntry;

    get isStub(): boolean;
}

export declare class IPackage9 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IPackage9;

    findRelatedPackages(options: FindRelatedPackagesOptions): IVector_Package;

    get sourceUriSchemeName(): string;
}
