// Generated by dynwinrt-codegen — do not edit
import { PackageUpdateAvailability } from './PackageUpdateAvailability.js';

export declare class PackageUpdateAvailabilityResult {
    private constructor();
    get availability(): PackageUpdateAvailability;
    get extendedError(): number;
}
