// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtValue, DynWinRtStruct } from '@microsoft/dynwinrt';
import { IVectorView_IStorageItem } from './IVectorView_IStorageItem.js';

export interface EventRegistrationToken {
    value: bigint;
}
/** Convert a WinRT struct value into a `EventRegistrationToken` object. */
export declare function unpackEventRegistrationToken(v: DynWinRtValue): EventRegistrationToken;
export declare const EventRegistrationToken_Type: DynWinRtType;
/** Convert a `EventRegistrationToken` object into a WinRT struct value. */
export declare function packEventRegistrationToken(v: EventRegistrationToken): DynWinRtStruct;

export declare class StorageItemQueryResult {
    private constructor();
    getItemsAsync(startIndex: number, maxNumberOfItems: number, signal?: AbortSignal): Promise<IVectorView_IStorageItem>;
    getItemsAsync(signal?: AbortSignal): Promise<IVectorView_IStorageItem>;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
}
