// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtValue, DynWinRtStruct } from '@microsoft/dynwinrt';
import { IVectorView_StorePackageUpdateStatus } from './IVectorView_StorePackageUpdateStatus.js';
import { IVectorView_StoreQueueItem } from './IVectorView_StoreQueueItem.js';
import { StorePackageUpdateState } from './StorePackageUpdateState.js';

export interface StorePackageUpdateStatus {
    packageFamilyName: string;
    packageDownloadSizeInBytes: bigint;
    packageBytesDownloaded: bigint;
    packageDownloadProgress: number;
    totalDownloadProgress: number;
    packageUpdateState: number;
}
/** Convert a WinRT struct value into a `StorePackageUpdateStatus` object. */
export declare function unpackStorePackageUpdateStatus(v: DynWinRtValue): StorePackageUpdateStatus;
export declare const StorePackageUpdateStatus_Type: DynWinRtType;
/** Convert a `StorePackageUpdateStatus` object into a WinRT struct value. */
export declare function packStorePackageUpdateStatus(v: StorePackageUpdateStatus): DynWinRtStruct;

export declare class StorePackageUpdateResult {
    private constructor();
    get overallState(): StorePackageUpdateState;
    get storePackageUpdateStatuses(): IVectorView_StorePackageUpdateStatus;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
    get storeQueueItems(): IVectorView_StoreQueueItem;
}

export declare class IStorePackageUpdateResult2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStorePackageUpdateResult2;

    get storeQueueItems(): IVectorView_StoreQueueItem;
}
