// Generated by dynwinrt-codegen — do not edit
export type StoreConsumableStatus = (typeof StoreConsumableStatus)[keyof typeof StoreConsumableStatus];
export declare const StoreConsumableStatus: {
    readonly Succeeded: 0;
    readonly InsufficentQuantity: 1;
    readonly NetworkError: 2;
    readonly ServerError: 3;
};
