// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtValue, DynWinRtStruct } from '@microsoft/dynwinrt';
import { StoreQueueItemCompletedEventArgs } from './StoreQueueItemCompletedEventArgs.js';
import { StoreQueueItemKind } from './StoreQueueItemKind.js';
import { StoreQueueItemStatus } from './StoreQueueItemStatus.js';

export interface EventRegistrationToken {
    value: bigint;
}
/** Convert a WinRT struct value into a `EventRegistrationToken` object. */
export declare function unpackEventRegistrationToken(v: DynWinRtValue): EventRegistrationToken;
export declare const EventRegistrationToken_Type: DynWinRtType;
/** Convert a `EventRegistrationToken` object into a WinRT struct value. */
export declare function packEventRegistrationToken(v: EventRegistrationToken): DynWinRtStruct;

export declare class StoreQueueItem {
    private constructor();
    get productId(): string;
    get packageFamilyName(): string;
    get installKind(): StoreQueueItemKind;
    getCurrentStatus(): StoreQueueItemStatus;
    /** Register a handler for the `Completed` event. Call the returned function to unsubscribe. */
    onCompleted(callback: (sender: StoreQueueItem, args: StoreQueueItemCompletedEventArgs) => void): () => void;
    /** Like `onCompleted` but automatically unsubscribes after the first invocation. */
    onceCompleted(callback: (sender: StoreQueueItem, args: StoreQueueItemCompletedEventArgs) => void): () => void;
    /** Unsubscribe from the `Completed` event using a raw registration token. */
    offCompleted(token: unknown): void;
    /** Register a handler for the `StatusChanged` event. Call the returned function to unsubscribe. */
    onStatusChanged(callback: (sender: StoreQueueItem, args: unknown) => void): () => void;
    /** Like `onStatusChanged` but automatically unsubscribes after the first invocation. */
    onceStatusChanged(callback: (sender: StoreQueueItem, args: unknown) => void): () => void;
    /** Unsubscribe from the `StatusChanged` event using a raw registration token. */
    offStatusChanged(token: unknown): void;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
    cancelInstallAsync(signal?: AbortSignal): Promise<void>;
    pauseInstallAsync(signal?: AbortSignal): Promise<void>;
    resumeInstallAsync(signal?: AbortSignal): Promise<void>;
}

export declare class IStoreQueueItem2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStoreQueueItem2;

    cancelInstallAsync(signal?: AbortSignal): Promise<void>;

    pauseInstallAsync(signal?: AbortSignal): Promise<void>;

    resumeInstallAsync(signal?: AbortSignal): Promise<void>;
}
