// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { Uri } from './Uri.js';
import { StoreImage } from './StoreImage.js';

const IID_IStoreVideo = WinGuid.parse('f26cb184-6f5e-4dc2-886c-3c63083c2f94');

const _IStoreVideo = DynWinRtType.registerInterface(
    "IStoreVideo", IID_IStoreVideo)
    .addMethod("get_Uri", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Foundation.Uri', WinGuid.parse('9e365e57-48b2-4160-956f-c7385120bbfc'))))
    .addMethod("get_VideoPurposeTag", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_Width", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_Height", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_Caption", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_PreviewImage", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Services.Store.StoreImage', WinGuid.parse('081fd248-adb4-4b64-a993-784789926ed5'))));

export class StoreVideo {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IStoreVideo);
    }
    get uri() {
        return new Uri(_IStoreVideo.method(6).invoke(this._obj, []));
    }
    get videoPurposeTag() {
        return _IStoreVideo.method(7).invoke(this._obj, []).toString();
    }
    get width() {
        return _IStoreVideo.method(8).invoke(this._obj, []).toNumber();
    }
    get height() {
        return _IStoreVideo.method(9).invoke(this._obj, []).toNumber();
    }
    get caption() {
        return _IStoreVideo.method(10).invoke(this._obj, []).toString();
    }
    get previewImage() {
        return new StoreImage(_IStoreVideo.method(11).invoke(this._obj, []));
    }
}
