// Generated by dynwinrt-codegen — do not edit
import { DocumentProperties } from './DocumentProperties.js';
import { ImageProperties } from './ImageProperties.js';
import { MusicProperties } from './MusicProperties.js';
import { VideoProperties } from './VideoProperties.js';

export declare class StorageItemContentProperties {
    private constructor();
    getMusicPropertiesAsync(signal?: AbortSignal): Promise<MusicProperties>;
    getVideoPropertiesAsync(signal?: AbortSignal): Promise<VideoProperties>;
    getImagePropertiesAsync(signal?: AbortSignal): Promise<ImageProperties>;
    getDocumentPropertiesAsync(signal?: AbortSignal): Promise<DocumentProperties>;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
}
