// Generated by dynwinrt-codegen — do not edit
export type StoreCanLicenseStatus = (typeof StoreCanLicenseStatus)[keyof typeof StoreCanLicenseStatus];
export declare const StoreCanLicenseStatus: {
    readonly NotLicensableToUser: 0;
    readonly Licensable: 1;
    readonly LicenseActionNotApplicableToProduct: 2;
    readonly NetworkError: 3;
    readonly ServerError: 4;
};
