// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';

const IID_IStorageLibraryChangeTrackerOptions = WinGuid.parse('bb52bcd4-1a6d-59c0-ad2a-823a20532483');

const _IStorageLibraryChangeTrackerOptions = DynWinRtType.registerInterface(
    "IStorageLibraryChangeTrackerOptions", IID_IStorageLibraryChangeTrackerOptions)
    .addMethod("get_TrackChangeDetails", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("put_TrackChangeDetails", new DynWinRtMethodSig().addIn(DynWinRtType.boolType()));

const _IActivationFactory = DynWinRtType.registerInterface('IActivationFactory', WinGuid.parse('00000035-0000-0000-c000-000000000046'))
    .addMethod('ActivateInstance', new DynWinRtMethodSig().addOut(DynWinRtType.object()));

export class StorageLibraryChangeTrackerOptions {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IStorageLibraryChangeTrackerOptions);
    }
    /**
     * Create a new `StorageLibraryChangeTrackerOptions` instance.
     */
    static create() {
        return new StorageLibraryChangeTrackerOptions(_IActivationFactory.method(6).invoke(DynWinRtValue.activationFactory('Windows.Storage.StorageLibraryChangeTrackerOptions'), []));
    }
    get trackChangeDetails() {
        return _IStorageLibraryChangeTrackerOptions.method(6).invoke(this._obj, []).toBool();
    }
    set trackChangeDetails(value) {
        _IStorageLibraryChangeTrackerOptions.method(7).invoke(this._obj, [DynWinRtValue.boolValue(value)]);
    }
}
