// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { StorePackageLicense } from './StorePackageLicense.js';

const IID_IStoreAcquireLicenseResult = WinGuid.parse('fbd7946d-f040-4cb3-9a39-29bcecdbe22d');

const _IStoreAcquireLicenseResult = DynWinRtType.registerInterface(
    "IStoreAcquireLicenseResult", IID_IStoreAcquireLicenseResult)
    .addMethod("get_StorePackageLicense", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Services.Store.StorePackageLicense', WinGuid.parse('0c465714-14e1-4973-bd14-f77724271e99'))))
    .addMethod("get_ExtendedError", new DynWinRtMethodSig().addOut(DynWinRtType.hresult()));

export class StoreAcquireLicenseResult {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IStoreAcquireLicenseResult);
    }
    get storePackageLicense() {
        return new StorePackageLicense(_IStoreAcquireLicenseResult.method(6).invoke(this._obj, []));
    }
    get extendedError() {
        return _IStoreAcquireLicenseResult.method(7).invoke(this._obj, []).toNumber();
    }
}
