// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';

const IID_IStorePrice = WinGuid.parse('55ba94c4-15f1-407c-8f06-006380f4df0b');
const IID_IStorePrice2 = WinGuid.parse('f711573c-40e6-5641-b063-f1df42b2b12a');

const _IStorePrice = DynWinRtType.registerInterface(
    "IStorePrice", IID_IStorePrice)
    .addMethod("get_FormattedBasePrice", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_FormattedPrice", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_IsOnSale", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_SaleEndDate", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()])))
    .addMethod("get_CurrencyCode", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_FormattedRecurrencePrice", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

const _IStorePrice2 = DynWinRtType.registerInterface(
    "IStorePrice2", IID_IStorePrice2)
    .addMethod("get_UnformattedBasePrice", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_UnformattedPrice", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_UnformattedRecurrencePrice", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

export function unpackDateTime(v) {
    const s = v.asStruct();
    return { universalTime: s.getI64(0) };
}
const _unpackDateTime = unpackDateTime;
export const DateTime_Type = DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()]);
const _DateTime_Type = DateTime_Type;
export function packDateTime(v) {
    const s = DynWinRtStruct.create(DateTime_Type);
    s.setI64(0, v.universalTime);
    return s;
}
const _packDateTime = packDateTime;

export class StorePrice {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IStorePrice);
    }
    get formattedBasePrice() {
        return _IStorePrice.method(6).invoke(this._obj, []).toString();
    }
    get formattedPrice() {
        return _IStorePrice.method(7).invoke(this._obj, []).toString();
    }
    get isOnSale() {
        return _IStorePrice.method(8).invoke(this._obj, []).toBool();
    }
    get saleEndDate() {
        return _unpackDateTime(_IStorePrice.method(9).invoke(this._obj, []));
    }
    get currencyCode() {
        return _IStorePrice.method(10).invoke(this._obj, []).toString();
    }
    get formattedRecurrencePrice() {
        return _IStorePrice.method(11).invoke(this._obj, []).toString();
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
    get unformattedBasePrice() {
        return _IStorePrice2.method(6).invoke(this._obj.cast(IID_IStorePrice2), []).toString();
    }
    get unformattedPrice() {
        return _IStorePrice2.method(7).invoke(this._obj.cast(IID_IStorePrice2), []).toString();
    }
    get unformattedRecurrencePrice() {
        return _IStorePrice2.method(8).invoke(this._obj.cast(IID_IStorePrice2), []).toString();
    }
}

export class IStorePrice2 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorePrice2(obj.cast(IID_IStorePrice2));
    }

    get unformattedBasePrice() {
        return _IStorePrice2.method(6).invoke(this._obj, []).toString();
    }

    get unformattedPrice() {
        return _IStorePrice2.method(7).invoke(this._obj, []).toString();
    }

    get unformattedRecurrencePrice() {
        return _IStorePrice2.method(8).invoke(this._obj, []).toString();
    }
}
