// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { StoreConsumableStatus } from './StoreConsumableStatus.js';

const IID_IStoreConsumableResult = WinGuid.parse('ea5dab72-6a00-4052-be5b-bfdab4433352');

const _IStoreConsumableResult = DynWinRtType.registerInterface(
    "IStoreConsumableResult", IID_IStoreConsumableResult)
    .addMethod("get_Status", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Services.Store.StoreConsumableStatus', ['Succeeded', 'InsufficentQuantity', 'NetworkError', 'ServerError'], [0, 1, 2, 3])))
    .addMethod("get_TrackingId", new DynWinRtMethodSig().addOut(DynWinRtType.guidType()))
    .addMethod("get_BalanceRemaining", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_ExtendedError", new DynWinRtMethodSig().addOut(DynWinRtType.hresult()));

export class StoreConsumableResult {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IStoreConsumableResult);
    }
    get status() {
        return _IStoreConsumableResult.method(6).invoke(this._obj, []).toNumber();
    }
    get trackingId() {
        return _IStoreConsumableResult.method(7).invoke(this._obj, []).toString();
    }
    get balanceRemaining() {
        return _IStoreConsumableResult.method(8).invoke(this._obj, []).toNumber();
    }
    get extendedError() {
        return _IStoreConsumableResult.method(9).invoke(this._obj, []).toNumber();
    }
}
