// Generated by dynwinrt-codegen — do not edit
import { StorePackageLicense } from './StorePackageLicense.js';

export declare class StoreAcquireLicenseResult {
    private constructor();
    get storePackageLicense(): StorePackageLicense;
    get extendedError(): number;
}
