// Generated by dynwinrt-codegen — do not edit
import { StoreDurationUnit } from './StoreDurationUnit.js';

export declare class StoreSubscriptionInfo {
    private constructor();
    get billingPeriod(): number;
    get billingPeriodUnit(): StoreDurationUnit;
    get hasTrialPeriod(): boolean;
    get trialPeriod(): number;
    get trialPeriodUnit(): StoreDurationUnit;
}
