// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IVectorView_StorageLibraryChange } from './IVectorView_StorageLibraryChange.js';
import { StorageLibraryChange } from './StorageLibraryChange.js';

const IID_IStorageLibraryChangeReader = WinGuid.parse('f205bc83-fca2-41f9-8954-ee2e991eb96f');
const IID_IStorageLibraryChangeReader2 = WinGuid.parse('abf4868b-fbcc-4a4f-999e-e7ab7c646dbe');

const _IStorageLibraryChangeReader = DynWinRtType.registerInterface(
    "IStorageLibraryChangeReader", IID_IStorageLibraryChangeReader)
    .addMethod("ReadBatchAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageLibraryChange', WinGuid.parse('00980b23-2be2-4909-aa48-159f5203a51e'))]))))
    .addMethod("AcceptChangesAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncAction()));

const _IStorageLibraryChangeReader2 = DynWinRtType.registerInterface(
    "IStorageLibraryChangeReader2", IID_IStorageLibraryChangeReader2)
    .addMethod("GetLastChangeId", new DynWinRtMethodSig().addOut(DynWinRtType.u64()));

export class StorageLibraryChangeReader {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IStorageLibraryChangeReader);
    }
    async readBatchAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageLibraryChangeReader.method(6).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_StorageLibraryChange(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async acceptChangesAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageLibraryChangeReader.method(7).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            await _op.toPromise();
            return;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
    getLastChangeId() {
        return _IStorageLibraryChangeReader2.method(6).invoke(this._obj.cast(IID_IStorageLibraryChangeReader2), []).toI64();
    }
}

export class IStorageLibraryChangeReader2 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageLibraryChangeReader2(obj.cast(IID_IStorageLibraryChangeReader2));
    }

    getLastChangeId() {
        return _IStorageLibraryChangeReader2.method(6).invoke(this._obj, []).toI64();
    }
}
