// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtValue, DynWinRtStruct } from '@microsoft/dynwinrt';
import { IIterable_StorePackageUpdate } from './IIterable_StorePackageUpdate.js';
import { IIterable_StoreQueueItem } from './IIterable_StoreQueueItem.js';
import { IIterable_String } from './IIterable_String.js';
import { IVectorView_StorePackageUpdate } from './IVectorView_StorePackageUpdate.js';
import { IVectorView_StoreQueueItem } from './IVectorView_StoreQueueItem.js';
import { Package } from './Package.js';
import { StoreAcquireLicenseResult } from './StoreAcquireLicenseResult.js';
import { StoreAppLicense } from './StoreAppLicense.js';
import { StoreCanAcquireLicenseResult } from './StoreCanAcquireLicenseResult.js';
import { StoreConsumableResult } from './StoreConsumableResult.js';
import { StorePackageInstallOptions } from './StorePackageInstallOptions.js';
import { StorePackageUpdate } from './StorePackageUpdate.js';
import { StorePackageUpdateResult } from './StorePackageUpdateResult.js';
import { StoreProductOptions } from './StoreProductOptions.js';
import { StoreProductPagedQueryResult } from './StoreProductPagedQueryResult.js';
import { StoreProductQueryResult } from './StoreProductQueryResult.js';
import { StoreProductResult } from './StoreProductResult.js';
import { StorePurchaseProperties } from './StorePurchaseProperties.js';
import { StorePurchaseResult } from './StorePurchaseResult.js';
import { StoreQueueItem } from './StoreQueueItem.js';
import { StoreRateAndReviewResult } from './StoreRateAndReviewResult.js';
import { StoreUninstallStorePackageResult } from './StoreUninstallStorePackageResult.js';
import { User } from './User.js';

/**
 * A WinRT async operation that supports progress reporting and cancellation.
 *
 * - `await op` — wait for the final result
 * - `op.progress(cb)` — receive incremental progress updates (chainable)
 * - `op.cancel()` — cancel the underlying WinRT operation
 */
type WinRTAsyncWithProgress<T, P = unknown> = Promise<T> & {
    /** Register a callback for progress updates. Returns `this` for chaining. */
    progress(cb: (value: P) => void): WinRTAsyncWithProgress<T, P>;
    /** Get the underlying Promise (equivalent to awaiting directly). */
    toPromise(): Promise<T>;
    /** Cancel the underlying WinRT async operation. */
    cancel(): void;
};

export interface EventRegistrationToken {
    value: bigint;
}
/** Convert a WinRT struct value into a `EventRegistrationToken` object. */
export declare function unpackEventRegistrationToken(v: DynWinRtValue): EventRegistrationToken;
export declare const EventRegistrationToken_Type: DynWinRtType;
/** Convert a `EventRegistrationToken` object into a WinRT struct value. */
export declare function packEventRegistrationToken(v: EventRegistrationToken): DynWinRtStruct;

export interface StorePackageUpdateStatus {
    packageFamilyName: string;
    packageDownloadSizeInBytes: bigint;
    packageBytesDownloaded: bigint;
    packageDownloadProgress: number;
    totalDownloadProgress: number;
    packageUpdateState: number;
}
/** Convert a WinRT struct value into a `StorePackageUpdateStatus` object. */
export declare function unpackStorePackageUpdateStatus(v: DynWinRtValue): StorePackageUpdateStatus;
export declare const StorePackageUpdateStatus_Type: DynWinRtType;
/** Convert a `StorePackageUpdateStatus` object into a WinRT struct value. */
export declare function packStorePackageUpdateStatus(v: StorePackageUpdateStatus): DynWinRtStruct;

export declare class StoreContext {
    private constructor();
    static getDefault(): StoreContext;
    static getForUser(user: User): StoreContext;
    get user(): User;
    /** Register a handler for the `OfflineLicensesChanged` event. Call the returned function to unsubscribe. */
    onOfflineLicensesChanged(callback: (sender: StoreContext, args: unknown) => void): () => void;
    /** Like `onOfflineLicensesChanged` but automatically unsubscribes after the first invocation. */
    onceOfflineLicensesChanged(callback: (sender: StoreContext, args: unknown) => void): () => void;
    /** Unsubscribe from the `OfflineLicensesChanged` event using a raw registration token. */
    offOfflineLicensesChanged(token: unknown): void;
    getCustomerPurchaseIdAsync(serviceTicket: string, publisherUserId: string, signal?: AbortSignal): Promise<string>;
    getCustomerCollectionsIdAsync(serviceTicket: string, publisherUserId: string, signal?: AbortSignal): Promise<string>;
    getAppLicenseAsync(signal?: AbortSignal): Promise<StoreAppLicense>;
    getStoreProductForCurrentAppAsync(signal?: AbortSignal): Promise<StoreProductResult>;
    getStoreProductsAsync(productKinds: IIterable_String | string[], storeIds: IIterable_String | string[], signal?: AbortSignal): Promise<StoreProductQueryResult>;
    getAssociatedStoreProductsAsync(productKinds: IIterable_String | string[], signal?: AbortSignal): Promise<StoreProductQueryResult>;
    getAssociatedStoreProductsWithPagingAsync(productKinds: IIterable_String | string[], maxItemsToRetrievePerPage: number, signal?: AbortSignal): Promise<StoreProductPagedQueryResult>;
    getUserCollectionAsync(productKinds: IIterable_String | string[], signal?: AbortSignal): Promise<StoreProductQueryResult>;
    getUserCollectionWithPagingAsync(productKinds: IIterable_String | string[], maxItemsToRetrievePerPage: number, signal?: AbortSignal): Promise<StoreProductPagedQueryResult>;
    reportConsumableFulfillmentAsync(productStoreId: string, quantity: number, trackingId: string, signal?: AbortSignal): Promise<StoreConsumableResult>;
    getConsumableBalanceRemainingAsync(productStoreId: string, signal?: AbortSignal): Promise<StoreConsumableResult>;
    acquireStoreLicenseForOptionalPackageAsync(optionalPackage: Package, signal?: AbortSignal): Promise<StoreAcquireLicenseResult>;
    requestPurchaseAsync(storeId: string, signal?: AbortSignal): Promise<StorePurchaseResult>;
    requestPurchaseAsync(storeId: string, storePurchaseProperties: StorePurchaseProperties, signal?: AbortSignal): Promise<StorePurchaseResult>;
    getAppAndOptionalStorePackageUpdatesAsync(signal?: AbortSignal): Promise<IVectorView_StorePackageUpdate>;
    requestDownloadStorePackageUpdatesAsync(storePackageUpdates: IIterable_StorePackageUpdate | StorePackageUpdate[], signal?: AbortSignal): WinRTAsyncWithProgress<StorePackageUpdateResult, StorePackageUpdateStatus>;
    requestDownloadAndInstallStorePackageUpdatesAsync(storePackageUpdates: IIterable_StorePackageUpdate | StorePackageUpdate[], signal?: AbortSignal): WinRTAsyncWithProgress<StorePackageUpdateResult, StorePackageUpdateStatus>;
    requestDownloadAndInstallStorePackagesAsync(storeIds: IIterable_String | string[], signal?: AbortSignal): WinRTAsyncWithProgress<StorePackageUpdateResult, StorePackageUpdateStatus>;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
    findStoreProductForPackageAsync(productKinds: IIterable_String | string[], package_: Package, signal?: AbortSignal): Promise<StoreProductResult>;
    get canSilentlyDownloadStorePackageUpdates(): boolean;
    trySilentDownloadStorePackageUpdatesAsync(storePackageUpdates: IIterable_StorePackageUpdate | StorePackageUpdate[], signal?: AbortSignal): WinRTAsyncWithProgress<StorePackageUpdateResult, StorePackageUpdateStatus>;
    trySilentDownloadAndInstallStorePackageUpdatesAsync(storePackageUpdates: IIterable_StorePackageUpdate | StorePackageUpdate[], signal?: AbortSignal): WinRTAsyncWithProgress<StorePackageUpdateResult, StorePackageUpdateStatus>;
    canAcquireStoreLicenseForOptionalPackageAsync(optionalPackage: Package, signal?: AbortSignal): Promise<StoreCanAcquireLicenseResult>;
    canAcquireStoreLicenseAsync(productStoreId: string, signal?: AbortSignal): Promise<StoreCanAcquireLicenseResult>;
    getAssociatedStoreQueueItemsAsync(signal?: AbortSignal): Promise<IVectorView_StoreQueueItem>;
    getStoreQueueItemsAsync(storeIds: IIterable_String | string[], signal?: AbortSignal): Promise<IVectorView_StoreQueueItem>;
    downloadAndInstallStorePackagesAsync(storeIds: IIterable_String | string[], signal?: AbortSignal): WinRTAsyncWithProgress<StorePackageUpdateResult, StorePackageUpdateStatus>;
    requestUninstallStorePackageAsync(package_: Package, signal?: AbortSignal): Promise<StoreUninstallStorePackageResult>;
    requestUninstallStorePackageByStoreIdAsync(storeId: string, signal?: AbortSignal): Promise<StoreUninstallStorePackageResult>;
    uninstallStorePackageAsync(package_: Package, signal?: AbortSignal): Promise<StoreUninstallStorePackageResult>;
    uninstallStorePackageByStoreIdAsync(storeId: string, signal?: AbortSignal): Promise<StoreUninstallStorePackageResult>;
    requestRateAndReviewAppAsync(signal?: AbortSignal): Promise<StoreRateAndReviewResult>;
    setInstallOrderForAssociatedStoreQueueItemsAsync(items: IIterable_StoreQueueItem | StoreQueueItem[], signal?: AbortSignal): Promise<IVectorView_StoreQueueItem>;
    getUserPurchaseHistoryAsync(productKinds: IIterable_String | string[], signal?: AbortSignal): Promise<StoreProductQueryResult>;
    getAssociatedStoreProductsByInAppOfferTokenAsync(inAppOfferTokens: IIterable_String | string[], signal?: AbortSignal): Promise<StoreProductQueryResult>;
    requestPurchaseByInAppOfferTokenAsync(inAppOfferToken: string, signal?: AbortSignal): Promise<StorePurchaseResult>;
}

export declare class IStoreContext2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStoreContext2;

    findStoreProductForPackageAsync(productKinds: IIterable_String | string[], package_: Package, signal?: AbortSignal): Promise<StoreProductResult>;
}

export declare class IStoreContext3 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStoreContext3;

    get canSilentlyDownloadStorePackageUpdates(): boolean;

    trySilentDownloadStorePackageUpdatesAsync(storePackageUpdates: IIterable_StorePackageUpdate | StorePackageUpdate[], signal?: AbortSignal): WinRTAsyncWithProgress<StorePackageUpdateResult, StorePackageUpdateStatus>;

    trySilentDownloadAndInstallStorePackageUpdatesAsync(storePackageUpdates: IIterable_StorePackageUpdate | StorePackageUpdate[], signal?: AbortSignal): WinRTAsyncWithProgress<StorePackageUpdateResult, StorePackageUpdateStatus>;

    canAcquireStoreLicenseForOptionalPackageAsync(optionalPackage: Package, signal?: AbortSignal): Promise<StoreCanAcquireLicenseResult>;

    canAcquireStoreLicenseAsync(productStoreId: string, signal?: AbortSignal): Promise<StoreCanAcquireLicenseResult>;

    getStoreProductsWithOptionsAsync(productKinds: IIterable_String | string[], storeIds: IIterable_String | string[], storeProductOptions: StoreProductOptions, signal?: AbortSignal): Promise<StoreProductQueryResult>;

    getAssociatedStoreQueueItemsAsync(signal?: AbortSignal): Promise<IVectorView_StoreQueueItem>;

    getStoreQueueItemsAsync(storeIds: IIterable_String | string[], signal?: AbortSignal): Promise<IVectorView_StoreQueueItem>;

    requestDownloadAndInstallStorePackagesWithInstallOptionsAsync(storeIds: IIterable_String | string[], storePackageInstallOptions: StorePackageInstallOptions, signal?: AbortSignal): WinRTAsyncWithProgress<StorePackageUpdateResult, StorePackageUpdateStatus>;

    downloadAndInstallStorePackagesAsync(storeIds: IIterable_String | string[], signal?: AbortSignal): WinRTAsyncWithProgress<StorePackageUpdateResult, StorePackageUpdateStatus>;

    requestUninstallStorePackageAsync(package_: Package, signal?: AbortSignal): Promise<StoreUninstallStorePackageResult>;

    requestUninstallStorePackageByStoreIdAsync(storeId: string, signal?: AbortSignal): Promise<StoreUninstallStorePackageResult>;

    uninstallStorePackageAsync(package_: Package, signal?: AbortSignal): Promise<StoreUninstallStorePackageResult>;

    uninstallStorePackageByStoreIdAsync(storeId: string, signal?: AbortSignal): Promise<StoreUninstallStorePackageResult>;
}

export declare class IStoreContext4 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStoreContext4;

    requestRateAndReviewAppAsync(signal?: AbortSignal): Promise<StoreRateAndReviewResult>;

    setInstallOrderForAssociatedStoreQueueItemsAsync(items: IIterable_StoreQueueItem | StoreQueueItem[], signal?: AbortSignal): Promise<IVectorView_StoreQueueItem>;
}

export declare class IStoreContext5 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStoreContext5;

    getUserPurchaseHistoryAsync(productKinds: IIterable_String | string[], signal?: AbortSignal): Promise<StoreProductQueryResult>;

    getAssociatedStoreProductsByInAppOfferTokenAsync(inAppOfferTokens: IIterable_String | string[], signal?: AbortSignal): Promise<StoreProductQueryResult>;

    requestPurchaseByInAppOfferTokenAsync(inAppOfferToken: string, signal?: AbortSignal): Promise<StorePurchaseResult>;
}
