// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { StorePrice } from './StorePrice.js';
import { StorePurchaseProperties } from './StorePurchaseProperties.js';
import { StorePurchaseResult } from './StorePurchaseResult.js';
const _unwrap = (x) => x?._obj ?? x;

const IID_IStoreAvailability = WinGuid.parse('fa060325-0ffd-4493-ad43-f1f9918f69fa');

const _IStoreAvailability = DynWinRtType.registerInterface(
    "IStoreAvailability", IID_IStoreAvailability)
    .addMethod("get_StoreId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_EndDate", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()])))
    .addMethod("get_Price", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Services.Store.StorePrice', WinGuid.parse('55ba94c4-15f1-407c-8f06-006380f4df0b'))))
    .addMethod("get_ExtendedJsonData", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("RequestPurchaseAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Services.Store.StorePurchaseResult', WinGuid.parse('add28552-f96a-463d-a7bb-c20b4fca6952')))))
    .addMethod("RequestPurchaseWithPurchasePropertiesAsync", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Services.Store.StorePurchaseProperties', WinGuid.parse('836278f3-ff87-4364-a5b4-fd2153ebe43b'))).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Services.Store.StorePurchaseResult', WinGuid.parse('add28552-f96a-463d-a7bb-c20b4fca6952')))));

export function unpackDateTime(v) {
    const s = v.asStruct();
    return { universalTime: s.getI64(0) };
}
const _unpackDateTime = unpackDateTime;
export const DateTime_Type = DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()]);
const _DateTime_Type = DateTime_Type;
export function packDateTime(v) {
    const s = DynWinRtStruct.create(DateTime_Type);
    s.setI64(0, v.universalTime);
    return s;
}
const _packDateTime = packDateTime;

export class StoreAvailability {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IStoreAvailability);
    }
    get storeId() {
        return _IStoreAvailability.method(6).invoke(this._obj, []).toString();
    }
    get endDate() {
        return _unpackDateTime(_IStoreAvailability.method(7).invoke(this._obj, []));
    }
    get price() {
        return new StorePrice(_IStoreAvailability.method(8).invoke(this._obj, []));
    }
    get extendedJsonData() {
        return _IStoreAvailability.method(9).invoke(this._obj, []).toString();
    }
    async _requestPurchaseAsync_1(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStoreAvailability.method(10).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorePurchaseResult(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _requestPurchaseAsync_2(storePurchaseProperties, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStoreAvailability.method(11).invoke(this._obj, [_unwrap(storePurchaseProperties)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorePurchaseResult(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    requestPurchaseAsync(...args) {
        if (args.length >= 1 && args[0] !== undefined && !(args[0] instanceof AbortSignal)) {
            return this._requestPurchaseAsync_2(args[0], args[1]);
        }
        return this._requestPurchaseAsync_1(args[0]);
    }
}
