// Generated by dynwinrt-codegen — do not edit
export type StoreQueueItemExtendedState = (typeof StoreQueueItemExtendedState)[keyof typeof StoreQueueItemExtendedState];
export declare const StoreQueueItemExtendedState: {
    readonly ActivePending: 0;
    readonly ActiveStarting: 1;
    readonly ActiveAcquiringLicense: 2;
    readonly ActiveDownloading: 3;
    readonly ActiveRestoringData: 4;
    readonly ActiveInstalling: 5;
    readonly Completed: 6;
    readonly Canceled: 7;
    readonly Paused: 8;
    readonly Error: 9;
    readonly PausedPackagesInUse: 10;
    readonly PausedLowBattery: 11;
    readonly PausedWiFiRecommended: 12;
    readonly PausedWiFiRequired: 13;
    readonly PausedReadyToInstall: 14;
};
