// Generated by dynwinrt-codegen — do not edit
export declare class StorageLibraryChangeTrackerOptions {
    private constructor();
    /**
     * Create a new `StorageLibraryChangeTrackerOptions` instance.
     */
    static create(): StorageLibraryChangeTrackerOptions;
    get trackChangeDetails(): boolean;
    set trackChangeDetails(value: boolean);
}
