// Generated by dynwinrt-codegen — do not edit
import { StoreCanLicenseStatus } from './StoreCanLicenseStatus.js';

export declare class StoreCanAcquireLicenseResult {
    private constructor();
    get extendedError(): number;
    get licensableSku(): string;
    get status(): StoreCanLicenseStatus;
}
