// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';

const IID_IStorePurchaseProperties = WinGuid.parse('836278f3-ff87-4364-a5b4-fd2153ebe43b');
const IID_IStorePurchasePropertiesFactory = WinGuid.parse('a768f59e-fefd-489f-9a17-22a593e68b9d');

const _IStorePurchaseProperties = DynWinRtType.registerInterface(
    "IStorePurchaseProperties", IID_IStorePurchaseProperties)
    .addMethod("get_Name", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Name", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_ExtendedJsonData", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_ExtendedJsonData", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()));

const _IStorePurchasePropertiesFactory = DynWinRtType.registerInterface(
    "IStorePurchasePropertiesFactory", IID_IStorePurchasePropertiesFactory)
    .addMethod("Create", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.runtimeClass('Windows.Services.Store.StorePurchaseProperties', WinGuid.parse('836278f3-ff87-4364-a5b4-fd2153ebe43b'))));

const _IActivationFactory = DynWinRtType.registerInterface('IActivationFactory', WinGuid.parse('00000035-0000-0000-c000-000000000046'))
    .addMethod('ActivateInstance', new DynWinRtMethodSig().addOut(DynWinRtType.object()));

export class StorePurchaseProperties {
    _obj;
    static _f_IStorePurchasePropertiesFactory;
    static f_IStorePurchasePropertiesFactory() { return StorePurchaseProperties._f_IStorePurchasePropertiesFactory ??= DynWinRtValue.activationFactory('Windows.Services.Store.StorePurchaseProperties').cast(IID_IStorePurchasePropertiesFactory); }

    constructor(obj) {
        this._obj = obj.cast(IID_IStorePurchaseProperties);
    }
    /**
     * Create a new `StorePurchaseProperties` instance.
     */
    static createDefault() {
        return new StorePurchaseProperties(_IActivationFactory.method(6).invoke(DynWinRtValue.activationFactory('Windows.Services.Store.StorePurchaseProperties'), []));
    }
    static create(name) {
        return new StorePurchaseProperties(_IStorePurchasePropertiesFactory.method(6).invoke(StorePurchaseProperties.f_IStorePurchasePropertiesFactory(), [DynWinRtValue.hstring(name)]));
    }
    get name() {
        return _IStorePurchaseProperties.method(6).invoke(this._obj, []).toString();
    }
    set name(value) {
        _IStorePurchaseProperties.method(7).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }
    get extendedJsonData() {
        return _IStorePurchaseProperties.method(8).invoke(this._obj, []).toString();
    }
    set extendedJsonData(value) {
        _IStorePurchaseProperties.method(9).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }
}
