// Generated by dynwinrt-codegen — do not edit
export type StoreQueueItemKind = (typeof StoreQueueItemKind)[keyof typeof StoreQueueItemKind];
export declare const StoreQueueItemKind: {
    readonly Install: 0;
    readonly Update: 1;
    readonly Repair: 2;
};
