// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IMapView_String_StoreLicense } from './IMapView_String_StoreLicense.js';
import { StoreLicense } from './StoreLicense.js';

const IID_IStoreAppLicense = WinGuid.parse('f389f9de-73c0-45ce-9bab-b2fe3e5eafd3');
const IID_IStoreAppLicense2 = WinGuid.parse('b4666e91-4443-40b3-993f-28904435bdc6');

const _IStoreAppLicense = DynWinRtType.registerInterface(
    "IStoreAppLicense", IID_IStoreAppLicense)
    .addMethod("get_SkuStoreId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_IsActive", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_IsTrial", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_ExpirationDate", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()])))
    .addMethod("get_ExtendedJsonData", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_AddOnLicenses", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('e480ce40-a338-4ada-adcf-272272e48cb9'), [DynWinRtType.hstring(), DynWinRtType.runtimeClass('Windows.Services.Store.StoreLicense', WinGuid.parse('26dc9579-4c4f-4f30-bc89-649f60e36055'))])))
    .addMethod("get_TrialTimeRemaining", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.TimeSpan', [DynWinRtType.i64()])))
    .addMethod("get_IsTrialOwnedByThisUser", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_TrialUniqueId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

const _IStoreAppLicense2 = DynWinRtType.registerInterface(
    "IStoreAppLicense2", IID_IStoreAppLicense2)
    .addMethod("get_IsDiscLicense", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()));

export function unpackDateTime(v) {
    const s = v.asStruct();
    return { universalTime: s.getI64(0) };
}
const _unpackDateTime = unpackDateTime;
export const DateTime_Type = DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()]);
const _DateTime_Type = DateTime_Type;
export function packDateTime(v) {
    const s = DynWinRtStruct.create(DateTime_Type);
    s.setI64(0, v.universalTime);
    return s;
}
const _packDateTime = packDateTime;

export function unpackTimeSpan(v) {
    const s = v.asStruct();
    return { duration: s.getI64(0) };
}
const _unpackTimeSpan = unpackTimeSpan;
export const TimeSpan_Type = DynWinRtType.structType('Windows.Foundation.TimeSpan', [DynWinRtType.i64()]);
const _TimeSpan_Type = TimeSpan_Type;
export function packTimeSpan(v) {
    const s = DynWinRtStruct.create(TimeSpan_Type);
    s.setI64(0, v.duration);
    return s;
}
const _packTimeSpan = packTimeSpan;

export class StoreAppLicense {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IStoreAppLicense);
    }
    get skuStoreId() {
        return _IStoreAppLicense.method(6).invoke(this._obj, []).toString();
    }
    get isActive() {
        return _IStoreAppLicense.method(7).invoke(this._obj, []).toBool();
    }
    get isTrial() {
        return _IStoreAppLicense.method(8).invoke(this._obj, []).toBool();
    }
    get expirationDate() {
        return _unpackDateTime(_IStoreAppLicense.method(9).invoke(this._obj, []));
    }
    get extendedJsonData() {
        return _IStoreAppLicense.method(10).invoke(this._obj, []).toString();
    }
    get addOnLicenses() {
        return new IMapView_String_StoreLicense(_IStoreAppLicense.method(11).invoke(this._obj, []));
    }
    get trialTimeRemaining() {
        return _unpackTimeSpan(_IStoreAppLicense.method(12).invoke(this._obj, []));
    }
    get isTrialOwnedByThisUser() {
        return _IStoreAppLicense.method(13).invoke(this._obj, []).toBool();
    }
    get trialUniqueId() {
        return _IStoreAppLicense.method(14).invoke(this._obj, []).toString();
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
    get isDiscLicense() {
        return _IStoreAppLicense2.method(6).invoke(this._obj.cast(IID_IStoreAppLicense2), []).toBool();
    }
}

export class IStoreAppLicense2 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStoreAppLicense2(obj.cast(IID_IStoreAppLicense2));
    }

    get isDiscLicense() {
        return _IStoreAppLicense2.method(6).invoke(this._obj, []).toBool();
    }
}
