// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtValue, DynWinRtStruct } from '@microsoft/dynwinrt';

export interface DateTime {
    universalTime: bigint;
}
/** Convert a WinRT struct value into a `DateTime` object. */
export declare function unpackDateTime(v: DynWinRtValue): DateTime;
export declare const DateTime_Type: DynWinRtType;
/** Convert a `DateTime` object into a WinRT struct value. */
export declare function packDateTime(v: DateTime): DynWinRtStruct;

export interface TimeSpan {
    duration: bigint;
}
/** Convert a WinRT struct value into a `TimeSpan` object. */
export declare function unpackTimeSpan(v: DynWinRtValue): TimeSpan;
export declare const TimeSpan_Type: DynWinRtType;
/** Convert a `TimeSpan` object into a WinRT struct value. */
export declare function packTimeSpan(v: TimeSpan): DynWinRtStruct;

export declare class StoreCollectionData {
    private constructor();
    get isTrial(): boolean;
    get campaignId(): string;
    get developerOfferId(): string;
    get acquiredDate(): DateTime;
    get startDate(): DateTime;
    get endDate(): DateTime;
    get trialTimeRemaining(): TimeSpan;
    get extendedJsonData(): string;
}
