// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IIterable_IKeyValuePair_String_Object } from './IIterable_IKeyValuePair_String_Object.js';
import { IIterable_String } from './IIterable_String.js';
import { IKeyValuePair_String_Object } from './IKeyValuePair_String_Object.js';
import { IMap_String_Object } from './IMap_String_Object.js';
import { DocumentProperties } from './DocumentProperties.js';
import { ImageProperties } from './ImageProperties.js';
import { MusicProperties } from './MusicProperties.js';
import { VideoProperties } from './VideoProperties.js';
import { IID_IStorageItemExtraProperties, IStorageItemExtraProperties } from './IStorageItemExtraProperties.js';

const IID_IStorageItemContentProperties = WinGuid.parse('05294bad-bc38-48bf-85d7-770e0e2ae0ba');

const _IStorageItemContentProperties = DynWinRtType.registerInterface(
    "IStorageItemContentProperties", IID_IStorageItemContentProperties)
    .addMethod("GetMusicPropertiesAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.MusicProperties', WinGuid.parse('bc8aab62-66ec-419a-bc5d-ca65a4cb46da')))))
    .addMethod("GetVideoPropertiesAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.VideoProperties', WinGuid.parse('719ae507-68de-4db8-97de-49998c059f2f')))))
    .addMethod("GetImagePropertiesAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.ImageProperties', WinGuid.parse('523c9424-fcff-4275-afee-ecdb9ab47973')))))
    .addMethod("GetDocumentPropertiesAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.FileProperties.DocumentProperties', WinGuid.parse('7eab19bc-1821-4923-b4a9-0aea404d0070')))));

export class StorageItemContentProperties {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IStorageItemContentProperties);
    }
    async getMusicPropertiesAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemContentProperties.method(6).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new MusicProperties(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async getVideoPropertiesAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemContentProperties.method(7).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new VideoProperties(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async getImagePropertiesAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemContentProperties.method(8).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new ImageProperties(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async getDocumentPropertiesAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageItemContentProperties.method(9).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new DocumentProperties(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}
