// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { StorePurchaseStatus } from './StorePurchaseStatus.js';

const IID_IStorePurchaseResult = WinGuid.parse('add28552-f96a-463d-a7bb-c20b4fca6952');

const _IStorePurchaseResult = DynWinRtType.registerInterface(
    "IStorePurchaseResult", IID_IStorePurchaseResult)
    .addMethod("get_Status", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Services.Store.StorePurchaseStatus', ['Succeeded', 'AlreadyPurchased', 'NotPurchased', 'NetworkError', 'ServerError'], [0, 1, 2, 3, 4])))
    .addMethod("get_ExtendedError", new DynWinRtMethodSig().addOut(DynWinRtType.hresult()));

export class StorePurchaseResult {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IStorePurchaseResult);
    }
    get status() {
        return _IStorePurchaseResult.method(6).invoke(this._obj, []).toNumber();
    }
    get extendedError() {
        return _IStorePurchaseResult.method(7).invoke(this._obj, []).toNumber();
    }
}
