// Generated by dynwinrt-codegen — do not edit
import { IVectorView_StorageLibraryChange } from './IVectorView_StorageLibraryChange.js';

export declare class StorageLibraryChangeReader {
    private constructor();
    readBatchAsync(signal?: AbortSignal): Promise<IVectorView_StorageLibraryChange>;
    acceptChangesAsync(signal?: AbortSignal): Promise<void>;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
    getLastChangeId(): bigint;
}

export declare class IStorageLibraryChangeReader2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStorageLibraryChangeReader2;

    getLastChangeId(): bigint;
}
