// Generated by dynwinrt-codegen — do not edit
export type StorePurchaseStatus = (typeof StorePurchaseStatus)[keyof typeof StorePurchaseStatus];
export declare const StorePurchaseStatus: {
    readonly Succeeded: 0;
    readonly AlreadyPurchased: 1;
    readonly NotPurchased: 2;
    readonly NetworkError: 3;
    readonly ServerError: 4;
};
