// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { StorePackageUpdateState } from './StorePackageUpdateState.js';
import { StoreQueueItemExtendedState } from './StoreQueueItemExtendedState.js';
import { StoreQueueItemState } from './StoreQueueItemState.js';

const IID_IStoreQueueItemStatus = WinGuid.parse('9bd6796f-9cc3-4ec3-b2ef-7be433b30174');

const _IStoreQueueItemStatus = DynWinRtType.registerInterface(
    "IStoreQueueItemStatus", IID_IStoreQueueItemStatus)
    .addMethod("get_PackageInstallState", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Services.Store.StoreQueueItemState', ['Active', 'Completed', 'Canceled', 'Error', 'Paused'], [0, 1, 2, 3, 4])))
    .addMethod("get_PackageInstallExtendedState", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Services.Store.StoreQueueItemExtendedState', ['ActivePending', 'ActiveStarting', 'ActiveAcquiringLicense', 'ActiveDownloading', 'ActiveRestoringData', 'ActiveInstalling', 'Completed', 'Canceled', 'Paused', 'Error', 'PausedPackagesInUse', 'PausedLowBattery', 'PausedWiFiRecommended', 'PausedWiFiRequired', 'PausedReadyToInstall'], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])))
    .addMethod("get_UpdateStatus", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Services.Store.StorePackageUpdateStatus', [DynWinRtType.hstring(), DynWinRtType.u64(), DynWinRtType.u64(), DynWinRtType.f64(), DynWinRtType.f64(), DynWinRtType.enumType('Windows.Services.Store.StorePackageUpdateState', ['Pending', 'Downloading', 'Deploying', 'Completed', 'Canceled', 'OtherError', 'ErrorLowBattery', 'ErrorWiFiRecommended', 'ErrorWiFiRequired'], [0, 1, 2, 3, 4, 5, 6, 7, 8])])))
    .addMethod("get_ExtendedError", new DynWinRtMethodSig().addOut(DynWinRtType.hresult()));

export function unpackStorePackageUpdateStatus(v) {
    const s = v.asStruct();
    return { packageFamilyName: s.getHstring(0), packageDownloadSizeInBytes: s.getU64(1), packageBytesDownloaded: s.getU64(2), packageDownloadProgress: s.getF64(3), totalDownloadProgress: s.getF64(4), packageUpdateState: s.getI32(5) };
}
const _unpackStorePackageUpdateStatus = unpackStorePackageUpdateStatus;
export const StorePackageUpdateStatus_Type = DynWinRtType.structType('Windows.Services.Store.StorePackageUpdateStatus', [DynWinRtType.hstring(), DynWinRtType.u64(), DynWinRtType.u64(), DynWinRtType.f64(), DynWinRtType.f64(), DynWinRtType.enumType('Windows.Services.Store.StorePackageUpdateState', ['Pending', 'Downloading', 'Deploying', 'Completed', 'Canceled', 'OtherError', 'ErrorLowBattery', 'ErrorWiFiRecommended', 'ErrorWiFiRequired'], [0, 1, 2, 3, 4, 5, 6, 7, 8])]);
const _StorePackageUpdateStatus_Type = StorePackageUpdateStatus_Type;
export function packStorePackageUpdateStatus(v) {
    const s = DynWinRtStruct.create(StorePackageUpdateStatus_Type);
    s.setHstring(0, v.packageFamilyName);
    s.setU64(1, v.packageDownloadSizeInBytes);
    s.setU64(2, v.packageBytesDownloaded);
    s.setF64(3, v.packageDownloadProgress);
    s.setF64(4, v.totalDownloadProgress);
    s.setI32(5, v.packageUpdateState);
    return s;
}
const _packStorePackageUpdateStatus = packStorePackageUpdateStatus;

export class StoreQueueItemStatus {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IStoreQueueItemStatus);
    }
    get packageInstallState() {
        return _IStoreQueueItemStatus.method(6).invoke(this._obj, []).toNumber();
    }
    get packageInstallExtendedState() {
        return _IStoreQueueItemStatus.method(7).invoke(this._obj, []).toNumber();
    }
    get updateStatus() {
        return _unpackStorePackageUpdateStatus(_IStoreQueueItemStatus.method(8).invoke(this._obj, []));
    }
    get extendedError() {
        return _IStoreQueueItemStatus.method(9).invoke(this._obj, []).toNumber();
    }
}
