// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { HttpStatusCode } from './HttpStatusCode.js';

const IID_IStoreSendRequestResult = WinGuid.parse('c73abe60-8272-4502-8a69-6e75153a4299');
const IID_IStoreSendRequestResult2 = WinGuid.parse('2901296f-c0b0-49d0-8e8d-aa940af9c10b');

const _IStoreSendRequestResult = DynWinRtType.registerInterface(
    "IStoreSendRequestResult", IID_IStoreSendRequestResult)
    .addMethod("get_Response", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_ExtendedError", new DynWinRtMethodSig().addOut(DynWinRtType.hresult()));

const _IStoreSendRequestResult2 = DynWinRtType.registerInterface(
    "IStoreSendRequestResult2", IID_IStoreSendRequestResult2)
    .addMethod("get_HttpStatusCode", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Web.Http.HttpStatusCode', ['None', 'Continue', 'SwitchingProtocols', 'Processing', 'Ok', 'Created', 'Accepted', 'NonAuthoritativeInformation', 'NoContent', 'ResetContent', 'PartialContent', 'MultiStatus', 'AlreadyReported', 'IMUsed', 'MultipleChoices', 'MovedPermanently', 'Found', 'SeeOther', 'NotModified', 'UseProxy', 'TemporaryRedirect', 'PermanentRedirect', 'BadRequest', 'Unauthorized', 'PaymentRequired', 'Forbidden', 'NotFound', 'MethodNotAllowed', 'NotAcceptable', 'ProxyAuthenticationRequired', 'RequestTimeout', 'Conflict', 'Gone', 'LengthRequired', 'PreconditionFailed', 'RequestEntityTooLarge', 'RequestUriTooLong', 'UnsupportedMediaType', 'RequestedRangeNotSatisfiable', 'ExpectationFailed', 'UnprocessableEntity', 'Locked', 'FailedDependency', 'UpgradeRequired', 'PreconditionRequired', 'TooManyRequests', 'RequestHeaderFieldsTooLarge', 'InternalServerError', 'NotImplemented', 'BadGateway', 'ServiceUnavailable', 'GatewayTimeout', 'HttpVersionNotSupported', 'VariantAlsoNegotiates', 'InsufficientStorage', 'LoopDetected', 'NotExtended', 'NetworkAuthenticationRequired'], [0, 100, 101, 102, 200, 201, 202, 203, 204, 205, 206, 207, 208, 226, 300, 301, 302, 303, 304, 305, 307, 308, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 422, 423, 424, 426, 428, 429, 431, 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, 511])));

export class StoreSendRequestResult {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IStoreSendRequestResult);
    }
    get response() {
        return _IStoreSendRequestResult.method(6).invoke(this._obj, []).toString();
    }
    get extendedError() {
        return _IStoreSendRequestResult.method(7).invoke(this._obj, []).toNumber();
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
    get httpStatusCode() {
        return _IStoreSendRequestResult2.method(6).invoke(this._obj.cast(IID_IStoreSendRequestResult2), []).toNumber();
    }
}

export class IStoreSendRequestResult2 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStoreSendRequestResult2(obj.cast(IID_IStoreSendRequestResult2));
    }

    get httpStatusCode() {
        return _IStoreSendRequestResult2.method(6).invoke(this._obj, []).toNumber();
    }
}
