// Generated by dynwinrt-codegen — do not edit

export const StoreUninstallStorePackageStatus = Object.freeze({
    Succeeded: 0,
    CanceledByUser: 1,
    NetworkError: 2,
    UninstallNotApplicable: 3,
    Error: 4,
});
