// Generated by dynwinrt-codegen — do not edit
import { StorePurchaseStatus } from './StorePurchaseStatus.js';

export declare class StorePurchaseResult {
    private constructor();
    get status(): StorePurchaseStatus;
    get extendedError(): number;
}
