// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtValue, DynWinRtStruct } from '@microsoft/dynwinrt';
import { Package } from './Package.js';
import { IClosable } from './IClosable.js';

export interface EventRegistrationToken {
    value: bigint;
}
/** Convert a WinRT struct value into a `EventRegistrationToken` object. */
export declare function unpackEventRegistrationToken(v: DynWinRtValue): EventRegistrationToken;
export declare const EventRegistrationToken_Type: DynWinRtType;
/** Convert a `EventRegistrationToken` object into a WinRT struct value. */
export declare function packEventRegistrationToken(v: EventRegistrationToken): DynWinRtStruct;

export declare class StorePackageLicense {
    private constructor();
    /** Register a handler for the `LicenseLost` event. Call the returned function to unsubscribe. */
    onLicenseLost(callback: (sender: StorePackageLicense, args: unknown) => void): () => void;
    /** Like `onLicenseLost` but automatically unsubscribes after the first invocation. */
    onceLicenseLost(callback: (sender: StorePackageLicense, args: unknown) => void): () => void;
    /** Unsubscribe from the `LicenseLost` event using a raw registration token. */
    offLicenseLost(token: unknown): void;
    get package_(): Package;
    get isValid(): boolean;
    releaseLicense(): void;
    /** Release underlying WinRT resources (IClosable). */
    close(): void;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
}
