// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IMapView_String_StoreProduct } from './IMapView_String_StoreProduct.js';
import { StoreProduct } from './StoreProduct.js';

const IID_IStoreProductPagedQueryResult = WinGuid.parse('c92718c5-4dd5-4869-a462-ecc6872e43c5');

const _IStoreProductPagedQueryResult = DynWinRtType.registerInterface(
    "IStoreProductPagedQueryResult", IID_IStoreProductPagedQueryResult)
    .addMethod("get_Products", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('e480ce40-a338-4ada-adcf-272272e48cb9'), [DynWinRtType.hstring(), DynWinRtType.runtimeClass('Windows.Services.Store.StoreProduct', WinGuid.parse('320e2c52-d760-450a-a42b-67d1e901ac90'))])))
    .addMethod("get_HasMoreResults", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_ExtendedError", new DynWinRtMethodSig().addOut(DynWinRtType.hresult()))
    .addMethod("GetNextAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Services.Store.StoreProductPagedQueryResult', WinGuid.parse('c92718c5-4dd5-4869-a462-ecc6872e43c5')))));

export class StoreProductPagedQueryResult {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IStoreProductPagedQueryResult);
    }
    get products() {
        return new IMapView_String_StoreProduct(_IStoreProductPagedQueryResult.method(6).invoke(this._obj, []));
    }
    get hasMoreResults() {
        return _IStoreProductPagedQueryResult.method(7).invoke(this._obj, []).toBool();
    }
    get extendedError() {
        return _IStoreProductPagedQueryResult.method(8).invoke(this._obj, []).toNumber();
    }
    async getNextAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStoreProductPagedQueryResult.method(9).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StoreProductPagedQueryResult(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
}
