// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';

const IID_IStoreLicense = WinGuid.parse('26dc9579-4c4f-4f30-bc89-649f60e36055');

const _IStoreLicense = DynWinRtType.registerInterface(
    "IStoreLicense", IID_IStoreLicense)
    .addMethod("get_SkuStoreId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_IsActive", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
    .addMethod("get_ExpirationDate", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()])))
    .addMethod("get_ExtendedJsonData", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_InAppOfferToken", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

export function unpackDateTime(v) {
    const s = v.asStruct();
    return { universalTime: s.getI64(0) };
}
const _unpackDateTime = unpackDateTime;
export const DateTime_Type = DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()]);
const _DateTime_Type = DateTime_Type;
export function packDateTime(v) {
    const s = DynWinRtStruct.create(DateTime_Type);
    s.setI64(0, v.universalTime);
    return s;
}
const _packDateTime = packDateTime;

export class StoreLicense {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IStoreLicense);
    }
    get skuStoreId() {
        return _IStoreLicense.method(6).invoke(this._obj, []).toString();
    }
    get isActive() {
        return _IStoreLicense.method(7).invoke(this._obj, []).toBool();
    }
    get expirationDate() {
        return _unpackDateTime(_IStoreLicense.method(8).invoke(this._obj, []));
    }
    get extendedJsonData() {
        return _IStoreLicense.method(9).invoke(this._obj, []).toString();
    }
    get inAppOfferToken() {
        return _IStoreLicense.method(10).invoke(this._obj, []).toString();
    }
}
