// Generated by dynwinrt-codegen — do not edit
import { StoreConsumableStatus } from './StoreConsumableStatus.js';

export declare class StoreConsumableResult {
    private constructor();
    get status(): StoreConsumableStatus;
    get trackingId(): string;
    get balanceRemaining(): number;
    get extendedError(): number;
}
