// Generated by dynwinrt-codegen — do not edit

export const StorePurchaseStatus = Object.freeze({
    Succeeded: 0,
    AlreadyPurchased: 1,
    NotPurchased: 2,
    NetworkError: 3,
    ServerError: 4,
});
