// Generated by dynwinrt-codegen — do not edit
export declare class StorePurchaseProperties {
    private constructor();
    /**
     * Create a new `StorePurchaseProperties` instance.
     */
    static createDefault(): StorePurchaseProperties;
    static create(name: string): StorePurchaseProperties;
    get name(): string;
    set name(value: string);
    get extendedJsonData(): string;
    set extendedJsonData(value: string);
}
