// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtValue, DynWinRtStruct } from '@microsoft/dynwinrt';
import { IMap_String_IVectorView_TextSegment } from './IMap_String_IVectorView_TextSegment.js';
import { IVectorView_StorageFile } from './IVectorView_StorageFile.js';
import { StorageFile } from './StorageFile.js';

export interface EventRegistrationToken {
    value: bigint;
}
/** Convert a WinRT struct value into a `EventRegistrationToken` object. */
export declare function unpackEventRegistrationToken(v: DynWinRtValue): EventRegistrationToken;
export declare const EventRegistrationToken_Type: DynWinRtType;
/** Convert a `EventRegistrationToken` object into a WinRT struct value. */
export declare function packEventRegistrationToken(v: EventRegistrationToken): DynWinRtStruct;

export interface TextSegment {
    startPosition: number;
    length: number;
}
/** Convert a WinRT struct value into a `TextSegment` object. */
export declare function unpackTextSegment(v: DynWinRtValue): TextSegment;
export declare const TextSegment_Type: DynWinRtType;
/** Convert a `TextSegment` object into a WinRT struct value. */
export declare function packTextSegment(v: TextSegment): DynWinRtStruct;

export declare class StorageFileQueryResult {
    private constructor();
    getFilesAsync(startIndex: number, maxNumberOfItems: number, signal?: AbortSignal): Promise<IVectorView_StorageFile>;
    getFilesAsync(signal?: AbortSignal): Promise<IVectorView_StorageFile>;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
    getMatchingPropertiesWithRanges(file: StorageFile): IMap_String_IVectorView_TextSegment;
}

export declare class IStorageFileQueryResult2 {
    private constructor();

    /** @internal Cast a raw WinRT object to this interface. */
    static from(obj: any): IStorageFileQueryResult2;

    getMatchingPropertiesWithRanges(file: StorageFile): IMap_String_IVectorView_TextSegment;
}
