// Generated by dynwinrt-codegen — do not edit
export declare class StorePackageInstallOptions {
    private constructor();
    /**
     * Create a new `StorePackageInstallOptions` instance.
     */
    static create(): StorePackageInstallOptions;
    get allowForcedAppRestart(): boolean;
    set allowForcedAppRestart(value: boolean);
}
