// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IVectorView_IStorageItem } from './IVectorView_IStorageItem.js';
import { IVectorView_StorageFile } from './IVectorView_StorageFile.js';
import { IVectorView_StorageFolder } from './IVectorView_StorageFolder.js';
import { CreationCollisionOption } from './CreationCollisionOption.js';
import { FileAttributes } from './FileAttributes.js';
import { IID_IStorageItem, IStorageItem } from './IStorageItem.js';
import { NameCollisionOption } from './NameCollisionOption.js';
import { StorageDeleteOption } from './StorageDeleteOption.js';
import { StorageFile } from './StorageFile.js';
import { StorageItemTypes } from './StorageItemTypes.js';
import { StorageLibraryChangeTracker } from './StorageLibraryChangeTracker.js';
import { StorageProvider } from './StorageProvider.js';
import { BasicProperties } from './BasicProperties.js';
import { StorageItemContentProperties } from './StorageItemContentProperties.js';
import { StorageItemThumbnail } from './StorageItemThumbnail.js';
import { ThumbnailMode } from './ThumbnailMode.js';
import { ThumbnailOptions } from './ThumbnailOptions.js';
import { CommonFileQuery } from './CommonFileQuery.js';
import { CommonFolderQuery } from './CommonFolderQuery.js';
import { IndexedState } from './IndexedState.js';
import { QueryOptions } from './QueryOptions.js';
import { StorageFileQueryResult } from './StorageFileQueryResult.js';
import { StorageFolderQueryResult } from './StorageFolderQueryResult.js';
import { StorageItemQueryResult } from './StorageItemQueryResult.js';
import { User } from './User.js';
import { IID_IStorageItemProperties, IStorageItemProperties } from './IStorageItemProperties.js';
import { IID_IStorageItemProperties2, IStorageItemProperties2 } from './IStorageItemProperties2.js';
import { IID_IStorageItem2, IStorageItem2 } from './IStorageItem2.js';
import { IID_IStorageItemPropertiesWithProvider, IStorageItemPropertiesWithProvider } from './IStorageItemPropertiesWithProvider.js';
const _unwrap = (x) => x?._obj ?? x;

const IID_IStorageFolder = WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b');
const IID_IStorageFolderStatics = WinGuid.parse('08f327ff-85d5-48b9-aee9-28511e339f9f');
const IID_IStorageFolderStatics2 = WinGuid.parse('b4656dc3-71d2-467d-8b29-371f0f62bf6f');
const IID_IStorageFolderQueryOperations = WinGuid.parse('cb43ccc9-446b-4a4f-be97-757771be5203');
const IID_IStorageFolder2 = WinGuid.parse('e827e8b9-08d9-4a8e-a0ac-fe5ed3cbbbd3');
const IID_IStorageFolder3 = WinGuid.parse('9f617899-bde1-4124-aeb3-b06ad96f98d4');

const _IStorageFolder = DynWinRtType.registerInterface(
    "IStorageFolder", IID_IStorageFolder)
    .addMethod("CreateFileAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
    .addMethod("CreateFileAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.enumType('Windows.Storage.CreationCollisionOption', ['GenerateUniqueName', 'ReplaceExisting', 'FailIfExists', 'OpenIfExists'], [0, 1, 2, 3])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
    .addMethod("CreateFolderAsyncOverloadDefaultOptions", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b')))))
    .addMethod("CreateFolderAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addIn(DynWinRtType.enumType('Windows.Storage.CreationCollisionOption', ['GenerateUniqueName', 'ReplaceExisting', 'FailIfExists', 'OpenIfExists'], [0, 1, 2, 3])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b')))))
    .addMethod("GetFileAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea')))))
    .addMethod("GetFolderAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b')))))
    .addMethod("GetItemAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30')))))
    .addMethod("GetFilesAsyncOverloadDefaultOptionsStartAndCount", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))]))))
    .addMethod("GetFoldersAsyncOverloadDefaultOptionsStartAndCount", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))]))))
    .addMethod("GetItemsAsyncOverloadDefaultStartAndCount", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30'))]))));

const _IStorageFolderStatics = DynWinRtType.registerInterface(
    "IStorageFolderStatics", IID_IStorageFolderStatics)
    .addMethod("GetFolderFromPathAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b')))));

const _IStorageFolderStatics2 = DynWinRtType.registerInterface(
    "IStorageFolderStatics2", IID_IStorageFolderStatics2)
    .addMethod("GetFolderFromPathForUserAsync", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))).addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b')))));

const _IStorageFolderQueryOperations = DynWinRtType.registerInterface(
    "IStorageFolderQueryOperations", IID_IStorageFolderQueryOperations)
    .addMethod("GetIndexedStateAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.enumType('Windows.Storage.Search.IndexedState', ['Unknown', 'NotIndexed', 'PartiallyIndexed', 'FullyIndexed'], [0, 1, 2, 3]))))
    .addMethod("CreateFileQueryOverloadDefault", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFileQueryResult', WinGuid.parse('52fda447-2baa-412c-b29f-d4b1778efa1e'))))
    .addMethod("CreateFileQuery", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFileQuery', ['DefaultQuery', 'OrderByName', 'OrderByTitle', 'OrderByMusicProperties', 'OrderBySearchRank', 'OrderByDate'], [0, 1, 2, 3, 4, 5])).addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFileQueryResult', WinGuid.parse('52fda447-2baa-412c-b29f-d4b1778efa1e'))))
    .addMethod("CreateFileQueryWithOptions", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))).addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFileQueryResult', WinGuid.parse('52fda447-2baa-412c-b29f-d4b1778efa1e'))))
    .addMethod("CreateFolderQueryOverloadDefault", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFolderQueryResult', WinGuid.parse('6654c911-7d66-46fa-aecf-e4a4baa93ab8'))))
    .addMethod("CreateFolderQuery", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFolderQuery', ['DefaultQuery', 'GroupByYear', 'GroupByMonth', 'GroupByArtist', 'GroupByAlbum', 'GroupByAlbumArtist', 'GroupByComposer', 'GroupByGenre', 'GroupByPublishedYear', 'GroupByRating', 'GroupByTag', 'GroupByAuthor', 'GroupByType'], [0, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])).addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFolderQueryResult', WinGuid.parse('6654c911-7d66-46fa-aecf-e4a4baa93ab8'))))
    .addMethod("CreateFolderQueryWithOptions", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))).addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageFolderQueryResult', WinGuid.parse('6654c911-7d66-46fa-aecf-e4a4baa93ab8'))))
    .addMethod("CreateItemQuery", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageItemQueryResult', WinGuid.parse('e8948079-9d58-47b8-b2b2-41b07f4795f9'))))
    .addMethod("CreateItemQueryWithOptions", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))).addOut(DynWinRtType.runtimeClass('Windows.Storage.Search.StorageItemQueryResult', WinGuid.parse('e8948079-9d58-47b8-b2b2-41b07f4795f9'))))
    .addMethod("GetFilesAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFileQuery', ['DefaultQuery', 'OrderByName', 'OrderByTitle', 'OrderByMusicProperties', 'OrderBySearchRank', 'OrderByDate'], [0, 1, 2, 3, 4, 5])).addIn(DynWinRtType.u32()).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))]))))
    .addMethod("GetFilesAsyncOverloadDefaultStartAndCount", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFileQuery', ['DefaultQuery', 'OrderByName', 'OrderByTitle', 'OrderByMusicProperties', 'OrderBySearchRank', 'OrderByDate'], [0, 1, 2, 3, 4, 5])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFile', WinGuid.parse('fa3f6186-4214-428c-a64c-14c9ac7315ea'))]))))
    .addMethod("GetFoldersAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFolderQuery', ['DefaultQuery', 'GroupByYear', 'GroupByMonth', 'GroupByArtist', 'GroupByAlbum', 'GroupByAlbumArtist', 'GroupByComposer', 'GroupByGenre', 'GroupByPublishedYear', 'GroupByRating', 'GroupByTag', 'GroupByAuthor', 'GroupByType'], [0, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])).addIn(DynWinRtType.u32()).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))]))))
    .addMethod("GetFoldersAsyncOverloadDefaultStartAndCount", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFolderQuery', ['DefaultQuery', 'GroupByYear', 'GroupByMonth', 'GroupByArtist', 'GroupByAlbum', 'GroupByAlbumArtist', 'GroupByComposer', 'GroupByGenre', 'GroupByPublishedYear', 'GroupByRating', 'GroupByTag', 'GroupByAuthor', 'GroupByType'], [0, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.Storage.StorageFolder', WinGuid.parse('72d1cb78-b3ef-4f75-a80b-6fd9dae2944b'))]))))
    .addMethod("GetItemsAsync", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(DynWinRtType.u32()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30'))]))))
    .addMethod("AreQueryOptionsSupported", new DynWinRtMethodSig().addIn(DynWinRtType.runtimeClass('Windows.Storage.Search.QueryOptions', WinGuid.parse('1e5e46ee-0f45-4838-a8e9-d0479d446c30'))).addOut(DynWinRtType.boolType()))
    .addMethod("IsCommonFolderQuerySupported", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFolderQuery', ['DefaultQuery', 'GroupByYear', 'GroupByMonth', 'GroupByArtist', 'GroupByAlbum', 'GroupByAlbumArtist', 'GroupByComposer', 'GroupByGenre', 'GroupByPublishedYear', 'GroupByRating', 'GroupByTag', 'GroupByAuthor', 'GroupByType'], [0, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])).addOut(DynWinRtType.boolType()))
    .addMethod("IsCommonFileQuerySupported", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.Storage.Search.CommonFileQuery', ['DefaultQuery', 'OrderByName', 'OrderByTitle', 'OrderByMusicProperties', 'OrderBySearchRank', 'OrderByDate'], [0, 1, 2, 3, 4, 5])).addOut(DynWinRtType.boolType()));

const _IStorageFolder2 = DynWinRtType.registerInterface(
    "IStorageFolder2", IID_IStorageFolder2)
    .addMethod("TryGetItemAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('4207a996-ca2f-42f7-bde8-8b10457a7f30')))));

const _IStorageFolder3 = DynWinRtType.registerInterface(
    "IStorageFolder3", IID_IStorageFolder3)
    .addMethod("TryGetChangeTracker", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.Storage.StorageLibraryChangeTracker', WinGuid.parse('9e157316-6073-44f6-9681-7492d1286c90'))));

export function unpackDateTime(v) {
    const s = v.asStruct();
    return { universalTime: s.getI64(0) };
}
const _unpackDateTime = unpackDateTime;
export const DateTime_Type = DynWinRtType.structType('Windows.Foundation.DateTime', [DynWinRtType.i64()]);
const _DateTime_Type = DateTime_Type;
export function packDateTime(v) {
    const s = DynWinRtStruct.create(DateTime_Type);
    s.setI64(0, v.universalTime);
    return s;
}
const _packDateTime = packDateTime;

export class StorageFolder {
    _obj;
    static _s_IStorageFolderStatics;
    static _s_IStorageFolderStatics2;
    static s_IStorageFolderStatics() { return StorageFolder._s_IStorageFolderStatics ??= DynWinRtValue.activationFactory('Windows.Storage.StorageFolder').cast(IID_IStorageFolderStatics); }
    static s_IStorageFolderStatics2() { return StorageFolder._s_IStorageFolderStatics2 ??= DynWinRtValue.activationFactory('Windows.Storage.StorageFolder').cast(IID_IStorageFolderStatics2); }

    constructor(obj) {
        this._obj = obj.cast(IID_IStorageFolder);
    }
    static async getFolderFromPathAsync(path, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderStatics.method(6).invoke(StorageFolder.s_IStorageFolderStatics(), [DynWinRtValue.hstring(path)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorageFolder(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    static async getFolderFromPathForUserAsync(user, path, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderStatics2.method(6).invoke(StorageFolder.s_IStorageFolderStatics2(), [_unwrap(user), DynWinRtValue.hstring(path)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorageFolder(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _createFileAsync_1(desiredName, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(6).invoke(this._obj, [DynWinRtValue.hstring(desiredName)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorageFile(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _createFileAsync_2(desiredName, options, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(7).invoke(this._obj, [DynWinRtValue.hstring(desiredName), DynWinRtValue.i32(options)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorageFile(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `createFileAsync` with default options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    createFileAsync(...args) {
        if (args.length >= 2 && args[1] !== undefined && !(args[1] instanceof AbortSignal)) {
            return this._createFileAsync_2(args[0], args[1], args[2]);
        }
        return this._createFileAsync_1(args[0], args[1]);
    }
    async _createFolderAsync_1(desiredName, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(8).invoke(this._obj, [DynWinRtValue.hstring(desiredName)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorageFolder(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async _createFolderAsync_2(desiredName, options, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(9).invoke(this._obj, [DynWinRtValue.hstring(desiredName), DynWinRtValue.i32(options)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorageFolder(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `createFolderAsync` with default options.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    createFolderAsync(...args) {
        if (args.length >= 2 && args[1] !== undefined && !(args[1] instanceof AbortSignal)) {
            return this._createFolderAsync_2(args[0], args[1], args[2]);
        }
        return this._createFolderAsync_1(args[0], args[1]);
    }
    async getFileAsync(name, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(10).invoke(this._obj, [DynWinRtValue.hstring(name)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorageFile(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async getFolderAsync(name, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(11).invoke(this._obj, [DynWinRtValue.hstring(name)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new StorageFolder(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async getItemAsync(name, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(12).invoke(this._obj, [DynWinRtValue.hstring(name)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IStorageItem(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `getFilesAsync` with default options, start, count.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async getFilesAsync(query, startIndex, maxItemsToRetrieve, signal) {
        if (query !== undefined && !(query instanceof AbortSignal)) {
            return IStorageFolderQueryOperations.from(this._obj).getFilesAsync(query, startIndex, maxItemsToRetrieve, signal);
        }
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(13).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_StorageFile(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `getFoldersAsync` with default options, start, count.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async getFoldersAsync(query, startIndex, maxItemsToRetrieve, signal) {
        if (query !== undefined && !(query instanceof AbortSignal)) {
            return IStorageFolderQueryOperations.from(this._obj).getFoldersAsync(query, startIndex, maxItemsToRetrieve, signal);
        }
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(14).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_StorageFolder(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    /**
     * Overload of `getItemsAsync` with default start, count.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async getItemsAsync(startIndex, maxItemsToRetrieve, signal) {
        if (startIndex !== undefined && !(startIndex instanceof AbortSignal)) {
            return IStorageFolderQueryOperations.from(this._obj).getItemsAsync(startIndex, maxItemsToRetrieve, signal);
        }
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder.method(15).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_IStorageItem(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
    async getIndexedStateAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(6).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toNumber();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    _createFileQuery_1() {
        return new StorageFileQueryResult(_IStorageFolderQueryOperations.method(7).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), []));
    }
    _createFileQuery_2(query) {
        return new StorageFileQueryResult(_IStorageFolderQueryOperations.method(8).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), [DynWinRtValue.i32(query)]));
    }
    /**
     * Parameterless overload of `createFileQuery`.
     */
    createFileQuery(...args) {
        if (args.length >= 1 && args[0] !== undefined && !(args[0] instanceof AbortSignal)) {
            return this._createFileQuery_2(args[0]);
        }
        return this._createFileQuery_1();
    }
    createFileQueryWithOptions(queryOptions) {
        return new StorageFileQueryResult(_IStorageFolderQueryOperations.method(9).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), [_unwrap(queryOptions)]));
    }
    _createFolderQuery_1() {
        return new StorageFolderQueryResult(_IStorageFolderQueryOperations.method(10).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), []));
    }
    _createFolderQuery_2(query) {
        return new StorageFolderQueryResult(_IStorageFolderQueryOperations.method(11).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), [DynWinRtValue.i32(query)]));
    }
    /**
     * Parameterless overload of `createFolderQuery`.
     */
    createFolderQuery(...args) {
        if (args.length >= 1 && args[0] !== undefined && !(args[0] instanceof AbortSignal)) {
            return this._createFolderQuery_2(args[0]);
        }
        return this._createFolderQuery_1();
    }
    createFolderQueryWithOptions(queryOptions) {
        return new StorageFolderQueryResult(_IStorageFolderQueryOperations.method(12).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), [_unwrap(queryOptions)]));
    }
    createItemQuery() {
        return new StorageItemQueryResult(_IStorageFolderQueryOperations.method(13).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), []));
    }
    createItemQueryWithOptions(queryOptions) {
        return new StorageItemQueryResult(_IStorageFolderQueryOperations.method(14).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), [_unwrap(queryOptions)]));
    }
    areQueryOptionsSupported(queryOptions) {
        return _IStorageFolderQueryOperations.method(20).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), [_unwrap(queryOptions)]).toBool();
    }
    isCommonFolderQuerySupported(query) {
        return _IStorageFolderQueryOperations.method(21).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), [DynWinRtValue.i32(query)]).toBool();
    }
    isCommonFileQuerySupported(query) {
        return _IStorageFolderQueryOperations.method(22).invoke(this._obj.cast(IID_IStorageFolderQueryOperations), [DynWinRtValue.i32(query)]).toBool();
    }
    async tryGetItemAsync(name, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder2.method(6).invoke(this._obj.cast(IID_IStorageFolder2), [DynWinRtValue.hstring(name)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IStorageItem(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    tryGetChangeTracker() {
        return new StorageLibraryChangeTracker(_IStorageFolder3.method(6).invoke(this._obj.cast(IID_IStorageFolder3), []));
    }
}

export class IStorageFolderQueryOperations {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageFolderQueryOperations(obj.cast(IID_IStorageFolderQueryOperations));
    }

    async getIndexedStateAsync(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(6).invoke(this._obj, []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toNumber();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    /**
     * Parameterless overload of `createFileQuery`.
     */
    createFileQueryOverloadDefault() {
        return new StorageFileQueryResult(_IStorageFolderQueryOperations.method(7).invoke(this._obj, []));
    }

    createFileQuery(query) {
        return new StorageFileQueryResult(_IStorageFolderQueryOperations.method(8).invoke(this._obj, [DynWinRtValue.i32(query)]));
    }

    createFileQueryWithOptions(queryOptions) {
        return new StorageFileQueryResult(_IStorageFolderQueryOperations.method(9).invoke(this._obj, [_unwrap(queryOptions)]));
    }

    /**
     * Parameterless overload of `createFolderQuery`.
     */
    createFolderQueryOverloadDefault() {
        return new StorageFolderQueryResult(_IStorageFolderQueryOperations.method(10).invoke(this._obj, []));
    }

    createFolderQuery(query) {
        return new StorageFolderQueryResult(_IStorageFolderQueryOperations.method(11).invoke(this._obj, [DynWinRtValue.i32(query)]));
    }

    createFolderQueryWithOptions(queryOptions) {
        return new StorageFolderQueryResult(_IStorageFolderQueryOperations.method(12).invoke(this._obj, [_unwrap(queryOptions)]));
    }

    createItemQuery() {
        return new StorageItemQueryResult(_IStorageFolderQueryOperations.method(13).invoke(this._obj, []));
    }

    createItemQueryWithOptions(queryOptions) {
        return new StorageItemQueryResult(_IStorageFolderQueryOperations.method(14).invoke(this._obj, [_unwrap(queryOptions)]));
    }

    async getFilesAsync(query, startIndex, maxItemsToRetrieve, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(15).invoke(this._obj, [DynWinRtValue.i32(query), DynWinRtValue.u32(startIndex), DynWinRtValue.u32(maxItemsToRetrieve)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_StorageFile(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    /**
     * Overload of `getFilesAsync` with default start, count.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async getFilesAsyncOverloadDefaultStartAndCount(query, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(16).invoke(this._obj, [DynWinRtValue.i32(query)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_StorageFile(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    async getFoldersAsync(query, startIndex, maxItemsToRetrieve, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(17).invoke(this._obj, [DynWinRtValue.i32(query), DynWinRtValue.u32(startIndex), DynWinRtValue.u32(maxItemsToRetrieve)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_StorageFolder(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    /**
     * Overload of `getFoldersAsync` with default start, count.
     * @param signal Abort signal to cancel the underlying WinRT async operation.
     */
    async getFoldersAsyncOverloadDefaultStartAndCount(query, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(18).invoke(this._obj, [DynWinRtValue.i32(query)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_StorageFolder(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    async getItemsAsync(startIndex, maxItemsToRetrieve, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolderQueryOperations.method(19).invoke(this._obj, [DynWinRtValue.u32(startIndex), DynWinRtValue.u32(maxItemsToRetrieve)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_IStorageItem(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }

    areQueryOptionsSupported(queryOptions) {
        return _IStorageFolderQueryOperations.method(20).invoke(this._obj, [_unwrap(queryOptions)]).toBool();
    }

    isCommonFolderQuerySupported(query) {
        return _IStorageFolderQueryOperations.method(21).invoke(this._obj, [DynWinRtValue.i32(query)]).toBool();
    }

    isCommonFileQuerySupported(query) {
        return _IStorageFolderQueryOperations.method(22).invoke(this._obj, [DynWinRtValue.i32(query)]).toBool();
    }
}

export class IStorageFolder2 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageFolder2(obj.cast(IID_IStorageFolder2));
    }

    async tryGetItemAsync(name, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageFolder2.method(6).invoke(this._obj, [DynWinRtValue.hstring(name)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IStorageItem(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
}

export class IStorageFolder3 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageFolder3(obj.cast(IID_IStorageFolder3));
    }

    tryGetChangeTracker() {
        return new StorageLibraryChangeTracker(_IStorageFolder3.method(6).invoke(this._obj, []));
    }
}
