// Generated by dynwinrt-codegen — do not edit
import { IMapView_String_StoreProduct } from './IMapView_String_StoreProduct.js';

export declare class StoreProductQueryResult {
    private constructor();
    get products(): IMapView_String_StoreProduct;
    get extendedError(): number;
}
