// Generated by dynwinrt-codegen — do not edit
import { IRandomAccessStream } from './IRandomAccessStream.js';
import { IClosable } from './IClosable.js';

export declare class StorageStreamTransaction {
    private constructor();
    get stream(): IRandomAccessStream;
    commitAsync(signal?: AbortSignal): Promise<void>;
    /** Release underlying WinRT resources (IClosable). */
    close(): void;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
}
