// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';

const IID_IStorageProvider = WinGuid.parse('e705eed4-d478-47d6-ba46-1a8ebe114a20');
const IID_IStorageProvider2 = WinGuid.parse('010d1917-3404-414b-9fd7-cd44472eaa39');

const _IStorageProvider = DynWinRtType.registerInterface(
    "IStorageProvider", IID_IStorageProvider)
    .addMethod("get_Id", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_DisplayName", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()));

const _IStorageProvider2 = DynWinRtType.registerInterface(
    "IStorageProvider2", IID_IStorageProvider2)
    .addMethod("IsPropertySupportedForPartialFileAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.boolType())));

export class StorageProvider {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IStorageProvider);
    }
    get id() {
        return _IStorageProvider.method(6).invoke(this._obj, []).toString();
    }
    get displayName() {
        return _IStorageProvider.method(7).invoke(this._obj, []).toString();
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
    async isPropertySupportedForPartialFileAsync(propertyCanonicalName, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageProvider2.method(6).invoke(this._obj.cast(IID_IStorageProvider2), [DynWinRtValue.hstring(propertyCanonicalName)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toBool();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
}

export class IStorageProvider2 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IStorageProvider2(obj.cast(IID_IStorageProvider2));
    }

    async isPropertySupportedForPartialFileAsync(propertyCanonicalName, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IStorageProvider2.method(6).invoke(this._obj, [DynWinRtValue.hstring(propertyCanonicalName)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toBool();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
}
