// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, WinGuid } from '@microsoft/dynwinrt';

export const IID_TypedEventHandler_UserWatcher_UserChangedEventArgs = DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.runtimeClass('Windows.System.UserChangedEventArgs', WinGuid.parse('086459dc-18c6-48db-bc99-724fb9203ccc'))]).iid();
export const TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES = [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.runtimeClass('Windows.System.UserChangedEventArgs', WinGuid.parse('086459dc-18c6-48db-bc99-724fb9203ccc'))];
