// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, WinGuid } from '@microsoft/dynwinrt';

export const IID_TypedEventHandler_StorePackageLicense_Object = DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.Services.Store.StorePackageLicense', WinGuid.parse('0c465714-14e1-4973-bd14-f77724271e99')), DynWinRtType.object()]).iid();
export const TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES = [DynWinRtType.runtimeClass('Windows.Services.Store.StorePackageLicense', WinGuid.parse('0c465714-14e1-4973-bd14-f77724271e99')), DynWinRtType.object()];
