// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, WinGuid } from '@microsoft/dynwinrt';
import { StoreContext } from './StoreContext.js';

export type TypedEventHandler_StoreContext_Object = (sender: StoreContext, args: unknown) => void;
export declare const IID_TypedEventHandler_StoreContext_Object: WinGuid;
export declare const TypedEventHandler_StoreContext_Object_PARAM_TYPES: DynWinRtType[];
