// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, WinGuid } from '@microsoft/dynwinrt';
import { StorePackageLicense } from './StorePackageLicense.js';

export type TypedEventHandler_StorePackageLicense_Object = (sender: StorePackageLicense, args: unknown) => void;
export declare const IID_TypedEventHandler_StorePackageLicense_Object: WinGuid;
export declare const TypedEventHandler_StorePackageLicense_Object_PARAM_TYPES: DynWinRtType[];
