// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, WinGuid } from '@microsoft/dynwinrt';
import { StoreQueueItem } from './StoreQueueItem.js';

export type TypedEventHandler_StoreQueueItem_Object = (sender: StoreQueueItem, args: unknown) => void;
export declare const IID_TypedEventHandler_StoreQueueItem_Object: WinGuid;
export declare const TypedEventHandler_StoreQueueItem_Object_PARAM_TYPES: DynWinRtType[];
