// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IVectorView_String } from './IVectorView_String.js';
import { IVectorView_User } from './IVectorView_User.js';
import { IID_IPropertySet, IPropertySet } from './IPropertySet.js';
import { IID_IRandomAccessStreamReference, IRandomAccessStreamReference } from './IRandomAccessStreamReference.js';
import { UserAgeConsentGroup } from './UserAgeConsentGroup.js';
import { UserAgeConsentResult } from './UserAgeConsentResult.js';
import { UserAuthenticationStatus } from './UserAuthenticationStatus.js';
import { UserPictureSize } from './UserPictureSize.js';
import { UserType } from './UserType.js';
import { UserWatcher } from './UserWatcher.js';
const _unwrap = (x) => x?._obj ?? x;

const IID_IUser = WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b');
const IID_IUserStatics2 = WinGuid.parse('74a37e11-2eb5-4487-b0d5-2c6790e013e9');
const IID_IUserStatics = WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fdd');
const IID_IUser2 = WinGuid.parse('98ba5628-a6e3-518e-89d9-d3b2b1991a10');

const _IUser = DynWinRtType.registerInterface(
    "IUser", IID_IUser)
    .addMethod("get_NonRoamableId", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("get_AuthenticationStatus", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.System.UserAuthenticationStatus', ['Unauthenticated', 'LocallyAuthenticated', 'RemotelyAuthenticated'], [0, 1, 2])))
    .addMethod("get_Type", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.System.UserType', ['LocalUser', 'RemoteUser', 'LocalGuest', 'RemoteGuest', 'SystemManaged'], [0, 1, 2, 3, 4])))
    .addMethod("GetPropertyAsync", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.object())))
    .addMethod("GetPropertiesAsync", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.hstring()])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('8a43ed9f-f4e6-4421-acf9-1dab2986820c')))))
    .addMethod("GetPictureAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.System.UserPictureSize', ['Size64x64', 'Size208x208', 'Size424x424', 'Size1080x1080'], [0, 1, 2, 3])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.interface(WinGuid.parse('33ee3134-1dd6-4e3a-8067-d1c162e8642b')))));

const _IUserStatics2 = DynWinRtType.registerInterface(
    "IUserStatics2", IID_IUserStatics2)
    .addMethod("GetDefault", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))));

const _IUserStatics = DynWinRtType.registerInterface(
    "IUserStatics", IID_IUserStatics)
    .addMethod("CreateWatcher", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb'))))
    .addMethod("FindAllAsync", new DynWinRtMethodSig().addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))]))))
    .addMethod("FindAllAsyncByType", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.System.UserType', ['LocalUser', 'RemoteUser', 'LocalGuest', 'RemoteGuest', 'SystemManaged'], [0, 1, 2, 3, 4])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))]))))
    .addMethod("FindAllAsyncByTypeAndStatus", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.System.UserType', ['LocalUser', 'RemoteUser', 'LocalGuest', 'RemoteGuest', 'SystemManaged'], [0, 1, 2, 3, 4])).addIn(DynWinRtType.enumType('Windows.System.UserAuthenticationStatus', ['Unauthenticated', 'LocallyAuthenticated', 'RemotelyAuthenticated'], [0, 1, 2])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))]))))
    .addMethod("GetFromId", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()).addOut(DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))));

const _IUser2 = DynWinRtType.registerInterface(
    "IUser2", IID_IUser2)
    .addMethod("CheckUserAgeConsentGroupAsync", new DynWinRtMethodSig().addIn(DynWinRtType.enumType('Windows.System.UserAgeConsentGroup', ['Child', 'Minor', 'Adult'], [0, 1, 2])).addOut(DynWinRtType.iAsyncOperation(DynWinRtType.enumType('Windows.System.UserAgeConsentResult', ['NotEnforced', 'Included', 'NotIncluded', 'Unknown', 'Ambiguous'], [0, 1, 2, 3, 4]))));

export class User {
    _obj;
    static _s_IUserStatics2;
    static _s_IUserStatics;
    static s_IUserStatics2() { return User._s_IUserStatics2 ??= DynWinRtValue.activationFactory('Windows.System.User').cast(IID_IUserStatics2); }
    static s_IUserStatics() { return User._s_IUserStatics ??= DynWinRtValue.activationFactory('Windows.System.User').cast(IID_IUserStatics); }

    constructor(obj) {
        this._obj = obj.cast(IID_IUser);
    }
    static getDefault() {
        return new User(_IUserStatics2.method(6).invoke(User.s_IUserStatics2(), []));
    }
    static createWatcher() {
        return new UserWatcher(_IUserStatics.method(6).invoke(User.s_IUserStatics(), []));
    }
    static async _findAllAsync_1(signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IUserStatics.method(7).invoke(User.s_IUserStatics(), []);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_User(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    static async _findAllAsync_2(type, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IUserStatics.method(8).invoke(User.s_IUserStatics(), [DynWinRtValue.i32(type)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_User(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    static async _findAllAsync_3(type, status, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IUserStatics.method(9).invoke(User.s_IUserStatics(), [DynWinRtValue.i32(type), DynWinRtValue.i32(status)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IVectorView_User(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    static findAllAsync(...args) {
        if (args.length >= 2 && args[1] !== undefined && !(args[1] instanceof AbortSignal)) {
            return this._findAllAsync_3(args[0], args[1], args[2]);
        }
        if (args.length >= 1 && args[0] !== undefined && !(args[0] instanceof AbortSignal)) {
            return this._findAllAsync_2(args[0], args[1]);
        }
        return this._findAllAsync_1(args[0]);
    }
    static getFromId(nonRoamableId) {
        return new User(_IUserStatics.method(10).invoke(User.s_IUserStatics(), [DynWinRtValue.hstring(nonRoamableId)]));
    }
    get nonRoamableId() {
        return _IUser.method(6).invoke(this._obj, []).toString();
    }
    get authenticationStatus() {
        return _IUser.method(7).invoke(this._obj, []).toNumber();
    }
    get type() {
        return _IUser.method(8).invoke(this._obj, []).toNumber();
    }
    async getPropertyAsync(value, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IUser.method(9).invoke(this._obj, [DynWinRtValue.hstring(value)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v;
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async getPropertiesAsync(values, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IUser.method(10).invoke(this._obj, [(Array.isArray(values) ? DynWinRtValue.createVector(values.map(_i => DynWinRtValue.hstring(_i)), DynWinRtType.hstring()).cast(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.hstring()]).iid()) : _unwrap(values).cast(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.hstring()]).iid()))]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IPropertySet(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    async getPictureAsync(desiredSize, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IUser.method(11).invoke(this._obj, [DynWinRtValue.i32(desiredSize)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return new IRandomAccessStreamReference(_v);
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
    async checkUserAgeConsentGroupAsync(consentGroup, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IUser2.method(6).invoke(this._obj.cast(IID_IUser2), [DynWinRtValue.i32(consentGroup)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toNumber();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
}

export class IUser2 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IUser2(obj.cast(IID_IUser2));
    }

    async checkUserAgeConsentGroupAsync(consentGroup, signal) {
        if (signal?.aborted) throw signal.reason;
        const _op = _IUser2.method(6).invoke(this._obj, [DynWinRtValue.i32(consentGroup)]);
        const _onAbort = signal ? () => { try { _op.cancel(); } catch (_ce) { /* cancel after completion is a no-op per WinRT spec */ } } : undefined;
        if (_onAbort) { signal.addEventListener('abort', _onAbort, { once: true }); if (signal.aborted) _onAbort(); }
        try {
            const _v = await _op.toPromise();
            return _v.toNumber();
        } catch (_e) {
            if (signal?.aborted) throw signal.reason;
            throw _e;
        } finally {
            if (_onAbort) signal.removeEventListener('abort', _onAbort);
        }
    }
}
