// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { User } from './User.js';
import { UserAuthenticationStatus } from './UserAuthenticationStatus.js';
import { UserAuthenticationStatusChangeDeferral } from './UserAuthenticationStatusChangeDeferral.js';

const IID_IUserAuthenticationStatusChangingEventArgs = WinGuid.parse('8c030f28-a711-4c1e-ab48-04179c15938f');

const _IUserAuthenticationStatusChangingEventArgs = DynWinRtType.registerInterface(
    "IUserAuthenticationStatusChangingEventArgs", IID_IUserAuthenticationStatusChangingEventArgs)
    .addMethod("GetDeferral", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.System.UserAuthenticationStatusChangeDeferral', WinGuid.parse('88b59568-bb30-42fb-a270-e9902e40efa7'))))
    .addMethod("get_User", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))))
    .addMethod("get_NewStatus", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.System.UserAuthenticationStatus', ['Unauthenticated', 'LocallyAuthenticated', 'RemotelyAuthenticated'], [0, 1, 2])))
    .addMethod("get_CurrentStatus", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.System.UserAuthenticationStatus', ['Unauthenticated', 'LocallyAuthenticated', 'RemotelyAuthenticated'], [0, 1, 2])));

export class UserAuthenticationStatusChangingEventArgs {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IUserAuthenticationStatusChangingEventArgs);
    }
    getDeferral() {
        return new UserAuthenticationStatusChangeDeferral(_IUserAuthenticationStatusChangingEventArgs.method(6).invoke(this._obj, []));
    }
    get user() {
        return new User(_IUserAuthenticationStatusChangingEventArgs.method(7).invoke(this._obj, []));
    }
    get newStatus() {
        return _IUserAuthenticationStatusChangingEventArgs.method(8).invoke(this._obj, []).toNumber();
    }
    get currentStatus() {
        return _IUserAuthenticationStatusChangingEventArgs.method(9).invoke(this._obj, []).toNumber();
    }
}
