// Generated by dynwinrt-codegen — do not edit

export const UserWatcherStatus = Object.freeze({
    Created: 0,
    Started: 1,
    EnumerationCompleted: 2,
    Stopping: 3,
    Stopped: 4,
    Aborted: 5,
});
