// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IVectorView_UserWatcherUpdateKind } from './IVectorView_UserWatcherUpdateKind.js';
import { User } from './User.js';
import { UserWatcherUpdateKind } from './UserWatcherUpdateKind.js';

const IID_IUserChangedEventArgs = WinGuid.parse('086459dc-18c6-48db-bc99-724fb9203ccc');
const IID_IUserChangedEventArgs2 = WinGuid.parse('6b2ccb44-6f01-560c-97ad-fc7f32ec581f');

const _IUserChangedEventArgs = DynWinRtType.registerInterface(
    "IUserChangedEventArgs", IID_IUserChangedEventArgs)
    .addMethod("get_User", new DynWinRtMethodSig().addOut(DynWinRtType.runtimeClass('Windows.System.User', WinGuid.parse('df9a26c6-e746-4bcd-b5d4-120103c4209b'))));

const _IUserChangedEventArgs2 = DynWinRtType.registerInterface(
    "IUserChangedEventArgs2", IID_IUserChangedEventArgs2)
    .addMethod("get_ChangedPropertyKinds", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56'), [DynWinRtType.enumType('Windows.System.UserWatcherUpdateKind', ['Properties', 'Picture'], [0, 1])])));

export class UserChangedEventArgs {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IUserChangedEventArgs);
    }
    get user() {
        return new User(_IUserChangedEventArgs.method(6).invoke(this._obj, []));
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
    get changedPropertyKinds() {
        return new IVectorView_UserWatcherUpdateKind(_IUserChangedEventArgs2.method(6).invoke(this._obj.cast(IID_IUserChangedEventArgs2), []));
    }
}

export class IUserChangedEventArgs2 {
    _obj;

    constructor(obj) {
        this._obj = obj;
    }

    static from(obj) {
        return new IUserChangedEventArgs2(obj.cast(IID_IUserChangedEventArgs2));
    }

    get changedPropertyKinds() {
        return new IVectorView_UserWatcherUpdateKind(_IUserChangedEventArgs2.method(6).invoke(this._obj, []));
    }
}
