// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES } from './TypedEventHandler_UserWatcher_Object.js';
import { IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs.js';
import { IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES } from './TypedEventHandler_UserWatcher_UserChangedEventArgs.js';
import { UserAuthenticationStatusChangingEventArgs } from './UserAuthenticationStatusChangingEventArgs.js';
import { UserChangedEventArgs } from './UserChangedEventArgs.js';
import { UserWatcherStatus } from './UserWatcherStatus.js';

const IID_IUserWatcher = WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb');

const _IUserWatcher = DynWinRtType.registerInterface(
    "IUserWatcher", IID_IUserWatcher)
    .addMethod("get_Status", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.System.UserWatcherStatus', ['Created', 'Started', 'EnumerationCompleted', 'Stopping', 'Stopped', 'Aborted'], [0, 1, 2, 3, 4, 5])))
    .addMethod("Start", new DynWinRtMethodSig())
    .addMethod("Stop", new DynWinRtMethodSig())
    .addMethod("add_Added", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.runtimeClass('Windows.System.UserChangedEventArgs', WinGuid.parse('086459dc-18c6-48db-bc99-724fb9203ccc'))])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_Added", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("add_Removed", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.runtimeClass('Windows.System.UserChangedEventArgs', WinGuid.parse('086459dc-18c6-48db-bc99-724fb9203ccc'))])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_Removed", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("add_Updated", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.runtimeClass('Windows.System.UserChangedEventArgs', WinGuid.parse('086459dc-18c6-48db-bc99-724fb9203ccc'))])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_Updated", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("add_AuthenticationStatusChanged", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.runtimeClass('Windows.System.UserChangedEventArgs', WinGuid.parse('086459dc-18c6-48db-bc99-724fb9203ccc'))])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_AuthenticationStatusChanged", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("add_AuthenticationStatusChanging", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.runtimeClass('Windows.System.UserAuthenticationStatusChangingEventArgs', WinGuid.parse('8c030f28-a711-4c1e-ab48-04179c15938f'))])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_AuthenticationStatusChanging", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("add_EnumerationCompleted", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.object()])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_EnumerationCompleted", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("add_Stopped", new DynWinRtMethodSig().addIn(DynWinRtType.parameterized(WinGuid.parse('9de1c534-6ae1-11e0-84e1-18a905bcc53f'), [DynWinRtType.runtimeClass('Windows.System.UserWatcher', WinGuid.parse('155eb23b-242a-45e0-a2e9-3171fc6a7fbb')), DynWinRtType.object()])).addOut(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])))
    .addMethod("remove_Stopped", new DynWinRtMethodSig().addIn(DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()])));

export function unpackEventRegistrationToken(v) {
    const s = v.asStruct();
    return { value: s.getI64(0) };
}
const _unpackEventRegistrationToken = unpackEventRegistrationToken;
export const EventRegistrationToken_Type = DynWinRtType.structType('Windows.Foundation.EventRegistrationToken', [DynWinRtType.i64()]);
const _EventRegistrationToken_Type = EventRegistrationToken_Type;
export function packEventRegistrationToken(v) {
    const s = DynWinRtStruct.create(EventRegistrationToken_Type);
    s.setI64(0, v.value);
    return s;
}
const _packEventRegistrationToken = packEventRegistrationToken;

export class UserWatcher {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IUserWatcher);
    }
    get status() {
        return _IUserWatcher.method(6).invoke(this._obj, []).toNumber();
    }
    start() {
        _IUserWatcher.method(7).invoke(this._obj, []);
    }
    stop() {
        _IUserWatcher.method(8).invoke(this._obj, []);
    }
    onAdded(callback) {
        const wrapped = (__a0__, __a1__) => callback(new UserWatcher(__a0__), new UserChangedEventArgs(__a1__));
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES, wrapped);
        const __token = _IUserWatcher.method(9).invoke(this._obj, [handler.toValue()]);
        return () => { _IUserWatcher.method(10).invoke(this._obj, [__token]); };
    }
    onceAdded(callback) {
        const unsub = this.onAdded((...args) => { unsub(); callback(...args); });
        return unsub;
    }
    offAdded(token) {
        _IUserWatcher.method(10).invoke(this._obj, [token]);
    }
    onRemoved(callback) {
        const wrapped = (__a0__, __a1__) => callback(new UserWatcher(__a0__), new UserChangedEventArgs(__a1__));
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES, wrapped);
        const __token = _IUserWatcher.method(11).invoke(this._obj, [handler.toValue()]);
        return () => { _IUserWatcher.method(12).invoke(this._obj, [__token]); };
    }
    onceRemoved(callback) {
        const unsub = this.onRemoved((...args) => { unsub(); callback(...args); });
        return unsub;
    }
    offRemoved(token) {
        _IUserWatcher.method(12).invoke(this._obj, [token]);
    }
    onUpdated(callback) {
        const wrapped = (__a0__, __a1__) => callback(new UserWatcher(__a0__), new UserChangedEventArgs(__a1__));
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES, wrapped);
        const __token = _IUserWatcher.method(13).invoke(this._obj, [handler.toValue()]);
        return () => { _IUserWatcher.method(14).invoke(this._obj, [__token]); };
    }
    onceUpdated(callback) {
        const unsub = this.onUpdated((...args) => { unsub(); callback(...args); });
        return unsub;
    }
    offUpdated(token) {
        _IUserWatcher.method(14).invoke(this._obj, [token]);
    }
    onAuthenticationStatusChanged(callback) {
        const wrapped = (__a0__, __a1__) => callback(new UserWatcher(__a0__), new UserChangedEventArgs(__a1__));
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_UserWatcher_UserChangedEventArgs, TypedEventHandler_UserWatcher_UserChangedEventArgs_PARAM_TYPES, wrapped);
        const __token = _IUserWatcher.method(15).invoke(this._obj, [handler.toValue()]);
        return () => { _IUserWatcher.method(16).invoke(this._obj, [__token]); };
    }
    onceAuthenticationStatusChanged(callback) {
        const unsub = this.onAuthenticationStatusChanged((...args) => { unsub(); callback(...args); });
        return unsub;
    }
    offAuthenticationStatusChanged(token) {
        _IUserWatcher.method(16).invoke(this._obj, [token]);
    }
    onAuthenticationStatusChanging(callback) {
        const wrapped = (__a0__, __a1__) => callback(new UserWatcher(__a0__), new UserAuthenticationStatusChangingEventArgs(__a1__));
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs, TypedEventHandler_UserWatcher_UserAuthenticationStatusChangingEventArgs_PARAM_TYPES, wrapped);
        const __token = _IUserWatcher.method(17).invoke(this._obj, [handler.toValue()]);
        return () => { _IUserWatcher.method(18).invoke(this._obj, [__token]); };
    }
    onceAuthenticationStatusChanging(callback) {
        const unsub = this.onAuthenticationStatusChanging((...args) => { unsub(); callback(...args); });
        return unsub;
    }
    offAuthenticationStatusChanging(token) {
        _IUserWatcher.method(18).invoke(this._obj, [token]);
    }
    onEnumerationCompleted(callback) {
        const wrapped = (__a0__, __a1__) => callback(new UserWatcher(__a0__), __a1__);
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES, wrapped);
        const __token = _IUserWatcher.method(19).invoke(this._obj, [handler.toValue()]);
        return () => { _IUserWatcher.method(20).invoke(this._obj, [__token]); };
    }
    onceEnumerationCompleted(callback) {
        const unsub = this.onEnumerationCompleted((...args) => { unsub(); callback(...args); });
        return unsub;
    }
    offEnumerationCompleted(token) {
        _IUserWatcher.method(20).invoke(this._obj, [token]);
    }
    onStopped(callback) {
        const wrapped = (__a0__, __a1__) => callback(new UserWatcher(__a0__), __a1__);
        const handler = DynWinRtDelegate.create(IID_TypedEventHandler_UserWatcher_Object, TypedEventHandler_UserWatcher_Object_PARAM_TYPES, wrapped);
        const __token = _IUserWatcher.method(21).invoke(this._obj, [handler.toValue()]);
        return () => { _IUserWatcher.method(22).invoke(this._obj, [__token]); };
    }
    onceStopped(callback) {
        const unsub = this.onStopped((...args) => { unsub(); callback(...args); });
        return unsub;
    }
    offStopped(token) {
        _IUserWatcher.method(22).invoke(this._obj, [token]);
    }
}
