// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from '@microsoft/dynwinrt';
import { IIterable_IKeyValuePair_String_Object } from './IIterable_IKeyValuePair_String_Object.js';
import { IIterable_String } from './IIterable_String.js';
import { IKeyValuePair_String_Object } from './IKeyValuePair_String_Object.js';
import { IMap_String_Object } from './IMap_String_Object.js';
import { IReference_Double } from './IReference_Double.js';
import { IVector_String } from './IVector_String.js';
import { VideoOrientation } from './VideoOrientation.js';
import { IID_IStorageItemExtraProperties, IStorageItemExtraProperties } from './IStorageItemExtraProperties.js';

const IID_IVideoProperties = WinGuid.parse('719ae507-68de-4db8-97de-49998c059f2f');

const _IVideoProperties = DynWinRtType.registerInterface(
    "IVideoProperties", IID_IVideoProperties)
    .addMethod("get_Rating", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("put_Rating", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("get_Keywords", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_Width", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_Height", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_Duration", new DynWinRtMethodSig().addOut(DynWinRtType.structType('Windows.Foundation.TimeSpan', [DynWinRtType.i64()])))
    .addMethod("get_Latitude", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('61c17706-2d65-11e0-9ae8-d48564015472'), [DynWinRtType.f64()])))
    .addMethod("get_Longitude", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('61c17706-2d65-11e0-9ae8-d48564015472'), [DynWinRtType.f64()])))
    .addMethod("get_Title", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Title", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Subtitle", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Subtitle", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Producers", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_Publisher", new DynWinRtMethodSig().addOut(DynWinRtType.hstring()))
    .addMethod("put_Publisher", new DynWinRtMethodSig().addIn(DynWinRtType.hstring()))
    .addMethod("get_Writers", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_Year", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("put_Year", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
    .addMethod("get_Bitrate", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
    .addMethod("get_Directors", new DynWinRtMethodSig().addOut(DynWinRtType.parameterized(WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d'), [DynWinRtType.hstring()])))
    .addMethod("get_Orientation", new DynWinRtMethodSig().addOut(DynWinRtType.enumType('Windows.Storage.FileProperties.VideoOrientation', ['Normal', 'Rotate90', 'Rotate180', 'Rotate270'], [0, 90, 180, 270])));

export function unpackTimeSpan(v) {
    const s = v.asStruct();
    return { duration: s.getI64(0) };
}
const _unpackTimeSpan = unpackTimeSpan;
export const TimeSpan_Type = DynWinRtType.structType('Windows.Foundation.TimeSpan', [DynWinRtType.i64()]);
const _TimeSpan_Type = TimeSpan_Type;
export function packTimeSpan(v) {
    const s = DynWinRtStruct.create(TimeSpan_Type);
    s.setI64(0, v.duration);
    return s;
}
const _packTimeSpan = packTimeSpan;

export class VideoProperties {
    _obj;

    constructor(obj) {
        this._obj = obj.cast(IID_IVideoProperties);
    }
    get rating() {
        return _IVideoProperties.method(6).invoke(this._obj, []).toNumber();
    }
    set rating(value) {
        _IVideoProperties.method(7).invoke(this._obj, [DynWinRtValue.u32(value)]);
    }
    get keywords() {
        return new IVector_String(_IVideoProperties.method(8).invoke(this._obj, []));
    }
    get width() {
        return _IVideoProperties.method(9).invoke(this._obj, []).toNumber();
    }
    get height() {
        return _IVideoProperties.method(10).invoke(this._obj, []).toNumber();
    }
    get duration() {
        return _unpackTimeSpan(_IVideoProperties.method(11).invoke(this._obj, []));
    }
    get latitude() {
        return new IReference_Double(_IVideoProperties.method(12).invoke(this._obj, []));
    }
    get longitude() {
        return new IReference_Double(_IVideoProperties.method(13).invoke(this._obj, []));
    }
    get title() {
        return _IVideoProperties.method(14).invoke(this._obj, []).toString();
    }
    set title(value) {
        _IVideoProperties.method(15).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }
    get subtitle() {
        return _IVideoProperties.method(16).invoke(this._obj, []).toString();
    }
    set subtitle(value) {
        _IVideoProperties.method(17).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }
    get producers() {
        return new IVector_String(_IVideoProperties.method(18).invoke(this._obj, []));
    }
    get publisher() {
        return _IVideoProperties.method(19).invoke(this._obj, []).toString();
    }
    set publisher(value) {
        _IVideoProperties.method(20).invoke(this._obj, [DynWinRtValue.hstring(value)]);
    }
    get writers() {
        return new IVector_String(_IVideoProperties.method(21).invoke(this._obj, []));
    }
    get year() {
        return _IVideoProperties.method(22).invoke(this._obj, []).toNumber();
    }
    set year(value) {
        _IVideoProperties.method(23).invoke(this._obj, [DynWinRtValue.u32(value)]);
    }
    get bitrate() {
        return _IVideoProperties.method(24).invoke(this._obj, []).toNumber();
    }
    get directors() {
        return new IVector_String(_IVideoProperties.method(25).invoke(this._obj, []));
    }
    get orientation() {
        return _IVideoProperties.method(26).invoke(this._obj, []).toNumber();
    }
    as(InterfaceClass) {
        return InterfaceClass.from(this._obj);
    }
}
