// Generated by dynwinrt-codegen — do not edit
import { DynWinRtType, DynWinRtValue, DynWinRtStruct } from '@microsoft/dynwinrt';
import { IReference_Double } from './IReference_Double.js';
import { IVector_String } from './IVector_String.js';
import { VideoOrientation } from './VideoOrientation.js';

export interface TimeSpan {
    duration: bigint;
}
/** Convert a WinRT struct value into a `TimeSpan` object. */
export declare function unpackTimeSpan(v: DynWinRtValue): TimeSpan;
export declare const TimeSpan_Type: DynWinRtType;
/** Convert a `TimeSpan` object into a WinRT struct value. */
export declare function packTimeSpan(v: TimeSpan): DynWinRtStruct;

export declare class VideoProperties {
    private constructor();
    get rating(): number;
    set rating(value: number);
    get keywords(): IVector_String;
    get width(): number;
    get height(): number;
    get duration(): TimeSpan;
    get latitude(): IReference_Double;
    get longitude(): IReference_Double;
    get title(): string;
    set title(value: string);
    get subtitle(): string;
    set subtitle(value: string);
    get producers(): IVector_String;
    get publisher(): string;
    set publisher(value: string);
    get writers(): IVector_String;
    get year(): number;
    set year(value: number);
    get bitrate(): number;
    get directors(): IVector_String;
    get orientation(): VideoOrientation;
    /** Cast this object to another WinRT interface. */
    as<T>(InterfaceClass: { from(obj: any): T }): T;
}
