import { useTranslation } from 'react-i18next';
import { AlertCircle, ExternalLink, Gauge } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Switch } from '@/components/ui/switch';
import type { DependencyManagementTabProps } from '../types';

export default function EnvironmentTab({ snapshot, onOpenNodeEnvironmentFaq, onUpdateMirrorSettings, isSavingMirrorSettings, mirrorRegistryUrl, mirrorSaveError }: DependencyManagementTabProps) {
  const { t } = useTranslation('common');
  return <div className="space-y-5">
    <Card><CardHeader><CardTitle className="text-lg">{t('dependencyManagement.environment.title')}</CardTitle><CardDescription>{t(`dependencyManagement.environment.sourceLabel.${snapshot.environment.source}`)}</CardDescription></CardHeader><CardContent><Badge variant="outline">{snapshot.environment.nodeVersion ?? t('dependencyManagement.environment.unavailable')}</Badge></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Gauge className="h-5 w-5" />{t('dependencyManagement.environment.title')}</CardTitle><CardDescription>{t('dependencyManagement.environment.description')}</CardDescription></CardHeader><CardContent className="space-y-4">
      <div className="rounded-lg border bg-muted/30 p-4"><p className="text-sm font-medium">{t('dependencyManagement.environment.rationaleTitle')}</p><p className="mt-2 text-sm text-muted-foreground">{t('dependencyManagement.environment.externalNotice')}</p><Button type="button" variant="outline" size="sm" className="mt-3 gap-2" onClick={onOpenNodeEnvironmentFaq}><ExternalLink className="h-4 w-4" />{t('dependencyManagement.environment.faqLinkLabel')}</Button></div>
      <div className="grid gap-4 md:grid-cols-2">{(['node', 'npm'] as const).map((component) => { const item = snapshot.environment[component]; return <div key={component} className="rounded-lg border p-4"><div className="mb-2 flex items-center justify-between gap-3"><span className="font-medium uppercase">{component}</span><Badge variant={item.status === 'available' ? 'default' : 'destructive'}>{t(`dependencyManagement.environment.status.${item.status}`)}</Badge></div><p className="text-sm text-muted-foreground">{t('dependencyManagement.environment.version')}: {item.version ?? t('dependencyManagement.unavailable')}</p><p className="break-all text-sm text-muted-foreground">{item.executablePath}</p>{item.message && <p className="mt-2 text-sm text-destructive">{item.message}</p>}</div>; })}<div className="rounded-lg border p-4 md:col-span-2"><p className="text-sm font-medium">{t('dependencyManagement.environment.source')}</p><p className="break-all text-sm text-muted-foreground">{t(`dependencyManagement.environment.sourceLabel.${snapshot.environment.source}`)}</p><p className="mt-3 text-sm font-medium">{t('dependencyManagement.environment.nodeMajorVersion')}</p><p className="break-all text-sm text-muted-foreground">node{snapshot.environment.nodeMajorVersion}</p><p className="mt-3 text-sm font-medium">{t('dependencyManagement.environment.globalPrefix')}</p><p className="break-all text-sm text-muted-foreground">{snapshot.environment.npmGlobalPrefix}</p><p className="mt-3 text-sm font-medium">{t('dependencyManagement.environment.globalModulesRoot')}</p><p className="break-all text-sm text-muted-foreground">{snapshot.environment.npmGlobalModulesRoot}</p></div></div>
    </CardContent></Card>
    <Card><CardHeader><CardTitle className="text-lg">{t('dependencyManagement.mirror.title')}</CardTitle><CardDescription>{t('dependencyManagement.mirror.description')}</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-4 rounded-lg border bg-card p-4"><div className="space-y-2"><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{t('dependencyManagement.mirror.toggleLabel')}</span><Badge variant={snapshot.mirrorSettings.enabled ? 'default' : 'secondary'}>{isSavingMirrorSettings ? t('dependencyManagement.mirror.saving') : snapshot.mirrorSettings.enabled ? t('dependencyManagement.mirror.enabled') : t('dependencyManagement.mirror.disabled')}</Badge></div><p className="break-all text-sm text-muted-foreground">{t('dependencyManagement.mirror.registryUrl')}: {mirrorRegistryUrl}</p><p className="text-sm text-muted-foreground">{snapshot.mirrorSettings.enabled ? t('dependencyManagement.mirror.enabledHelp') : t('dependencyManagement.mirror.disabledHelp')}</p></div><Switch checked={snapshot.mirrorSettings.enabled} onCheckedChange={(enabled) => void onUpdateMirrorSettings(enabled)} disabled={isSavingMirrorSettings} aria-label={t('dependencyManagement.mirror.toggleLabel')} /></div>{mirrorSaveError && <Alert variant="destructive"><AlertCircle className="h-4 w-4" /><AlertTitle>{t('dependencyManagement.mirror.saveFailed')}</AlertTitle><AlertDescription>{mirrorSaveError}</AlertDescription></Alert>}</CardContent></Card>
  </div>;
}
